### ISSUE TITLE
Error on Update - paperless-ngx

### ISSUE THREAD

**Issue by coolduke666** [community-scripts/ProxmoxVE#10]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

running the update script I get the following error:

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx.sh)"`

- Updating to v2.13.2   
[ERROR] in line 93: exit code 0: while executing command pip install -r requirements.txt &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by Mellowlynx** [comment]
Execute `rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED` in the LXC console and try again.

**Comment by Mellowlynx** [comment]
@MickLesk I see this one regularly, we should add an announcement within the discussions so we can revere to it, like tteck did.
(https://github.com/tteck/Proxmox/discussions/3300)

**Comment by coolduke666** [comment]
Didn't solve it - same error again

I didn't have a dirctory called 'EXTERNALLY-MANGED" in any of the python3.* - I have python3.9 and python3.11

how to sove it?
