### ISSUE TITLE
Checkmk install fails

### ISSUE THREAD

**Issue by thost96** [community-scripts/ProxmoxVE#1003]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

checkmk

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/checkmk.sh)"

### 📝 Provide a clear and concise description of the issue.

ChechMK Installation fails von Ubuntu 24.04 with the error below. Depencies are unmed for Install. 

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Ubuntu 24.04

### 🔄 Steps to reproduce the issue.

🧩  Using Advanced Settings on node prox-1
  🖥️  Operating System: ubuntu
  🌟  Version: 24.04
  📦  Container Type: Unprivileged
  🔐  Root Password: ********
  🆔  Container ID: 304
  🏠  Hostname: checkmk
  💾  Disk Size: 4
  🧠  CPU Cores: 2
  🛠️  RAM Size: 2048
  🌉  Bridge: vmbr1
  📡  IP Address:  ********
  🌐  Gateway IP Address:  ********
  📡  APT-Cacher IP Address: Default
  🚫  Disable IPv6: no
  ⚙️  Interface MTU Size: Default
  🔍  DNS Search Domain: Host
  📡  DNS Server IP Address: Host
  🏷️  Vlan: Default
  🔑  Root SSH Access: yes
  🔍  Verbose Mode: yes
  🚀  Creating a checkmk LXC using the above advanced settings
  ✔️  Using  ******** for Template Storage.
  ✔️  Using  ******** for Container Storage.
  ✔️  Updated LXC Template List
  ✔️  LXC Container 304 was successfully created.
  ✔️  Started LXC Container
  ✔️  Set up Container OS
  ✔️  Network Connected:  ********
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.121.4

### ❌ Paste the full error output (if available).

✔️  Installed Dependencies
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
 ⠴Note, selecting 'check-mk-raw-2.3.0p23' instead of '/opt/checkmk.deb'
 ⠇Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ⠸ check-mk-raw-2.3.0p23 : Depends: libpango1.0-0 but it is not installable
                         Depends: libperl5.36 but it is not installable
E: Unable to correct problems, you have held broken packages.

[ERROR] in line 27: exit code 0: while executing command $STD apt-get install -y /opt/checkmk.deb

**Comment by michelroegl-brunner** [comment]
You can only install it on debian. We do not support ubuntu in this case, because we would have to download each binary depending on is. please use debian 12.
