### ISSUE TITLE
Proxmox-Datacenter Manager

### ISSUE THREAD

**Issue by hypermoist** [community-scripts/ProxmoxVE#1012]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Proxmox-Datacenter Manager

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/proxmox-datacenter-manager.sh)"

### 📝 Provide a clear and concise description of the issue.

When trying to run the install script the script fails with a bunch of bash errors

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Just run the install script

### ❌ Paste the full error output (if available).

```
/dev/fd/63: line 1: 404:: command not found
bash: line 19: header_info: command not found
bash: line 20: base_settings: command not found
bash: line 23: variables: command not found
bash: line 24: color: command not found
bash: line 25: catch_errors: command not found
bash: line 39: start: command not found
bash: line 40: build_container: command not found
bash: line 41: description: command not found
bash: line 43: msg_ok: command not found
proxmox-datacenter-manager setup has been successfully initialized!
 Access it using the following URL:
https://:8443
```

**Comment by rbradley0** [comment]
On [Line 2](https://github.com/community-scripts/ProxmoxVE/blob/cf8dd2bfac113665d6ee4ea550f13ce4c2ebe2cc/ct/proxmox-datacenter-manager.sh#L2) of the Proxmox Datacenter Manager setup script, it includes `raw` in the source url for build.func which is an error.

If you were to download the setup script and manually remove it, the script will work correctly.

It should look as follows:
```diff
- source <(curl -s https://raw.githubusercontent.com/community-scripts/ProxmoxVE/raw/main/misc/build.func)
+ source <(curl -s https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/misc/build.func)
```

**Comment by hypermoist** [comment]
> ```diff
> source <(curl -s https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/misc/build.func)
> ```

Can Confirm this was the issue :)
