### ISSUE TITLE
Error updating Open WebUI

### ISSUE THREAD

**Issue by Builder-DE-TH** [community-scripts/ProxmoxVE#1014]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Open WebUI

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

On updating this error is output

`[ERROR] in line 164: exit code 0: while executing command apt-get install -y figlet &> /dev/null`

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

update

### ❌ Paste the full error output (if available).

[ERROR] in line 164: exit code 0: while executing command apt-get install -y figlet &> /dev/null

**Comment by MickLesk** [comment]
Install figlet on your lxc. Or apt autoremove before
