### ISSUE TITLE
CT Tags are not applied if Container is installed with "Advanced Settings"

### ISSUE THREAD

**Issue by andygrunwald** [community-scripts/ProxmoxVE#1016]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

prometheus

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/prometheus.sh)"

### 📝 Provide a clear and concise description of the issue.

If you install Prometheus with the "Default settings", the tag `monitoring` is getting applied, see https://github.com/community-scripts/ProxmoxVE/blob/9b07fe41785e9fd11bb4f9245e1511ea1aab59c6/ct/prometheus.sh#L10C11-L10C21
Like in ![Screenshot 2024-12-25 at 18 19 41](https://github.com/user-attachments/assets/bcaac2c3-12f7-4935-b9a9-d6f82f9b1da7)

If you install with "Advances settings", only the `community-scripts` tag gets applied.
<img width="471" alt="Screenshot 2024-12-26 at 10 25 34" src="https://github.com/user-attachments/assets/cabe2d1a-e506-431a-b940-f6407816c2f6" />

### ⚙️ What settings are you using?

- [X] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Run installation of prometheus with default and advanced settings: bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/prometheus.sh)"

### ❌ Paste the full error output (if available).

No error output available

**Comment by dsiebel** [comment]
Can confirm. 
In advanced settings the tags are being set to `community-scripts;`, which replaces the settings from `base_settings`:
https://github.com/community-scripts/ProxmoxVE/blob/main/misc/build.func#L320

**Comment by TheRealVira** [comment]
If it helps any, I set up a PR to reverse tags to `proxmox-helper-scripts` and include `var_tags` for advanced setup: https://github.com/community-scripts/ProxmoxVE/pull/1038
