### ISSUE TITLE
Hoarder LXC script fails during instalation

### ISSUE THREAD

**Issue by cino** [community-scripts/ProxmoxVE#1020]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Hoarderr

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/hoarder.sh)"

### 📝 Provide a clear and concise description of the issue.

When installing the Hoarder LXC it gives an error and is not able to install.

### ⚙️ What settings are you using?

- Default Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Step 1:

Execute: `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/hoarder.sh)"`

Step 2: 

Look at error :)

### ❌ Paste the full error output (if available).

[ERROR] in line 164: exit code 0: while executing command apt-get install -y figlet &> /dev/null

### 🖼️ Additional context (optional).

<img width="876" alt="image" src="https://github.com/user-attachments/assets/ca5f9255-e023-449c-b787-87eb31b89e00" />

**Comment by MickLesk** [comment]
Install figlet on your Proxmox Node. You have deprecated apts

**Comment by cino** [comment]
@MickLesk Shouldn't that be handled by the command? And/or otherwise can we add this to the documentation if it's that common

**Comment by MickLesk** [comment]
Thats Not normal. Something broken in your Proxmox. Enter apt-get Install figlet and Check Output

**Comment by CNCMK** [comment]
leider habe ich das gleiche.
![Screenshot 2024-12-27 161507](https://github.com/user-attachments/assets/16a01544-86c4-4c80-a44c-5d04455e9f45)
![Screenshot 2024-12-27 162058](https://github.com/user-attachments/assets/313c1adb-9068-44ae-85b2-b8042a0e607a)

**Comment by MickLesk** [comment]
Beste Meldung bisher, da fehlt eine repo. Kann ich hinzufügen im Script. Nächste Woche. Warum du so wenig Repos hast, k.a.

**Comment by CNCMK** [comment]
Ich habe das soweit lösen können.
Andere Repos benutzen
---------------------------------------
Wir empfehlen, dieses Repository in /etc/apt/sources.list zu konfigurieren .

Datei /etc/apt/sources.list
deb http://ftp.debian.org/debian bookworm main contrib 
deb http://ftp.debian.org/debian bookworm-updates main contrib 

# Proxmox VE pve-no-subscription-Repository bereitgestellt von proxmox.com, 
# NICHT für den Produktionseinsatz empfohlen 
deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription 

# Sicherheitsupdates 
deb http://security.debian.org/debian-security bookworm-security main contrib
-------------------------------------
