### ISSUE TITLE
MongoDB Install : old Version

### ISSUE THREAD

**Issue by Belocin** [community-scripts/ProxmoxVE#1030]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

mongodb

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/mongodb.sh)"

### 📝 Provide a clear and concise description of the issue.

This install provide a LXC of MongoDB 7.x
MongoDB 8 has been released 2 mouths ago, would it be possible to adapt scripts ?

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/mongodb.sh)"

### ❌ Paste the full error output (if available).

db version v7.0.16
Build Info: {
    "version": "7.0.16",
    "gitVersion": "18b949444cfdaa88e30b0e10243bc18268251c1f",
    "openSSLVersion": "OpenSSL 3.0.15 3 Sep 2024",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "debian12",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}

**Comment by MickLesk** [comment]
done for new installations
