### ISSUE TITLE
build.func fehlerhaft?

### ISSUE THREAD

**Issue by CNCMK** [community-scripts/ProxmoxVE#1037]
### ✅ Have you read and understood the above guidelines?

ja

### 📜 What is the name of the script you are using?

build.func

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/influxdb.sh)"

### 📝 Provide a clear and concise description of the issue.

![Screenshot 2024-12-27 152320](https://github.com/user-attachments/assets/cc1e5cea-336b-465b-a61d-c42aed792d2f)

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Ubuntu 22.04

### 🔄 Steps to reproduce the issue.

1

### ❌ Paste the full error output (if available).

1

**Comment by CNCMK** [comment]
Leider bekomme ich diese Meldung

**Comment by MickLesk** [comment]
No, you have apt Problems. I build next week N workaround

**Comment by TheRealVira** [comment]
I just experienced the exact same issue for nginxproxymanager. Hours later it resumed "working" again, but now man-db is stuck processing. I did some digging on the previous issue and I found this entry in the logs:

> Err:1 http://deb.debian.org/debian bookworm InRelease   Unknown error executing apt-key

Perhaps http://deb.debian.org/debian/dists/bookworm/InRelease was down for some time? Does it work for you now?

**Comment by CNCMK** [comment]
Nein funktioniert immer noch nicht. In meiner Repo ist einfach nicht der figlet enthalten. Es soll wohl so sein, dass in der standard Repo dieser immer fehlt.

**Comment by CNCMK** [comment]
Ich habe das soweit lösen können.
Andere Repos benutzen
---------------------------------------
Wir empfehlen, dieses Repository in /etc/apt/sources.list zu konfigurieren .

Datei /etc/apt/sources.list
deb http://ftp.debian.org/debian bookworm main contrib 
deb http://ftp.debian.org/debian bookworm-updates main contrib 

# Proxmox VE pve-no-subscription-Repository bereitgestellt von proxmox.com, 
# NICHT für den Produktionseinsatz empfohlen 
deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription 

# Sicherheitsupdates 
deb http://security.debian.org/debian-security bookworm-security main contrib
-------------------------------------

**Comment by MickLesk** [comment]
Fix is done #1044
