### ISSUE TITLE
BunkerWeb LXC Script doesnt work

### ISSUE THREAD

**Issue by Madoka2000** [community-scripts/ProxmoxVE#1054]
### ✅ Have you read and understood the above guidelines?

Yes

### 📜 What is the name of the script you are using?

BunkerWeb LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/bunkerweb.sh)"

### 📝 Provide a clear and concise description of the issue.

Hi,

The script seem to be broken. The "UI" doesn't even show.

![image](https://github.com/user-attachments/assets/e9d3315a-260f-40dd-8a91-3200fa2e7e3c)

### ⚙️ What settings are you using?

- [ ] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Just call the script "bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/bunkerweb.sh)""

### ❌ Paste the full error output (if available).

[ERROR] in line 168: exit code 0: while executing command apt-get install -y figlet &> /dev/null

### 🖼️ Additional context (optional).

![image](https://github.com/user-attachments/assets/e9d3315a-260f-40dd-8a91-3200fa2e7e3c)

**Comment by MickLesk** [comment]
When you execute it? Ive fixed 3h ago a bug with figlet

**Comment by Madoka2000** [comment]
> When you execute it? Ive fixed 3h ago a bug with figlet

Yeah, but executing dpkg --configure -a and reinstalling figlet manually seem to have resolved the issue. It was probably due to an incoherent state
