### ISSUE TITLE
Heimdall script error

### ISSUE THREAD

**Issue by kampfhanuta** [community-scripts/ProxmoxVE#1058]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Heimdall Dashboard LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/heimdall-dashboard.sh)"

### 📝 Provide a clear and concise description of the issue.

[ERROR] in line 25: exit code 0: while executing command RELEASE=$(curl -sX GET "https://api.github.com/repos/linuxserver/Heimdall/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/heimdall-dashboard.sh)"

### ❌ Paste the full error output (if available).

[ERROR] in line 25: exit code 0: while executing command RELEASE=$(curl -sX GET "https://api.github.com/repos/linuxserver/Heimdall/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')

**Comment by quantumryuu** [comment]
Works good on my end!
![image](https://github.com/user-attachments/assets/d7282f34-37f4-4d54-bae0-59e61945002d)

Can you try running in the proxmox shell the following commands?
`RELEASE=$(curl -sX GET "https://api.github.com/repos/linuxserver/Heimdall/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')`
`echo ${RELEASE}`

**Comment by kampfhanuta** [comment]
v2.6.3

**Comment by kampfhanuta** [comment]
Today I tried again with IPv4, this worked. Dont know why only this script with IPv6 doesn't worked on my machine.

**Comment by MickLesk** [comment]
When was the issue?

**Comment by Builder-DE-TH** [comment]
When I updated from 2.6.1 to 2.6.3, typing update did nothing, pasting the script gave a fail error, then I couldn't connect but after a reboot it said it had updated successfully.
