### ISSUE TITLE
Plex LXC Update Script Bug

### ISSUE THREAD

**Issue by Outsmart2383** [community-scripts/ProxmoxVE#1061]
### ✅ Have you read and understood the above guidelines?

Yes

### 📜 What is the name of the script you are using?

Plex (Update command)

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

Running `update` in the console of your Plex LXC to update it gives the following error:

` ⠋ Updating Plex LXC 
[ERROR] in line 41: exit code 0: while executing command apt-get update &> /dev/null`

There was a previous issue raised for this, it was closed because the reporter was using the wrong Ubuntu version, however, this continues to be an issue. Previous issue: https://github.com/community-scripts/ProxmoxVE/issues/794

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Ubuntu 22.04

### 🔄 Steps to reproduce the issue.

Running command `update` 

### ❌ Paste the full error output (if available).

` ⠋ Updating Plex LXC 
[ERROR] in line 41: exit code 0: while executing command apt-get update &> /dev/null`

**Comment by thebatfink** [comment]
I also have the tteck plex lxc, updated with the update script https://github.com/community-scripts/ProxmoxVE/raw/main/misc/update-repo.sh.

When performing update in the plex lxc, same error:

` ⠏ Updating Plex LXC 
[ERROR] in line 41: exit code 0: while executing command apt-get update &> /dev/null `

Ubuntu:

`Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy `

**Comment by lurkus** [comment]
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```

Same here. When manually running `apt-get update`, I get the following output:

```
apt-get update
Hit:1 https://downloads.plex.tv/repo/deb public InRelease
Get:2 http://ftp.debian.org/debian bookworm InRelease [151 kB]              
Err:2 http://ftp.debian.org/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
W: GPG error: http://ftp.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
E: The repository 'http://ftp.debian.org/debian bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by MickLesk** [comment]
fixed generally with newest Breaking Change

**Comment by thebatfink** [comment]
> fixed generally with newest Breaking Change

What does this mean?

**Comment by MickLesk** [comment]
remove the wrong source and then enter update again

**Comment by thebatfink** [comment]
Seems OK. For anyone unsure:

`sudo nano /etc/apt/sources.list` delete the debian line, save file.
