### ISSUE TITLE
Homepage Dashboard release branch

### ISSUE THREAD

**Issue by pafade89** [community-scripts/ProxmoxVE#1062]
### ✅ Have you read and understood the above guidelines?

Yes

### 📜 What is the name of the script you are using?

Homepage Dashboard 

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/homepage.sh)"

### 📝 Provide a clear and concise description of the issue.

I think it make sense not to use the dev branch but instead ne single releases. Also an benefit is that after switching the branch tbe version is shown correct in the right corner of homepage.

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

No version in the right low corner ;)

### ❌ Paste the full error output (if available).

No errors

**Comment by se-bastiaan** [comment]
If I read your issue correctly, you are proposing the use of homepage releases instead of pulling from the dev branch. Is that correct?

The script currently looks at the latest release on GitHub and then downloads the attached zip file. So I would say that what you want is already how it works.

**Comment by pafade89** [comment]
Thank you for your fast response. When I use your command the following version indicator is now shown:

![image](https://github.com/user-attachments/assets/13fceb36-c14c-4213-bbc7-3c7debf9082e)

**Comment by se-bastiaan** [comment]
Yes I meant that the script needs to be adjusted to set the version. If you want to set it to a specific version with the application already installed you should set `NEXT_PUBLIC_VERSION=v0.10.6`

**Comment by pafade89** [comment]
@se-bastiaan Thank you very much =)

**Comment by se-bastiaan** [comment]
could we reopen this?

**Comment by MickLesk** [comment]
yep

**Comment by pafade89** [comment]
It still doesn't seem to be working properly.

![Screenshot_2025-01-01-12-56-28-323_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/061fb6b1-fc9c-4c77-8047-4034abdc4af4)

**Comment by MickLesk** [comment]
New PR needed only

**Comment by MickLesk** [comment]
Please Test the new merge in 10-15min again and give Feedback

**Comment by pafade89** [comment]
For me, it works now perfectly. =)

![image](https://github.com/user-attachments/assets/a5dabc27-4a27-4244-bba5-194238f774a4)
