### ISSUE TITLE
mariadb container not updating

### ISSUE THREAD

**Issue by tmkis2** [community-scripts/ProxmoxVE#1075]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

MariaDB

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/mariadb.sh)"

### 📝 Provide a clear and concise description of the issue.

When executing `update` or
```
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/mariadb.sh)"
```
in MariaDB Container created with the same command before it checks for:
`/etc/apt/sources.list.d/mariadb.list`
and doesn't find it - canceling an update.

### ⚙️ What settings are you using?

- [X] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

1. install a new mariadb container
2. enter container
3. type update

### ❌ Paste the full error output (if available).

✖️  No MariaDB Installation Found!

**Comment by MickLesk** [comment]
Done
