### ISSUE TITLE
Guacamole Script / Font error

### ISSUE THREAD

**Issue by phantum29** [community-scripts/ProxmoxVE#1083]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Apache Guacamole LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/apache-guacamole.sh)"

### 📝 Provide a clear and concise description of the issue.

After executing the script, and answering "yes" to create a new Apache-Guacamole LXC question, I get a font error. I can't seem to acquire the missing font either.

### ⚙️ What settings are you using?

- [ ] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

run `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/apache-guacamole.sh)"` and respond to create a new LXC

### ❌ Paste the full error output (if available).

`error: could not load font slant

[ERROR] in line 227: exit code 0: while executing command ascii_art=$(figlet -f slant -w "$term_width" "$APP"`

**Comment by phantum29** [comment]
Ah, well I installed figlet to get the included font "Slant" this seems to have solved the problem, but I'm not sure if this was an unexpected result and needs to be addressed or not.

**Comment by MickLesk** [comment]
Fixed since Yesterday, dont know why you Report this
