### ISSUE TITLE
Teddycloud Script Exit with Error

### ISSUE THREAD

**Issue by StefanX13** [community-scripts/ProxmoxVE#1088]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

TeddyCloud LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/teddycloud.sh)"

### 📝 Provide a clear and concise description of the issue.

  ⚙️  Using Default Settings on node proxmox
  🖥️  Operating System: debian
  🌟  Version: 12
  📦  Container Type: Unprivileged
  💾  Disk Size: 8GB
  🧠  CPU Cores: 2
  🛠️  RAM Size: 1024MB
  🆔  Container ID: 107
  🚀  Creating a TeddyCloud LXC using the above default settings
  
  ✔️  Using local for Template Storage.
  ✔️  Using local-lvm for Container Storage.
  ✔️  Updated LXC Template List
  ✔️  LXC Container 107 was successfully created.
  ✔️  Started LXC Container
  ✔️  Set up Container OS
  ✔️  Network Connected: 192.168.178.124 2a02:908:8b7:e280:be24:11ff:fe37:1ee9 
  ✔️  IPv4 Internet Connected
  ✔️  IPv6 Internet Connected
  ✔️  DNS Resolved github.com to 140.82.121.4
  ✔️  Updated Container OS
  ✔️  Installed Dependencies
 ⠼bash: line 31: unzip: command not found

[ERROR] in line 31: exit code 0: while executing command unzip -q -d "/opt/teddycloud-${VERSION}" "teddycloud.amd64.release_v${VERSION}.zip"
root@proxmox:~#

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Just start the Script

### ❌ Paste the full error output (if available).

[ERROR] in line 31: exit code 0: while executing command unzip -q -d "/opt/teddycloud-${VERSION}" "teddycloud.amd64.release_v${VERSION}.zip"

**Comment by StefanX13** [comment]
@dsiebel

**Comment by MickLesk** [comment]
fixed.
