### ISSUE TITLE
Wallos not versioning up?

### ISSUE THREAD

**Issue by hgelpke** [community-scripts/ProxmoxVE#110]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the update script, Wallos shows an update to the latest version. When logged into the app, the version is behind. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![firefox_s2KxoczWbj](https://github.com/user-attachments/assets/a69d409c-b7f1-49df-a68e-dd1c76a31178)
![firefox_ZGYRX5RVXi](https://github.com/user-attachments/assets/c246f3a9-51f6-4953-98c6-f173674f72ef)

**Comment by MickLesk** [comment]
i think, i found the issue.

Can you enter "curl http://localhost/endpoints/db/migrate.php" in LXC Console, after this, "systemctl reload apache2"?

Is the version correct? Then i can build a little bugfix

**Comment by hgelpke** [comment]
> i think, i found the issue.
> 
> Can you enter "curl http://localhost/endpoints/db/migrate.php" in LXC Console, after this, "systemctl reload apache2"?
> 
> Is the version correct? Then i can build a little bugfix
> 
> @Aloe-recite can you test?

![image](https://github.com/user-attachments/assets/9b56321c-2110-4118-a3aa-3172b4db3264)

**Comment by MickLesk** [comment]
Input is Missing. What Say the webui now? ^^

**Comment by hgelpke** [comment]
> Input is Missing. What Say the webui now? ^^

Same as before. Version in terminal doesn't match app

**Comment by MickLesk** [comment]
Done with the next Wallis Update

https://github.com/community-scripts/ProxmoxVE/pull/129
