### ISSUE TITLE
EMQX not updating?

### ISSUE THREAD

**Issue by Builder-DE-TH** [community-scripts/ProxmoxVE#1102]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

EMQX

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/emqx.sh)"

### 📝 Provide a clear and concise description of the issue.

Script says it has updated but EMQX GUI reports the old version. v5.8.3 instead of v5.8.4

Checked in fresh browser and it's not a cache issue.

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

type update

### ❌ Paste the full error output (if available).

no error messages

**Comment by MickLesk** [comment]
Reboot?

**Comment by Builder-DE-TH** [comment]
Yup. Twice.

**Comment by MickLesk** [comment]
Then the new Version is not pushed to Debian repo.
