### ISSUE TITLE
Stirling pdf fail to install with defaults

### ISSUE THREAD

**Issue by martincaddick** [community-scripts/ProxmoxVE#111]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

[ERROR] in line 56: exit code 0: while executing command wget -qO /etc/apt/trusted.gpg.d/zulu-repo.asc "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xB1998361219BD9C9"

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 113
Using Hostname: stirling-pdf
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Stirling-PDF LXC using the above default settings
 ✓ Using nfs for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.2.132 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 4.237.22.38
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed LibreOffice Components
 ✓ Installed Python Dependencies
 - Installing Azul Zulu   
[ERROR] in line 56: exit code 0: while executing command wget -qO /etc/apt/trusted.gpg.d/zulu-repo.asc "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xB1998361219BD9C9"

### Please provide detailed steps to reproduce the issue.

Installed using defaults

**Comment by havardthom** [comment]
Script works fine here.

🌐 It seems that you're facing a network problem, probably linked to DNS.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by martincaddick** [comment]
Really weird, everything else worked ok up until this point. I am running tailscale on the host. When I change to advanced settings, select all of the defaults and then change the DNS server to 192.168.2.1 (so not using tailscale) then it works perfectly. Cheers

**Comment by Leuconoe** [comment]
@martincaddick use this
tailscale up --accept-dns=false

https://nelsonslog.wordpress.com/2024/01/02/tailscale-magic-dns-proxmox-and-lxc/
