### ISSUE TITLE
Nginx Proxy Manager LXC update  error.

### ISSUE THREAD

**Issue by gladiatormax** [community-scripts/ProxmoxVE#1111]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Nginx Proxy Manager LXC

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

When i run the update command, it gives me this error,
✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.12.2
 \ Setting up Enviroment   
[ERROR] in line 137: exit code 0: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null

Anny idea?

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

update command

### ❌ Paste the full error output (if available).

[ERROR] in line 137: exit code 0: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null

**Comment by havardthom** [comment]
https://github.com/community-scripts/ProxmoxVE/discussions/555
