### ISSUE TITLE
NGINX Proxy Manager update error

### ISSUE THREAD

**Issue by Aloe-recite** [community-scripts/ProxmoxVE#1117]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Nginx Proxy Manager

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

Running "update" commands returns an error and an unusable LXC (had to restore from backup):

✔️  Stopped Services
✔️  Cleaned Old Files
✔️  Downloaded NPM v2.12.2
 ⠦ Setting up Enviroment 
[ERROR] in line 109: exit code 0: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Run "update" command to update from v2.12.1 to 2.12.2

### ❌ Paste the full error output (if available).

[ERROR] in line 109: exit code 0: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null

**Comment by MickLesk** [comment]
Python Error. See discussion

**Comment by gladiatormax** [comment]
Thx for the hint, its working now.
