### ISSUE TITLE
Netbox Install Script shows non-accessible URL on successful installation

### ISSUE THREAD

**Issue by GTRasH** [community-scripts/ProxmoxVE#1120]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

NetBox

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/netbox.sh)"

### 📝 Provide a clear and concise description of the issue.

NetBox Setup finishes with the following statement

🚀  NetBox setup has been successfully initialized!
  💡   Access it using the following URL:
    🌐  http://192.168.178.127

This is technically accessible, but shows only the default apache2 page, because it uses http so port 80 instead of https for port 443

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

install netbox via script

### ❌ Paste the full error output (if available).

🚀  NetBox setup has been successfully initialized!
  💡   Access it using the following URL:
    🌐  http://192.168.178.127

### 🖼️ Additional context (optional).

![image](https://github.com/user-attachments/assets/334345b6-3306-498e-bd5d-8852e09eb9a1)
![image](https://github.com/user-attachments/assets/5bf61d33-0559-405e-b6d7-033e35926628)

**Comment by MickLesk** [comment]
can you try https? its merged now

**Comment by GTRasH** [comment]
> can you try https? its merged now

works as expected now.
