### ISSUE TITLE
Alpine-Nextcloud LXC script broken, asks for unknown login on first boot

### ISSUE THREAD

**Issue by TheGinGear** [community-scripts/ProxmoxVE#1125]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Nextcloud LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/alpine-nextcloud.sh)"

### 📝 Provide a clear and concise description of the issue.

When setting up an alpine-linux based LXC for nextcloud using the script from the page [here](https://community-scripts.github.io/ProxmoxVE/scripts?id=nextcloudpi), you are immediately thrown into a login page with no further info. 
![image](https://github.com/user-attachments/assets/24cd1b78-6378-4567-bedd-aa2fa73f7278)

Doing some research, you are apparently supposed to throw the script once again into the lxc itself, but while that beigns some sort of process, it crashes at the second step. See below.

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Alpine

### 🔄 Steps to reproduce the issue.

Follow the normal install process.
![image](https://github.com/user-attachments/assets/923c86bb-ff94-4b77-96c2-9f5cd970ad1b)
![image](https://github.com/user-attachments/assets/58f28902-a865-41b5-ae1d-3aa182d0c420)
![image](https://github.com/user-attachments/assets/f10539aa-9626-4a39-84a1-5395472f830b)
![image](https://github.com/user-attachments/assets/5cc19930-c47c-4f40-9c11-c7c4c514aab6)

### ❌ Paste the full error output (if available).

`  💡  Figlet for ASCII-Header not found. Installing... 
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

[ERROR] in line 209: exit code 0: while executing command tar -xf "$temp_dir/figlet.tar.xz" -C /tmp/figlet --strip-components=1`

**Comment by MickLesk** [comment]
Can you try again in the next 10+ Min?

**Comment by IcHiAT** [comment]
I did try it, no change so far. 
Asks for Username and Password on first boot

**Comment by IcHiAT** [comment]
Ah! When I put the same command again (2nd time in the container), it works!
Also the color of the window is not blue, it's black. No idea if that helps.
![image](https://github.com/user-attachments/assets/593c2052-bf78-4bbe-86c2-7fefda1294a1)
![image](https://github.com/user-attachments/assets/1f11bf79-8456-4a13-8c98-0798fea2df28)

**Comment by MickLesk** [comment]
That's another mistake and doesn't belong here. The original issue has therefore been resolved.

**Comment by IcHiAT** [comment]
I guess there are two problems on the same topic or it is a consequential error from the first one? 
He has error 209 I had 47.
I had to put in the LXC the shell command 2 times, then it works.
So the error is exactly what the topic says
