### ISSUE TITLE
Homarr update script merge error

### ISSUE THREAD

**Issue by Steefzar** [community-scripts/ProxmoxVE#119]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Getting this when I am using the update script for the Homarr LXC:

**/Updating 68ff84c8..95c126f2   
error: Your local changes to the following files would be overwritten by merge:
        data/configs/default.json
Please commit your changes or stash them before you merge.
Aborting
Already up to date.**

New to committing so forgive me if I am not doing it correctly.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Skärmbild_20241107_155835](https://github.com/user-attachments/assets/2e57a5bd-8a9a-4337-8341-93f309db45eb)

### Please provide detailed steps to reproduce the issue.

Run update script inside the Homarr LXC:
 bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/homarr.sh)"

**Comment by MickLesk** [comment]
And what do you have updated in this File? 😅

**Comment by Steefzar** [comment]
> And what do you have updated in this File? 😅

It seems to be all of my settings to Homarr, but how do I proceed? I can backup the file ofc but I want to update Homarr too
Forgive me if I sound stupid but it is not really clear to me what to do haha

**Comment by MickLesk** [comment]
Done with the next homarr Update you run.


https://github.com/community-scripts/ProxmoxVE/pull/124

**Comment by Narkowii** [comment]
`   __  __
   / / / /___  ____ ___  ____ ___________
  / /_/ / __ \/ __ `__ \/ __ `/ ___/ ___/
 / __  / /_/ / / / / / / /_/ / /  / /
/_/ /_/\____/_/ /_/ /_/\__,_/_/  /_/

Loading...
bash: -c: line 58: syntax error in conditional expression: unexpected token `;'
root@homarr:~# `

**Comment by MickLesk** [comment]
> `   __  __
>    / / / /___  ____ ___  ____ ___________
>   / /_/ / __ \/ __ `__ \/ __ `/ ___/ ___/
>  / __  / /_/ / / / / / / /_/ / /  / /
> /_/ /_/\____/_/ /_/ /_/\__,_/_/  /_/
> 
> Loading...
> bash: -c: line 58: syntax error in conditional expression: unexpected token `;'
> root@homarr:~# `

Update or create?

**Comment by Narkowii** [comment]
oh sorry... for update with your modified script

**Comment by MickLesk** [comment]
Check again

**Comment by Narkowii** [comment]
`✓ Services Stopped
 -mv: cannot move '/opt/data' to '/opt/homarr/data': Directory not empty

[ERROR] in line 77: exit code 0: while executing command mv /opt/data /opt/homarr/`

**Comment by MickLesk** [comment]
Wtf, I wonder why it works for me and not for you. Okay, then I have to add a workaround for general.
