### ISSUE TITLE
Password in File Browser

### ISSUE THREAD

**Issue by kuchar91** [community-scripts/ProxmoxVE#142]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello. When installing File Browser I noticed that there is an error on the page regarding the first password after installing the application. On the page it says "changeme" and in the script itself "helper-scripts.com"

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="608" alt="Zrzut ekranu 2024-11-8 o 23 06 55" src="https://github.com/user-attachments/assets/3056a186-1c12-4c4e-9985-d50d414edcbe">

### Please provide detailed steps to reproduce the issue.

study the script.

**Comment by newzealandpaul** [comment]
Thank you, this has been fixed.
