### ISSUE TITLE
homeassistant-core-install.sh needs to tackle issues with python3.12 on debian

### ISSUE THREAD

**Issue by real-amie42** [community-scripts/ProxmoxVE#153]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When installing homeassistant into a debian LXC Container, the homeassistant-core-install.sh script will fail in this way:

`Reading package lists... Doneatience)   
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python3-pip' instead of 'pip'
 |E: Unable to locate package python3.12-dev
E: Couldn't find any package by glob 'python3.12-dev'
E: Couldn't find any package by regex 'python3.12-dev'

[ERROR] in line 17: exit code 0: while executing command $STD apt-get install -y git curl sudo mc bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libturbojpeg0-dev ffmpeg liblapack3 liblapack-dev dbus-broker libpcap-dev libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev libavfilter-dev libmariadb-dev-compat libatlas-base-dev pip python3.12-dev`

This is due to the fact that homeassistant ditched the support of python versions <3.12. However debian bookworm only provides python 3.11. 
@pascallj provides a backport of python3.12 specifically to tackle this particular issue within homeassistant. ( #[see](https://github.com/pascallj/python3.12-backport)

I would suggest to implement that within the homeassistant-core-install.sh script. Alternatively the process could provide a hook in the advanced settings to open a shell within the running container prior to the call of homeassistant-core-install.sh. 

Cheers 
Amie

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by havardthom** [comment]
Related issue: https://github.com/tteck/Proxmox/issues/3892

Adding custom python backports from unknown authors not something we want in our scripts (feel free to use it yourself manually though). You should use the default distribution which is clearly stated in documentation. 
![image](https://github.com/user-attachments/assets/d99c5292-3b28-47d6-bbe3-d06d8c6feec5)
![image](https://github.com/user-attachments/assets/1816ef76-db26-4c3d-bbcc-def5f700aa4a)
