### ISSUE TITLE
Rate limit exceeded when searching for scripts

### ISSUE THREAD

**Issue by remisharrock** [community-scripts/ProxmoxVE#155]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

i get this message when searching for scripts: 
Rate limit exceeded
Please wait a few minutes before retrying your request.

URL:
community-scripts.github.io

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

https://community-scripts.github.io/ProxmoxVE/scripts?id=changedetection 

### Please provide detailed steps to reproduce the issue.

search with the search box, and very quickly you have this error

**Comment by havardthom** [comment]
Reopening this since it looks to be related to image fetching
![image](https://github.com/user-attachments/assets/4f784990-842d-4ae7-9abf-acef3b408be1)
