### ISSUE TITLE
Cockpit File Sharing

### ISSUE THREAD

**Issue by badi713** [community-scripts/ProxmoxVE#157]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installed cockpit LXC and typed update in console to install [Cockpit File Sharing](https://github.com/45Drives/cockpit-file-sharing/releases/tag/v4.2.5) but i get this error: [ERROR] in line 84: exit code 0: while executing command wget -q https://github.com/45Drives/cockpit-file-sharing/releases/download/v${LATEST}/cockpit-file-sharing_${LATEST}-1focal_all.deb

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by havardthom** [comment]
Looks like 45Drives likes to use their own versioning scheme and not have the same version between github tag and filename in release https://github.com/45Drives/cockpit-file-sharing/releases
