### ISSUE TITLE
WireGuard showing inaccurate instructions.

### ISSUE THREAD

**Issue by tteck** [community-scripts/ProxmoxVE#16]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Viewing the instructions at https://community-scripts.github.io/Proxmox/scripts?id=WireGuard is different than https://tteck.github.io/Proxmox/#wireguard-lxc I'm sure they are others with incorrect info.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by BramSuurdje** [comment]
Its fixed. I agree, there are probably more that are wrong. but when the new system is in place i will go over every script to make sure it still aligns with your site.

**Comment by tteck** [comment]
> Its fixed.

@BramSuurdje the instructions are still wrong.

**Comment by BramSuurdje** [comment]
To my understanding they are in line now, if not please clarify on what is different.

**Comment by tteck** [comment]
You indeed get them fixed this time. Good job.
