### ISSUE TITLE
Frontend] Missing information on the new Homepage

### ISSUE THREAD

**Issue by MickLesk** [community-scripts/ProxmoxVE#185]
### Discussed in https://github.com/community-scripts/ProxmoxVE/discussions/181

<div type='discussions-op-text'>

<sup>Originally posted by **marvin78** November 11, 2024</sup>
Some scripts don't show some important information. Examples:

Vaulwarden: Information about the ressource settings for an update are missing. 
MariaDB: original has a link to a document for post script processing

There might be more. </div>

**Comment by derkahless** [comment]
I think "Keycloak" had some Infos as well (How to create the temp admin user)
