### ISSUE TITLE
Paperless-ngx update to v2.13.5 fails at line 95

### ISSUE THREAD

**Issue by frankanderson** [community-scripts/ProxmoxVE#187]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Ghostscript updated successfully the first time I ran the script, but the Paperless update failed. I ran the script again and got the same error.

```
cat: /opt/Paperless-ngx_version.txt: No such file or directory
 ✓ Stopped all Paperless-ngx Services
 | Updating to v2.13.5   
[ERROR] in line 95: exit code 0: while executing command /usr/bin/python3 manage.py migrate &> /dev/null
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

In LXC console, run:
`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/paperless-ngx.sh)"`

**Comment by MickLesk** [comment]
https://github.com/tteck/Proxmox/issues/2925
https://github.com/tteck/Proxmox/discussions/3864
