### ISSUE TITLE
Update jellyfin - Breaking Change

### ISSUE THREAD

**Issue by MickLesk** [community-scripts/ProxmoxVE#190]
### Discussed in https://github.com/community-scripts/ProxmoxVE/discussions/169

<div type='discussions-op-text'>

<sup>Originally posted by **ashoktvm** November 11, 2024</sup>
I tried using apt update and upgrade and also just updating inside the console, but it never updated the server. What can I do?</div>

apt-get --with-new-pkgs upgrade jellyfin jellyfin-server is needed in jellyfin.sh

**Comment by newzealandpaul** [comment]
Yes this is worth adding
