### ISSUE TITLE
AdGuard Home LXC - Update Error

### ISSUE THREAD

**Issue by Luschwe** [community-scripts/ProxmoxVE#198]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Update within AdGuard Shell command
![IMG_2578](https://github.com/user-attachments/assets/d46b3a4d-98a7-4195-97b2-4f15f211a726)

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/adguard.sh)"

leads to

[ERROR] in line 69: exit code 0: while executing command tar -xvf AdGuardHome_linux_amd64.tar.gz &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MickLesk** [comment]
I'm just wondering why there is an update script at all. Can't you do all that via the UI? 

Actually, we should remove that.

**Comment by Luschwe** [comment]
Yes you are right. It works via UI. So update script not needed.

**Comment by MickLesk** [comment]
Fine, i remove it in the november milestone. 👍

**Comment by synchromatik** [comment]
The latest update (AdGuard Home v0.107.55 is now available!) fails from UI thou :/ can I provide some logs if there are any? (could use pointers)
![image](https://github.com/user-attachments/assets/ef1bfa7a-85df-42c4-80e6-b75a21e31e21)

**Comment by synchromatik** [comment]
After investigating a bit more, i guess the default 2GB is not enough for a few months/updates of use. Resizing the default 2GB to 3GB fixed the update from UI bug. 

Just so you know, something to consider.

**Comment by flexdinesh** [comment]
UI update failed for me too. @synchromatik suggestion to upgrade the storage from 2GB to 3GB fixed the issue for me.
