### ISSUE TITLE
The fork seems to have stopped the website

### ISSUE THREAD

**Issue by simonmcnair** [community-scripts/ProxmoxVE#2]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The website with the links to the scripts has disappeared

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by simonmcnair** [comment]
https://helper-scripts.com/ no longer works.

**Comment by simonmcnair** [comment]
in case anyone was wondering I think the command generally was (an example).  In the meantime you'll jsut need to find the appropriate script

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/ubuntu.sh)"`

**Comment by simonmcnair** [comment]
aaah, it seems to work by going here:  https://tteck.github.io/Proxmox/

**Comment by community-scripts** [comment]
Wait a little bit ;) we need to declare Something

**Comment by tteck** [comment]
Moved redirect back to https://tteck.github.io/Proxmox/ until things are a little more finalized 😉
