### ISSUE TITLE
ollama script not on the website

### ISSUE THREAD

**Issue by newzealandpaul** [community-scripts/ProxmoxVE#202]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Converting this [discussion](https://github.com/community-scripts/ProxmoxVE/discussions/201) into a issue

> it's available to start / install from :
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/ollama.sh)"
but missing in the website :

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

No JSON exists.

### Please provide detailed steps to reproduce the issue.

Search the website

**Comment by newzealandpaul** [comment]
The team decided not to merge my pull request to fix this, so I am closing the issue.

**Comment by bao3** [comment]
Perhaps , change OS from Ubuntu to Debian would work. I noted many of the script have been changed.
