### ISSUE TITLE
Zwave JS UI updated it's requirements to include ENV variables. 

### ISSUE THREAD

**Issue by zmcnaney** [community-scripts/ProxmoxVE#207]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

ZWave JS upgraded to version 14 of the node-zwave-js.   When doing so, they changed the requirements and now require enviornment variables to be set and don't default.   This change occured today with the update to tag 9.21.1.   With the variables 

The variables that must be set are ZWAVEJS_EXTERNAL_CONFIG and STORE_DIR.    If those are not configured, all the devices lose their manufacturer, product, and product code in the UI.  ![image](https://github.com/user-attachments/assets/aa074a4b-d67a-4c7e-92f5-5b946cbcc695)

If you update the service entry being created in https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/zwave-js-ui.sh to include the variables - everything works as expected. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Old
```
[Unit]
  Description=zwave-js-ui
  Wants=network-online.target
  After=network-online.target
  [Service]
  User=root
  WorkingDirectory=/opt/zwave-js-ui
  ExecStart=/opt/zwave-js-ui/zwave-js-ui-linux
  [Install]
  WantedBy=multi-user.target
```
New
```
[Unit]
  Description=zwave-js-ui
  Wants=network-online.target
  After=network-online.target
  [Service]
  Environment="ZWAVEJS_EXTERNAL_CONFIG=/opt/zwave-js-ui/.config-db"
  Environment="STORE_DIR=/opt/zwave-js-ui/store"
  User=root
  WorkingDirectory=/opt/zwave-js-ui
  ExecStart=/opt/zwave-js-ui/zwave-js-ui-linux
  [Install]
  WantedBy=multi-user.target
  ```

### Please provide detailed steps to reproduce the issue.

Update ZWAVE JS UI using the update script to version 9.21.0 or higher.

**Comment by newzealandpaul** [comment]
Thanks for the detailed issue with a fix.

I don't have zwave devices so I cannot test this, can you try this script:

bash -c "$(wget -qLO - https://raw.githubusercontent.com/newzealandpaul/ProxmoxVE/refs/heads/newzealandpaul-zwave1/ct/zwave-js-ui.sh)"

And let me know if that works. This will create a new container just FYI.

**Comment by zmcnaney** [comment]
So, your script didn't work, but I believe that's due to it referencing a direct link to the build.func file, not the raw.githubusercontent.com link. 

Your script references: https://github.com/newzealandpaul/ProxmoxVE/blob/newzealandpaul-zwave1/misc/build.func

It should reference: https://raw.githubusercontent.com/newzealandpaul/ProxmoxVE/refs/heads/newzealandpaul-zwave1/misc/build.func since you're trying to run it?  

From what I can tell there are a number of changes in the .func file, but the update_script() function matches what I changed locally to get it working. 

When I attemtped to run it, I got an odd error:


```root@pve1:~# bash -c "$(wget -qLO - https://raw.githubusercontent.com/newzealandpaul/ProxmoxVE/refs/heads/newzealandpaul-zwave1/ct/zwave-js-ui.sh)"```


```
 _____                                  _______    __  ______
/__  /_      ______ __   _____         / / ___/   / / / /  _/
  / /| | /| / / __ `/ | / / _ \   __  / /\__ \   / / / // /  
 / /_| |/ |/ / /_/ /| |/ /  __/  / /_/ /___/ /  / /_/ // /   
/____/__/|__/\__,_/ |___/\___/   \____//____/   \____/___/   
                                                             
Loading...
bash: line 27: variables: command not found
bash: line 28: color: command not found
bash: line 29: catch_errors: command not found
bash: line 96: start: command not found
bash: line 97: build_container: command not found
bash: line 98: description: command not found
Zwave-JS-UI should be reachable by going to the following URL.
         http://:8091 
```

**Comment by newzealandpaul** [comment]
Sorry about that, I will take another look at it. Thanks for trying it.

**Comment by MickLesk** [comment]
I'm not sure what else might be missing here or if it affects us at all, but the file “/opt/zwave-js-ui/.config-db” does not exist. 
There are also 2-3 other WARN's here. Unfortunately I don't have Zwave to test anything. 


<img width="669" alt="image" src="https://github.com/user-attachments/assets/ac16987a-b230-41fb-8fe4-ed0725979c41">

**Comment by zmcnaney** [comment]
“/opt/zwave-js-ui/.config-db" doesn't need to exist.   It's created by the application upon boot.   It's a new file. 

The other warnings are because there is no devices yet.   Otherwise that doesn't look like problematic warnings.    Backups aren't enabled by default, I believe they have to be enabled later.

**Comment by MickLesk** [comment]
Would be great if you can test this, as I already said I don't have a ZWave device and could only fix it blindly :smile:

**Comment by zmcnaney** [comment]
Sorry, I have been out for the weekend.  I can test this later tonight! (Eastern Hours)

**Comment by zmcnaney** [comment]
@MickLesk Works just fine.   Thanks for the fix and good to know the preferred method in the future.

**Comment by MickLesk** [comment]
Okay, then i create an PR with the fix asap :smile:
