### ISSUE TITLE
improve clarity of script naming

### ISSUE THREAD

**Issue by thigg** [community-scripts/ProxmoxVE#210]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

i came to the site from hn, understanding that the site is about automating tasks on proxmox.
One of the first scripts I saw was the docker lxc script. The description of the script explains what docket is, which let me wonder if this is about running docker somehow nativley on proxmox. This is probably my fault by not reading the site properly, but I have two suggestions in mind:

Make Lxc stand out as a label that imakes clear its not part of the script title.

Make somehow clear that the script installs e.g. docker, because the only thing that is shown is a description of what docker is.

### Please provide a description of the expected behavior.

As written above.

**Comment by Mellowlynx** [comment]
Thanks for your feedback, and I get your point.
Currently, there are labels on the site, and a view other mentions:
![afbeelding](https://github.com/user-attachments/assets/7a8ce6b6-bca2-403a-be93-3453fddff78f)

But I do think it would help, if the GitHub introduction was also added to the site, that would make it clear what you are looking at for newcomers.
![afbeelding](https://github.com/user-attachments/assets/de26e273-bca8-41bd-af67-6f8f3c542c39)
