### ISSUE TITLE
Jellyseerr breaking change

### ISSUE THREAD

**Issue by blunweon** [community-scripts/ProxmoxVE#216]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

New Jellyseerr install v2.1.0 requires for deleting of certain directories before building.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

I tried the default "update" command and it did not manage to build the binary properly. Hence, I followed the steps given on the official discord announcement channel and their [github release page](https://github.com/Fallenbagel/jellyseerr/releases/tag/v2.1.0) to delete the directories before building.

Steps I did to update to the newest version:

```
cd /opt/jellyseerr
git pull
rm -r dist
rm -r .next 
rm -r node_modules
CYPRESS_INSTALL_BINARY=0 pnpm install --frozen-lockfile
pnpm build
systemctl restart jellyseerr
```

**Comment by MickLesk** [comment]
sorry i mixed up the issue with jellyfin :smile: now it should fit. Please give feedback
