### ISSUE TITLE
5GB of RAM is no more enough to build Vaultwarden

### ISSUE THREAD

**Issue by maciejla** [community-scripts/ProxmoxVE#236]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi, I was just updating Vaultwarden and unfortunately the recommended (and default in `vaultwarden.sh`) 5120MB of RAM is no longer enough to build it (process gets terminated by OOM killer). I increased it to 6144MB, it compiled just fine with the highest RAM usage being 5.07GB

It would probably make sense to increase the size (both the default while installing, and the one that gets displayed as a recommendation when updating). Something like 5.5G (5632MB) would probably work, but I guess 6G makes more sense from both a readability and future-proofing standpoint

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by japlic** [comment]
Hey its gonna be a while the owner of proxmox helper scripts passed away

**Comment by maciejla** [comment]
Oh, didn't know about that... My sincere condolences to family, friends and everyone else involved. This issue isn't that important, let's tackle it after you get things sorted out

**Comment by MickLesk** [comment]
> Hey its gonna be a while the owner of proxmox helper scripts passed away

Why should it take a while? We fix bugs every day. Even without tteck (RIP), that's what the new “community-scripts” org is for :-)

**Comment by MickLesk** [comment]
I have included a storage check, which will be correctly integrated for the upcoming LXCs. 

We will adjust the Vaultwarden CT afterwards (after it has been noted).

https://github.com/community-scripts/ProxmoxVE/pull/249
