### ISSUE TITLE
Wireguard LXC Freezing up | Unable to use until restart

### ISSUE THREAD

**Issue by qvipin** [community-scripts/ProxmoxVE#241]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When using the Wireguard LXC, I have noticed the LXC tend to freeze up when I attempt to create a tunnel and remains frozen until the container is restarted. This is evident even after attempting multiple times to ensure it wasn't a fluke. I also tested installing WGDashboard on a VM with better settings (3 Gigs of ram and 1 core) and I don't seem to notice any freezing.

Also RIP tteckster 🕊️

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. Install the Wireguard LXC from the website with all default settings
2. Upon accessing the Dashboard page, attempt to create a tunnel. 
3. After creating a tunnel observe the whole dashboard freezing and unable to be reloaded until restart.
4.  If the tunnel somehow works (worked once), attempt to turn on the tunnel with a default peer or any peer and observe its behavior.

**Comment by MickLesk** [comment]
I cannot understand the error.

1. freshly deployed WireGuard LXC (default settings)
2. login clicked through, without MFA
3. pressed “+” in “Home” and entered data => Save
4. activated
5. everything runs normally

<img width="1692" alt="image" src="https://github.com/user-attachments/assets/3bcfda58-db07-4e97-84bd-183f9e588076">
