### ISSUE TITLE
Vikunja install error

### ISSUE THREAD

**Issue by ranebrown** [community-scripts/ProxmoxVE#248]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Vikunja install fails with below error. No additional information if running advanced mode with verbose logging.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
Creating a Vikunja LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 \unable to create CT 109 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - --zstd --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/109/rootfs --skip-old-files --anchored --exclude './dev/*'' failed: exit code 2
 |bash: line 182: exit: A problem occured while trying to create container.: numeric argument required
```

### Please provide detailed steps to reproduce the issue.

Attempt default install by pasting `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/vikunja.sh)"` into shell.

**Comment by MickLesk** [comment]
Thats not an vikunja issue, the script failed, because there are some problems on your proxmox node with the container id or something else. 

Reboot your Proxmox and test again

**Comment by ranebrown** [comment]
Rebooting didn't help but I am seeing the same error trying a different script. Any advice on how to debug this?

**Comment by MickLesk** [comment]
Which version of Proxmox VE? With which user do you run the script? Do you run the script in Main-Node? 

nano /etc/subuid
nano /etc/subgid

Whats the output?

**Comment by ranebrown** [comment]
Got it fixed. There was a leftover folder in `/var/lib/lxc` with incorrect permissions that matched the new id I was trying to use. Deleting that folder and allowing it to be recreated worked. Thanks for the help.
