### ISSUE TITLE
NZBGet URL wrong on website

### ISSUE THREAD

**Issue by timmerk** [community-scripts/ProxmoxVE#253]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The nzbget page on the website points to nzbget.net. This is the old and discontinued original project. It has been forked and maintained since then at nzbget.com. The install script is correct, but the website URL still points to the old one.

### Please provide a description of the expected behavior.

Website button points to nzbget.com

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

n/a

### Please provide detailed steps to reproduce the issue.

Go to https://community-scripts.github.io/ProxmoxVE/scripts?id=nzbget and click on the "Website" button

**Comment by newzealandpaul** [comment]
Thanks @timmerk, a pull request that fixes this has been submitted.
