### ISSUE TITLE
Portainer UI not accessible

### ISSUE THREAD

**Issue by Ehsan-U** [community-scripts/ProxmoxVE#278]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Docker LXC
While running this script, it ask for portainer installation but not correctly expose the UI port which is 9000. 
UI is not accessible at 8000.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/5c1299ea-c8e9-41b8-90c0-793df7ed4868)

### Please provide detailed steps to reproduce the issue.

just run the script and accept to install portainer.

**Comment by MickLesk** [comment]
The UI can be reached at 9443.

**Comment by habitoti** [comment]
Though this issue is already closed: it would be nice if this would be printed into the console at the end of the installation. 9000 is usually the GUI port, so it really takes some additional forensics to find out it's actually 9443 here...

**Comment by tremor021** [comment]
![Image](https://github.com/user-attachments/assets/9f47374a-02d3-4de5-a3d4-2f8522d40636)

Not really sure where you got that default portainer port is 9000
