### ISSUE TITLE
LXC Cleaner script starts LXC's even if they are not selected

### ISSUE THREAD

**Issue by Scorpoon** [community-scripts/ProxmoxVE#283]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Running `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/clean-lxcs.sh)"` in the proxmox shell gives you the option to select which lxc should be cleaned.
In my case there are two lxc which aren't started and shouldn't be cleaned, so I didn't select them but the script treats them as if they are selected.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MekongHigh** [comment]
> Running `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/clean-lxcs.sh)"` in the proxmox shell gives you the option to **select which lxc should be cleaned.** In my case there are two lxc which aren't started and shouldn't be cleaned, **so I didn't select them** but the script treats them as if they are selected.

Select containers to skip from cleaning:
