### ISSUE TITLE
Recylarr UI Not accessible

### ISSUE THREAD

**Issue by piyush97** [community-scripts/ProxmoxVE#288]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Recylarr script doesn't provide the URL and port to open the UI. When I tried to access port 1000, as stated in the documentation, it was inaccessible.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MickLesk** [comment]
Does it have an UI? My last knowledge is that there is no UI but it is a pure command line application?

**Comment by Mellowlynx** [comment]
> Does it have an UI? My last knowledge is that there is no UI but it is a pure command line application?

Yep, Command line only
![image](https://github.com/user-attachments/assets/03d00421-26f3-4445-9b4e-843403de6c4e)
