### ISSUE TITLE
nginx proxy manager missing required certbot-dns packages.

### ISSUE THREAD

**Issue by bvierra** [community-scripts/ProxmoxVE#296]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

During installation the only certbot dns addon you install is `python3-certbot-dns-cloudflare` per 
[nginxproxymanager-install.sh](https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/nginxproxymanager-install.sh) line 41.

This means that trying to create a dns challenge verified certificate, if you are using cloudflare for your dns host you are fine. If not you get a message in nginx proxy manager that the option does not exist.

You should really remove line 41 (dont use the pkg manager to install the certbot plugin for cloudflare) and instead use the included `/app/scripts/install-certbot-plugins` which will install ALL of the plugins (there is like 100 of em).

If you need need any more information or a PR for this let me know

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Install nginx proxy manager, then login to the web interface and attempt to create a lets encrypt dns verified cert with the dns provider being namecheap. It will give an error.

**Comment by Mellowlynx** [comment]
As it stated on the website:
![image](https://github.com/user-attachments/assets/22ba3f20-7563-4ce5-810b-916ff9b6e4a8)
The plugin for Cloudflare was included because it's the most used within the community.
If you need something else, you can install it.

**Comment by bvierra** [comment]
> As it stated on the website: The plugin for Cloudflare was included because it's the most used within the community. If you need something else, you can install it.

That is fair, but maybe something on how this would be done would be nice. I only looked into this because someone had asked in a discord if anyone knew why they were getting the error. They gave me the command they ran and I traced it back through git and never looked at the site.

**Comment by bvierra** [comment]
> The next line is `$STD pip3 install certbot-dns-multi`, which installs https://github.com/alexzorin/certbot-dns-multi, which supports A LOT of dns providers, for instructions on how to use it, go to https://go-acme.github.io/lego/dns/

Yea I missed that one, but is there a reason why there seems to be pushback against just running the single command that is given by the author that installs the plugins that he also has in the GUI? Seems like a good way of making sure it just works.

**Comment by burgerga** [comment]
Yeah agree they this is not the most straightforward. I was reporting another issue, and saw this one by chance, and since I remembered struggling with this as well I thought I'd chime in. Perhaps including the above links for dns-multi on the website or as a post-install message would already help a lot of people.

**Comment by newzealandpaul** [comment]
I think it would be better to update the documentation to mention the script @bvierra referred to. PR submitted.

**Comment by infinitytec** [comment]
Hmmm... I seem to be having this issue. Ran both scripts. Whenever I attempt to renew my certs from the web UI an "Internal Error" message appears.
