### ISSUE TITLE
Regression: Wallos update removes subscriptions/payment icons

### ISSUE THREAD

**Issue by burgerga** [community-scripts/ProxmoxVE#314]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Commit 1addb21e179c2e7920808f4f50c67940e098b343 was introduced to solve #129, but this causes the subscriptions icons to disappear. Uploaded images are stored in `/opt/wallos/images/uploads/` and should be conserved.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. Install Wallos
2. Add subscription with logo
3. Update Wallos
4. Logo is gone

**Comment by MickLesk** [comment]
What is an subscription Icon? Where is this Set?

Can you share an Screenshot? Then i can fix it tomorrow.

**Comment by burgerga** [comment]
You can add logos to your subscriptions and to your custom payment methods, so how it looked before:
<img width="900" alt="SCR-20241117-rkoz" src="https://github.com/user-attachments/assets/b5aa7c3d-3344-4fc6-bb99-66e7502385b4">
How it looks after the update:
<img width="955" alt="SCR-20241117-rimt" src="https://github.com/user-attachments/assets/23b0d121-898a-401f-9545-79be829e15b9">
(you can see that Google Pay is one of the built-in payment options since it still has an icon, the others I added manually)
