### ISSUE TITLE
Vaultwarden update

### ISSUE THREAD

**Issue by vdias** [community-scripts/ProxmoxVE#334]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

 | Updating VaultWarden to 1.32.5 (Patience)
[ERROR] in line 87: exit code 0: while executing command cargo build --features "sqlite,mysql,postgresql" --release &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Launch .sh script to update version.
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/vaultwarden.sh)"

**Comment by vdias** [comment]
Any update on this one?

**Comment by havardthom** [comment]
I am not able to recreate this issue, update worked fine here. Could this be related to https://github.com/community-scripts/ProxmoxVE/issues/236 ? Do you have enough resources allocated to the LXC? 4 CPU cores and 6GB RAM minimum. Do you have enough storage?

**Comment by vdias** [comment]
6 vCPU
7GB RAM
11.06 GiB used of 11.71 GiB

Disk could be the problem... but cannot understand how can vaultwarden use 11GiB...

**Comment by MickLesk** [comment]
> 6 vCPU
> 7GB RAM
> 11.06 GiB used of 11.71 GiB
> 
> Disk could be the problem... but cannot understand how can vaultwarden use 11GiB...
> 


Thats an Problem. 
Vaultwarden on GNU Systems use many storage, the most of this are from the Cargo Builds.

**Comment by havardthom** [comment]
Feel free to investigate the disk usage and report back if something is wrong

**Comment by vdias** [comment]
root@vaultwarden:~# du -h | sort -hr | head -n 30
7.7G    .
4.9G    ./.rustup/toolchains
4.9G    ./.rustup
1.9G    ./.cargo/registry
1.9G    ./.cargo
1.1G    ./.cargo/registry/src
936M    ./vaultwarden
922M    ./vaultwarden/target/release
922M    ./vaultwarden/target
854M    ./vaultwarden/target/release/deps
759M    ./.cargo/registry/src/index.crates.io-6f17d22bba15001f
617M    ./.cargo/registry/index
594M    ./.cargo/registry/index/github.com-1ecc6299db9ec823
576M    ./.cargo/registry/index/github.com-1ecc6299db9ec823/.git/objects/pack
576M    ./.cargo/registry/index/github.com-1ecc6299db9ec823/.git/objects
576M    ./.cargo/registry/index/github.com-1ecc6299db9ec823/.git
570M    ./.rustup/toolchains/1.72.0-x86_64-unknown-linux-gnu
525M    ./.rustup/toolchains/1.82.0-x86_64-unknown-linux-gnu
512M    ./.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu
506M    ./.rustup/toolchains/1.69.0-x86_64-unknown-linux-gnu
505M    ./.rustup/toolchains/1.75.0-x86_64-unknown-linux-gnu
487M    ./.rustup/toolchains/1.80.1-x86_64-unknown-linux-gnu
480M    ./.rustup/toolchains/1.79.0-x86_64-unknown-linux-gnu
479M    ./.rustup/toolchains/1.72.0-x86_64-unknown-linux-gnu/lib
471M    ./.rustup/toolchains/stable-x86_64-unknown-linux-gnu
471M    ./.rustup/toolchains/1.65.0-x86_64-unknown-linux-gnu
470M    ./.rustup/toolchains/1.77.0-x86_64-unknown-linux-gnu
458M    ./.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib
452M    ./.rustup/toolchains/1.69.0-x86_64-unknown-linux-gnu/lib
449M    ./.rustup/toolchains/1.82.0-x86_64-unknown-linux-gnu/lib

**Comment by vdias** [comment]
root@vaultwarden:~# rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.65.0-x86_64-unknown-linux-gnu
1.67.0-x86_64-unknown-linux-gnu
1.69.0-x86_64-unknown-linux-gnu
1.72.0-x86_64-unknown-linux-gnu
1.75.0-x86_64-unknown-linux-gnu
1.77.0-x86_64-unknown-linux-gnu
1.79.0-x86_64-unknown-linux-gnu
1.80.1-x86_64-unknown-linux-gnu
1.82.0-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.65.0 (897e37553 2022-11-02)



Could be a good idea to add a rust cleanup task...

**Comment by vdias** [comment]
Really prefer the LXC concept... but this problems do not affect docker...

**Comment by vdias** [comment]
Fixed, cleaning up rust toolchains. 
`rustup toolchain uninstall XXXXXXXXXXXXXXXXXXXXX`

```
root@vaultwarden:/# rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.82.0-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.82.0 (f6e511eec 2024-10-15)
```
