### ISSUE TITLE
Netbird script does not work on alpine containers

### ISSUE THREAD

**Issue by pippo73** [community-scripts/ProxmoxVE#335]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

it is not possibile to install netbird on a container alpine_linux-based

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
Installing NetBird...
bash: line 3: /usr/share/keyrings/netbird-archive-keyring.gpg: No such file or directory
wget: write error: Broken pipe
bash: line 4: /etc/apt/sources.list.d/netbird.list: No such file or directory
```

### Please provide detailed steps to reproduce the issue.

try to install a container based on alpine linux. 
then try to install netbird client on this container and you get the following error after the menu where you select where to install netbird
```

    _   __     __  ____  _          __
   / | / /__  / /_/ __ )(_)________/ /
  /  |/ / _ \/ __/ __  / / ___/ __  /
 / /|  /  __/ /_/ /_/ / / /  / /_/ /
/_/ |_/\___/\__/_____/_/_/   \__,_/

Installing NetBird...
bash: line 3: /usr/share/keyrings/netbird-archive-keyring.gpg: No such file or directory
wget: write error: Broken pipe
bash: line 4: /etc/apt/sources.list.d/netbird.list: No such file or directory
```

**Comment by MickLesk** [comment]
This is not a bug. Alpine uses a completely different logic. A completely new script must be built for this, if it is possible at all with alpine.

**Comment by pippo73** [comment]
well, you can call as you wish (bug or CR or whatever) but I think 2 things should be done:
1) modify the script in order to controll the os of the container (otherwise it simply crashes like now)
2) notify it on the web page. ;-)
this are just my 2 cents for the community:-)

**Comment by fuad00** [comment]
I see this error after selecting container

![CleanShot 2024-11-20 at 05 37 39](https://github.com/user-attachments/assets/62835ecd-ab85-4e7c-ae95-d6eabe2bc012)
