### ISSUE TITLE
Error Creating LXC Container with Nginx Proxy Manager Script / Any Script

### ISSUE THREAD

**Issue by tamenmd** [community-scripts/ProxmoxVE#340]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While attempting to create an LXC container for Nginx Proxy Manager using the provided script, the process fails during template extraction with the following error message:

`unable to create CT 104 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - --zstd --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/104/rootfs --skip-old-files --anchored --exclude './dev/*'' failed: exit code 1`

This error prevents the container from being created successfully.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Command used to run the script:
`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/nginxproxymanager.sh)"`

### Please provide detailed steps to reproduce the issue.

Execute the script with default settings

**Comment by tamenmd** [comment]
Thank you for your response!

- HDD Setup: The Proxmox main node is installed on an NVMe drive (`/dev/nvme0n1`), and I am using the `local-lvm` storage for creating containers. This is on the same physical drive as the Proxmox installation. Additionally, I have remote NFS shares mounted, but these are not being used for the container creation.

- Storage Permissions: Could you clarify which permissions might be causing the issue? The local storage directory and local-lvm storage seem accessible without issues. Here’s the output of ls -ld for the relevant directories:

`ls -ld /var/lib/vz /var/lib/vz/template /var/lib/vz/template/cache`
The output:
```
drwxr-xr-x 5 root root 4096 Nov 18 12:00 /var/lib/vz
drwxr-xr-x 3 root root 4096 Nov 18 12:00 /var/lib/vz/template
drwxr-xr-x 2 root root 4096 Nov 18 12:00 /var/lib/vz/template/cache
```

Do you suspect any specific permission settings, or should I check something else? Let me know if you need additional information!

**Comment by MickLesk** [comment]
1st: check your files:
ls -lh /var/lib/vz/template/cache/

=> optionally, delete the debian file or mv to FILENAME%_bak

2nd:
cat /etc/subuid
cat /etc/subgid
=> root:100000:65536

3th: Check / Set Permissions (Warning! try the 1st and 2nd first!)
chown -R root:root /var/lib/lxc/
chmod -R 755 /var/lib/lxc/

**Comment by tamenmd** [comment]
Thank you for the help! The issue has been resolved.

The problem was caused by missing entries in `/etc/subuid` and `/etc/subgid`. Running the following commands fixed it:
```
echo "root:100000:65536" >> /etc/subuid
echo "root:100000:65536" >> /etc/subgid
```
After adding these entries, I was able to successfully create the LXC container without errors. Thanks again for your help!
