### ISSUE TITLE
Jellyfin update failing

### ISSUE THREAD

**Issue by TheFlyingBanshee** [community-scripts/ProxmoxVE#341]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Jellyfin has recently updated the ffmpeg codec, however, the helper script still uses an older version. This causes updating to fail.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

**Comment by newzealandpaul** [comment]
I thought this issue was fixed

https://github.com/community-scripts/ProxmoxVE/issues/216

**Comment by newzealandpaul** [comment]
@TheFlyingBanshee please confirm you used the correct script from this repository. Otherwise will close this issue.
