### ISSUE TITLE
PostgreSQL LXC - can't authenticate via Adminer

### ISSUE THREAD

**Issue by chris400** [community-scripts/ProxmoxVE#343]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The default configuration requires to create a linux user along with the postgresql. To avoid this I had to update the pg_hba.conf changing the following line
`local   all             all                                     peer`
to
`local   all             all                                     md5`

See https://gist.github.com/AtulKsol/4470d377b448e56468baef85af7fd614

My suggestion would be to either update the deployment script or put a note on the script.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Deploy the container and try to access the db server via Adminer

**Comment by michelroegl-brunner** [comment]
I could reproduce the error i think, i´working on a fix.
