### ISSUE TITLE
Linkwarden can't find monolith

### ISSUE THREAD

**Issue by burgerga** [community-scripts/ProxmoxVE#366]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

On adding a link I get the following message in the logs (and no html file is produced):
```
Nov 19 14:02:08 linkwarden yarn[50029]: [1] /bin/sh: 1: monolith: not found
```

This is because https://github.com/community-scripts/ProxmoxVE/blob/fc75c6657b5163530aa956d5bbdeae50c0416966/install/linkwarden-install.sh#L42
adds to ~/.bashrc, but linkwarden uses `sh` to execute the monolith command.

`ln -s /root/.cargo/bin/monolith /usr/local/bin/monolith` solves it, unsure if there is a cleaner solution (adding stuff to sh profile files is confusing)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by burgerga** [comment]
Yes, works perfectly, thanks!

**Comment by newzealandpaul** [comment]
Glad to have helped :)
