### ISSUE TITLE
Proxmox VE Cron LXC Updater - Missing Example

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [community-scripts/ProxmoxVE#375]
### Please verify that you have read and understood the guidelines.

yes

### What type of issue is this?

Documentation

### A clear and concise description of the issue.

On the page Proxmox VE Cron LXC Updater it claims there is an example of how to add the CTID (to allow for excluding LXCs). But the example is missing currently. 

### Which browser are you using?

Edge

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/205b3a84-631a-4fe7-8690-4016c33c6d25)

I did ask about this in the discord chat, and was given the following as what the example was suposed to be. 
![image](https://github.com/user-attachments/assets/24cbc7a1-3f9a-495e-a409-b66e180037e0)

### Please provide detailed steps to reproduce the issue.

Go to https://community-scripts.github.io/ProxmoxVE/scripts?id=cron-update-lxcs

**Comment by newzealandpaul** [comment]
Thank you for noting that, having the note there will help users. I have submitted a fix.
