### ISSUE TITLE
Installing Prometheus with bash -c ‘$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/prometheus.sh)’ gives an error

### ISSUE THREAD

**Issue by Shallowhave** [community-scripts/ProxmoxVE#380]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Creating a Prometheus LXC using the above default settings
✓ Using local-btrfs for Template Storage.
✓ Using local-btrfs for Container Storage.
✓ Updated LXC Template List
✓ LXC Container 111 was successfully created.
✓ Started LXC Container
✓ Set up Container OS
✓ Network Connected: xxxx
✓ IPv4 Internet Connected
✗ IPv6 Internet Not Connected
✓ DNS Resolved github.com to xxxx
✓ Updated Container OS
✓ Installed Dependencies
/mv: cannot stat ‘consoles/’: No such file or directory
mv: cannot stat ‘console_libraries/’: No such file or directory

[ERROR] in line 30: exit code 0: while executing command mv consoles/ console_libraries/ /etc/prometheus/

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Creating a Prometheus LXC using the above default settings
✓ Using local-btrfs for Template Storage.
✓ Using local-btrfs for Container Storage.
✓ Updated LXC Template List
✓ LXC Container 111 was successfully created.
✓ Started LXC Container
✓ Set up Container OS
✓ Network Connected: xxxx
✓ IPv4 Internet Connected
✗ IPv6 Internet Not Connected
✓ DNS Resolved github.com to xxxx
✓ Updated Container OS
✓ Installed Dependencies
/mv: cannot stat ‘consoles/’: No such file or directory
mv: cannot stat ‘console_libraries/’: No such file or directory

[ERROR] in line 30: exit code 0: while executing command mv consoles/ console_libraries/ /etc/prometheus/

**Comment by MickLesk** [comment]
You are using the old repo, so there are no updates included.

You can find the new page with the new scripts at https://helper-scripts.com or in this GitHub.

With:
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/update-repo.sh)"
you can update existing LXC's that were installed from the tteck repo to the new repo.

**Comment by Shallowhave** [comment]
> You are using the old repo, so there are no updates included.
> 
> You can find the new page with the new scripts at https://helper-scripts.com or in this GitHub.
> 
> With: bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/update-repo.sh)" you can update existing LXC's that were installed from the tteck repo to the new repo.

thank you
