### ISSUE TITLE
RDTClient update breaks web front end

### ISSUE THREAD

**Issue by stefmatik** [community-scripts/ProxmoxVE#399]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While updating the RDTClient, previously had a version from tteck, using the update command in the LXC, it updates the RDTClient but breaks the front end presumably because of the wrong dotnet-sdk version.

Removing dotnet-sdk-8.0 and installing dotnet-sdk-9.0 fixed the problem. I found the solution [here](https://github.com/rogerfar/rdt-client/issues/611)

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

k

### Please provide detailed steps to reproduce the issue.

1. Coming from a previous version, using update command to update RDTClient
3. Reboot
4. Frontend broken

**Comment by MickLesk** [comment]
Done with next PR

**Comment by stefmatik** [comment]
Thank you, I'll close the issue

**Comment by jwmann** [comment]
I just ran the update and my front end is not working. See my comment in #413
