### ISSUE TITLE
VS Code Server: Can't Install on Proxmox

### ISSUE THREAD

**Issue by xyboox** [community-scripts/ProxmoxVE#41]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I get this error when trying to run the install script for VSCode Server: "Can't Install on Proxmox"
Proxmox 8.2.7 - latest updates

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Running this command in shell: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/code-server.sh)"

**Comment by MickLesk** [comment]
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/code-server.sh)"

=> Works fine for me.

You need to enter this in an existing LXC, not in the Proxmox Node.
If this failure like this:
 - Installing Dependencies...‼ ERROR 100@72 Unknown failure occured.

You have an problem with apt-get update or dpkg-


Here an example at my test lxc: 
 
This will Install Code Server on cloudflared. Proceed(y/n)?y
 ✓ Installed Dependencies
 ✓ Installed Code-Server v4.93.1 on cloudflared
Code Server should be reachable by going to the following URL.
         http://192.168.0.40:8680

**Comment by xyboox** [comment]
oh... I feel stupid... just saw it: "Execute within an existing LXC Console".🤦‍♂️
