### ISSUE TITLE
Wireguard update issue

### ISSUE THREAD

**Issue by Dima-Kal** [community-scripts/ProxmoxVE#415]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Update command fails due to missing required python version

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
[WGDashboard] OS: debian
[WGDashboard] ✔ Python is installed
[WGDashboard] ✗ Could not find a compatible version of Python. Current Python is Python 3.9.2.
[WGDashboard] WGDashboard required Python 3.10, 3.11 or 3.12. Halting install now.
Terminated

[ERROR] in line 64: exit code 0: while executing command ./wgd.sh update
```

### Please provide detailed steps to reproduce the issue.

updated from a rather old version of wireguard lxc

**Comment by MickLesk** [comment]
Debian 11 dont support python >3.10 in default

Because the installation differs from our standards, I don't see it as an issue. 

you need to add this manually.
echo "deb http://deb.debian.org/debian bullseye-backports main" | sudo tee -a /etc/apt/sources.list
sudo apt update
sudo apt install -t bullseye-backports python3.10
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2
sudo update-alternatives --config python3

**Comment by Dima-Kal** [comment]
The standards were changed somewhere along the way, because the requirement was to use Debian 11 (while Proxmox 8 is on Debian 12)

https://github.com/tteck/Proxmox/issues/2377

more examples on the issue:
https://github.com/tteck/Proxmox/issues?q=Debian+11+wireguard

**Comment by Dima-Kal** [comment]
@MickLesk 

The standards were changed somewhere along the way, because the requirement was to use Debian 11 (while Proxmox 8 is on Debian 12)

https://github.com/tteck/Proxmox/issues/2377

more examples on the issue:
https://github.com/tteck/Proxmox/issues?q=Debian+11+wireguard

**Comment by MickLesk** [comment]
Then you cant use WGDashboard.

**Comment by MickLesk** [comment]
@havardthom @remz1337 @newzealandpaul what do you say? I don't want to inflate the script. Just because a post is 1 year ago that Debian 11 was used.

Then we should put out an announcement, I have noted the solution above.

**Comment by Dima-Kal** [comment]
@MickLesk 
BTW the suggested fix does not work:

```
root@wireguard:~# echo "deb http://deb.debian.org/debian bullseye-backports main" | sudo tee -a /etc/apt/sources.list
deb http://deb.debian.org/debian bullseye-backports main
root@wireguard:~# sudo apt update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Get:4 http://deb.debian.org/debian bullseye-backports InRelease [49.0 kB]
Get:5 http://deb.debian.org/debian bullseye-backports/main amd64 Packages [403 kB]
Get:6 http://deb.debian.org/debian bullseye-backports/main Translation-en [344 kB]
Fetched 795 kB in 1s (673 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@wireguard:~# sudo apt install -t bullseye-backports python3.10
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.10
E: Couldn't find any package by glob 'python3.10'
```

**Comment by Dima-Kal** [comment]
> And when you remove the .10?

it will try to install python 2

```
root@wireguard:~#  apt install -t bullseye-backports python
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
The following additional packages will be installed:
  libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib python2 python2-minimal python2.7 python2.7-minimal
Suggested packages:
  python2-doc python-tk python2.7-doc binfmt-support
The following NEW packages will be installed:
  libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib python-is-python2 python2 python2-minimal python2.7 python2.7-minimal
0 upgraded, 8 newly installed, 0 to remove and 36 not upgraded.
Need to get 3,956 kB of archives.
After this operation, 16.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
```

**Comment by Dima-Kal** [comment]
> And when you remove the .10?

```
root@wireguard:~#  apt install -t bullseye-backports python3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3 is already the newest version (3.9.2-3).
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
```

**Comment by havardthom** [comment]
This breaking change is announced here https://github.com/community-scripts/ProxmoxVE/blob/main/CHANGELOG.md#changed-18

relevant commits: https://github.com/community-scripts/ProxmoxVE/commit/9d579083bf9df05f1a425a865f85da1fbcd6d73f https://github.com/community-scripts/ProxmoxVE/commit/723365a79df7cc0fd29b1af8f7ef200a7e0921b1

If you want to update you need to migrate to debian 12

**Comment by Dima-Kal** [comment]
@havardthom 
tried to follow this https://www.cyberciti.biz/faq/update-upgrade-debian-11-to-debian-12-bookworm/
but I guess I F'd up:
```
dpkg: error processing package linux-headers-amd64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 linux-headers-6.1.0-27-amd64
 linux-headers-amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

It was updated to Debian 12:
```
root@wireguard:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

but update is not successful due to the issue above

Maybe introduce a script that updates LXC's to Debian 12?

**Comment by Dima-Kal** [comment]
found this thread:
https://github.com/tteck/Proxmox/discussions/1498
and then link to this thread:
https://forum.proxmox.com/threads/proxmox-ve-8-0-upgrade-error-while-building-linux-headers-6-1-0-10-amd64.130674/

and then this comment solved the issue:
```
sudo apt purge linux-headers-* linux-headers-*
```

update was successful but dashboard did not start, tried manually and got this error:


```
root@wireguard:~# /etc/wgdashboard/src/wgd.sh
=================================================================================
+          <WGDashboard> by Donald Zou - https://github.com/donaldzou           +
=================================================================================
| Usage: ./wgd.sh <option>                                                      |
|                                                                               |
| Available options:                                                            |
|    start: To start WGDashboard.                                               |
|    stop: To stop WGDashboard.                                                 |
|    debug: To start WGDashboard in debug mode (i.e run in foreground).         |
|    update: To update WGDashboard to the newest version from GitHub.           |
|    install: To install WGDashboard.                                           |
| Thank you for using! Your support is my motivation ;)                         |
=================================================================================
root@wireguard:~# /etc/wgdashboard/src/wgd.sh start
[WGDashboard] WireGuard is already installed.
------------------------------------------------------------
[WGDashboard] Starting WGDashboard with Gunicorn in the background.
[WGDashboard] Creating Python Virtual Environment under ./venv
/etc/wgdashboard/src/wgd.sh: line 46: ./log/install.txt: No such file or directory
[WGDashboard] ✗ Python Virtual Environment under ./venv failed to create. Halting now.
Terminated

```

**Comment by Dima-Kal** [comment]
Continuing with my journey:
1. Solution was apparently I needed to cd into /etc/wgdashboard/src, looks like an issue with the wgd.sh (and not Proxmox helper) for being that silly
2. Starting manually worked, but was not able to login, starting in debug showed me this issue:
```
  File "/etc/wgdashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/wgdashboard/src/dashboard.py", line 1736, in API_AuthenticateLogin
    valid = bcrypt.checkpw(data['password'].encode("utf-8"),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid salt
192.168.50.253 - - [21/Nov/2024 17:12:12] "POST /api/authenticate HTTP/1.1" 500 -
```
3. Found this thread in wgdashboard repo: https://github.com/donaldzou/WGDashboard/issues/509
if updating before 4.0.x need to remove a field from .ini file, searching the release announcement there was no mention of that breaking change as well

4. wgdashboard still does not auto start on boot, so needed to update service myself

what a clusterf**k of a mess on both repo's TBH

**Comment by MickLesk** [comment]
You're better off creating a new LXC ^^ 

or you hope that someone will debug debian 11 for you.

**Comment by Dima-Kal** [comment]
> You're better off creating a new LXC ^^
> 
> or you hope that someone will debug debian 11 for you.

I resolved the issues, just mentioned the steps I took if someone goes through the same thing

**Comment by havardthom** [comment]
For any future readers, I think the easiest way to migrate is just to install the new Wireguard LXC and copy over existing wireguard configurations from `/etc/wireguard`, they should not be affected by the breaking change.
