### ISSUE TITLE
[misc/post-pve-install.sh] Nag screen not disabled on Proxmox-VE 8.3.0

### ISSUE THREAD

**Issue by Fclem** [community-scripts/ProxmoxVE#421]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After running the script `misc/post-pve-install.sh` and selecting "disable nag screen",
the nag screen is still appearing on a fresh node Proxmox-VE 8.3.0 install when refreshing the packages list in the "Updates" tab.
This issue does not happen on my other proxmox nodes (albeit those have not been rebooted after the update) that had run this script before updating to 8.3.0

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. Install Proxmox-VE 8.2.2 on a new node.
2. Add `pve-no-subscription` repository
4. Upgrade all packages, and thus update to 8.3
5. Run `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/post-pve-install.sh)"`
6. Answer yes to all questions (select all the options)
7. After the reboot, the nag screen is still showing when refreshing the updatable package list in the "Updates" tab of the node.

**Comment by hautamik** [comment]
At the scripts end:

`if ! pveversion | grep -Eq "pve-manager/8.[0-2]"; then
  msg_error "This version of Proxmox Virtual Environment is not supported"
  echo -e "Requires Proxmox Virtual Environment Version 8.0 or later."
  echo -e "Exiting..."
  sleep 2
  exit
fi`

So 8.3 does not qualify, but gives an error. Until that is fixed (and perhaps verified that it _really_ works with 8.3) I downloaded the script, changed [0-2] to [0-3], gave execute permissions and ran it. 

Seems to work (both script and Proxmox).

**Comment by hautamik** [comment]
Apparently proxmox-widget-toolkit has been updated so the current script isn't able to make the changes that were effective earlier. I can live with the reminder (nag, some might call) and wait.

**Comment by MickLesk** [comment]
8.3 is accessible since today, it takes time to improve such scripts for the new version. ASAP

**Comment by Ajvdhoff** [comment]
You can disable the nag by commenting out the Ext.Msg.show in the proxmoxlib.js file located in the /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js, like i did here (line 566 for me): 
```checked_command: function (orig_cmd) {
			Proxmox.Utils.API2Request(
				{
					url: '/nodes/localhost/subscription',
					method: 'GET',
					failure: function (response, opts) {
						Ext.Msg.alert(gettext('Error'), response.htmlStatus);
					},
					success: function (response, opts) {
						let res = response.result;
						if (res === null || res === undefined || !res || res
							.data.status.toLowerCase() !== 'active') {
							// Ext.Msg.show({
							//     title: gettext('No valid subscription'),
							//     icon: Ext.Msg.WARNING,
							//     message: Proxmox.Utils.getNoSubKeyHtml(res.data.url),
							//     buttons: Ext.Msg.OK,
							//     callback: function(btn) {
							// 	if (btn !== 'ok') {
							// 	    return;
							// 	}
							// 	orig_cmd();
							//     },
							// });
						} else {
							orig_cmd();
						}
					},
				},
			);
		},```

**Comment by newzealandpaul** [comment]
@Ajvdhoff can you post or link to the original function without comments. I am trying to figure out why the existing script is not working.

**Comment by MickLesk** [comment]
i fix the script at the moment. @hautamik can you share me the output of:

cat /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js | grep 'data.status'

**Comment by cbrunnkvist** [comment]
Just install a fresh off the shelf 8.3 Proxmox VE ISO. I'm getting the following error:

```
Start the Proxmox VE Post Install Script (y/n)?y
 ✗ This version of Proxmox Virtual Environment is not supported
Requires Proxmox Virtual Environment Version 8.0 or later.
Exiting...
root@lemox:~# pveversion 
pve-manager/8.3.0/c1689ccb1065a83b (running kernel: 6.8.12-4-pve)
```

**Comment by MickLesk** [comment]
thats already in PR state and need approved by 2 @community-scripts/contributor

**Comment by derolli1976** [comment]
> 
> ```
> 			Proxmox.Utils.API2Request(
> 				{
> 					url: '/nodes/localhost/subscription',
> 					method: 'GET',
> 					failure: function (response, opts) {
> 						Ext.Msg.alert(gettext('Error'), response.htmlStatus);
> 					},
> 					success: function (response, opts) {
> 						let res = response.result;
> 						if (res === null || res === undefined || !res || res
> 							.data.status.toLowerCase() !== 'active') {

> 							 	orig_cmd();
> 						} else {
> 							orig_cmd();
> 						}
> 					},
> 				},
> 			);
> 		},```
> ```

You actually commented out a line too much. You need to leave to "orig_cmd();" in the if clause. Otherwise no commands (like "refresh" on the "Updates" page will actually do anything.

**Comment by Coffee0297** [comment]
I assume im bumping in to the same issue? 
![image](https://github.com/user-attachments/assets/0d41e5aa-13d3-4d31-9b8c-5743d0ae64da)

**Comment by sammyke007** [comment]
It's still showing up, is this normal?

**Comment by MickLesk** [comment]
Which Script ?

**Comment by sammyke007** [comment]
> Which Script ?

This script:
`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/post-pve-install.sh)"`

From:
[https://community-scripts.github.io/ProxmoxVE/scripts?id=post-pve-install](https://community-scripts.github.io/ProxmoxVE/scripts?id=post-pve-install)

I've said YES on every question while running the script.
The script confirms that he nag removal has been run, but the nag kept showing up.
Orrrrr could it have been a browser cache issue?
I've fixed it eventualy with

`
sed -Ezi.bak "s/(function\(orig_cmd\) \{)/\1\n\torig_cmd\(\);\n\treturn;/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js && systemctl restart pveproxy.service
`

Brand new Proxmox v8.3.0 install.

**Comment by MickLesk** [comment]
Works fine for me and hundert Others ^^ Do you have more nodes

**Comment by sammyke007** [comment]
> Works fine for me and hundert Others ^^ Do you have more nodes 

I'll be installing a new one in 3 days. I'll report back!

**Comment by MickLesk** [comment]
Please then do an new issue. Because i get 100-200 notifications per day

**Comment by sammyke007** [comment]
> Please then do an new issue. Because i get 100-200 notifications per day

Was my mistake (cache). Tried it on a new install and it worked 100% OK. Tnx!
