### ISSUE TITLE
Update script fails and breaks Vikunja

### ISSUE THREAD

**Issue by helderrscorreia** [community-scripts/ProxmoxVE#438]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the update script on the Vikunja LXC it fails with the error `environment: line 73: APPLICATION: unbound variable`.
After that Vikunja wont start.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![imagem](https://github.com/user-attachments/assets/4bc8db34-06bb-41b9-876c-ad7ff29531d2)

### Please provide detailed steps to reproduce the issue.

Just run the update script inside the LXC.

**Comment by MickLesk** [comment]
How you have Installed Vikunja?
