### ISSUE TITLE
Frigate install error (version check)

### ISSUE THREAD

**Issue by ksya** [community-scripts/ProxmoxVE#443]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

There are actually 2 issues.
1. github api rate limiting results in not getting latest release version of Frigate
2. jq is not install by default on proxmox, <-- not sure if this is available in the container

The error:
[ERROR] in line 57: exit code 0: while executing command wget -q https://github.com/blakeblackshear/frigate/archive/refs/tags/${RELEASE}.tar.gz -O frigate.tar.gz

It seams that $(RELEASE) is not filled, since api rate limiting is effective, there is not data. Therefore, Frigate cannot be installed. I think this needs to be catched in an error instead of stopping the script here.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

RELEASE=$(curl -s https://api.github.com/repos/blakeblackshear/frigate/releases/latest | jq -r '.tag_name')

### Please provide detailed steps to reproduce the issue.

Start script, use default settings, choose storage etc.. 
Script will stop with given error

**Comment by remz1337** [comment]
So you are saying that your IP got blocked by https://api.github.com/repos/blakeblackshear/frigate/releases/latest? Not sure how to reproduce this.
