### ISSUE TITLE
Proxmox VE Post Install does not work with 8.3

### ISSUE THREAD

**Issue by terrytrent** [community-scripts/ProxmoxVE#446]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the Proxmox VE Post Install script on proxmox 8.3 it says that it must be a 8.0 version.

This block seems to be the issue....not sure if modifying this to add in 3 to be available will break anything.

```bash
if ! pveversion | grep -Eq "pve-manager/8.[0-2]"; then
  msg_error "This version of Proxmox Virtual Environment is not supported"
  echo -e "Requires Proxmox Virtual Environment Version 8.0 or later."
  echo -e "Exiting..."
  sleep 2
  exit
fi
```

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by thefunnyben** [comment]
The script(s) just need to be updated to accept 8.3 (they currently check for 0-2).
