### ISSUE TITLE
Frigate installer failing during install

### ISSUE THREAD

**Issue by jappish84** [community-scripts/ProxmoxVE#457]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Tried installing a few times and keep getting errors during install on the same place. Seems to be related to `openvino` and `ssdlite_mobilenet_v2`

I am running an old server without AVX support, although SSE 4.2 should be supported. [CPU info](https://www.techpowerup.com/cpu-specs/xeon-e5620.c933)

```
8 x Intel(R) Xeon(R) CPU E5620 @ 2.40GHz (1 Socket)
--
Kernel Version Linux 6.8.12-4-pve (2024-11-06T15:04Z)
Boot Mode Legacy BIOS
Manager Version pve-manager/8.2.8/a577cfa684c7476d
```

My plan is to run frigate with USB Google Coral - no real need for iGPU support in my case. I have also tried installing with default settings. 

I found a [related ](https://github.com/community-scripts/ProxmoxVE/issues/294) issue but don't understand how it was solved

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Beginning of script:
```
    ______     _             __
   / ____/____(_)___ _____ _/ /____
  / /_  / ___/ / __ `/ __ `/ __/ _ \
 / __/ / /  / / /_/ / /_/ / /_/  __/
/_/   /_/  /_/\__, /\__,_/\__/\___/
             /____/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 0
Using Root Password: ********
Container ID: 102
Using Hostname: frigate
Using Disk Size: 20
Allocated Cores: 4
Allocated RAM: 8096
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: yes
Creating a Frigate LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 / Creating LXC Container  
 ```

Last couple of rows with the error:
```
-dtypes, h5py, grpcio, google-pasta, gast, defusedxml, astunparse, absl-py, openvino-dev, markdown, keras, tensorboard, tensorflow
 /  Attempting uninstall: openvino
    Found existing installation: openvino 2024.1.0
 -    Uninstalling openvino-2024.1.0:
      Successfully uninstalled openvino-2024.1.0
 /Successfully installed absl-py-2.1.0 astunparse-1.6.3 defusedxml-0.7.1 gast-0.6.0 google-pasta-0.2.0 grpcio-1.68.0 h5py-3.12.1 keras-3.6.0 libclang-18.1.1 markdown-3.7 ml-dtypes-0.4.1 namex-0.0.8 networkx-3.1 openvino-2024.5.0 openvino-dev-2024.5.0 opt-einsum-3.4.0 optree-0.13.1 tensorboard-2.18.0 tensorboard-data-server-0.7.2 tensorflow-2.18.0 tensorflow-io-gcs-filesystem-0.37.1 termcolor-2.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
 \################|| Downloading ssdlite_mobilenet_v2 ||################

========== Downloading /opt/frigate/models/public/ssdlite_mobilenet_v2/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz
... 100%, 49829 KB, 33511 KB/s, 1 seconds passedd
 \
========== Unpacking /opt/frigate/models/public/ssdlite_mobilenet_v2/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz
 |
 |========== Converting ssdlite_mobilenet_v2 to IR (FP16)
Conversion command: /usr/bin/python3 -- /usr/local/bin/mo --framework=tf --output_dir=/opt/frigate/models/public/ssdlite_mobilenet_v2/FP16 --model_name=ssdlite_mobilenet_v2 --input=image_tensor --reverse_input_channels --output=detection_scores,detection_boxes,num_detections --transformations_config=/usr/local/lib/python3.9/dist-packages/openvino/tools/mo/front/tf/ssd_v2_support.json --tensorflow_object_detection_api_pipeline_config=/opt/frigate/models/public/ssdlite_mobilenet_v2/ssdlite_mobilenet_v2_coco_2018_05_09/pipeline.config --input_model=/opt/frigate/models/public/ssdlite_mobilenet_v2/ssdlite_mobilenet_v2_coco_2018_05_09/frozen_inference_graph.pb '--layout=image_tensor(NHWC)' '--input_shape=[1, 300, 300, 3]' --compress_to_fp16=True

 -[ INFO ] MO command line tool is considered as the legacy conversion API as of OpenVINO 2023.2 release.
In 2025.0 MO command line tool and openvino.tools.mo.convert_model() will be removed. Please use OpenVINO Model Converter (OVC) or openvino.convert_model(). OVC represents a lightweight alternative of MO and provides simplified model conversion API. 
Find more information about transition from MO to OVC at https://docs.openvino.ai/2023.2/openvino_docs_OV_Converter_UG_prepare_model_convert_model_MO_OVC_transition.html
 \FAILED:
ssdlite_mobilenet_v2
 -
[ERROR] in line 114: exit code 0: while executing command $STD /usr/local/bin/omz_converter --name ssdlite_mobilenet_v2 --precision FP16 --mo /usr/local/bin/mo
root@proxmox:~#
```

### Please provide detailed steps to reproduce the issue.

running `root@proxmox:~# bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/frigate.sh)"` in the proxmox shell - error occurs with both default and advanced settings

**Comment by ristomatti** [comment]
I wonder if Frigate is too much of a moving target to support since the recommended installation method is via Docker? There's also still breaking changes on pretty much each major release. I've been running Frigate on Docker within a Debian LXC well over a year (originally installed using @tteck's "Docker LXC" script). Even with the nested virtualization, I've been surpised on how good the performance is.

**Comment by MickLesk** [comment]
> I wonder if Frigate is too much of a moving target to support since the recommended installation method is via Docker? There's also still breaking changes on pretty much each major release. I've been running Frigate on Docker within a Debian LXC well over a year (originally installed using @tteck's "Docker LXC" script). Even with the nested virtualization, I've been surpised on how good the performance is.


I've often asked myself the same question, and this is by far the script that causes the most problems. tteck had already seen it that way and wanted to remove it several times, but then many users complained.

**Comment by jappish84** [comment]
I actually managed to get past this by forking the repo and commenting out the Openvino install part in `frigate-install.sh`
Suggestion to the maintainers is to make optional installs deselectable if possible without to much hassle

**Comment by remz1337** [comment]
I'm suspecting it's the lack of AVX support. Unfortunately, I can't test further. I have a recent CPU and the default installation ran fine.

@jappish84 Can you log into the container and run this? please paste the detailed logs
```
cd /opt/frigate/models && /usr/local/bin/omz_converter --name ssdlite_mobilenet_v2 --precision FP16 --mo /usr/local/bin/mo
```

**Comment by Dino0811** [comment]
i got the same Error, CPU is Intel Celeron J4105 with integrated Intel® UHD Graphics 600 (Generation 9)

result of your code:

```shell
========== Converting ssdlite_mobilenet_v2 to IR (FP16)
Conversion command: /usr/bin/python3 -- /usr/local/bin/mo --framework=tf --output_dir=/opt/frigate/models/public/ssdlite_mobilenet_v2/FP16 --model_name=ssdlite_mobilenet_v2 --input=image_tensor --reverse_input_channels --output=detection_scores,detection_boxes,num_detections --transformations_config=/usr/local/lib/python3.9/dist-packages/openvino/tools/mo/front/tf/ssd_v2_support.json --tensorflow_object_detection_api_pipeline_config=/opt/frigate/models/public/ssdlite_mobilenet_v2/ssdlite_mobilenet_v2_coco_2018_05_09/pipeline.config --input_model=/opt/frigate/models/public/ssdlite_mobilenet_v2/ssdlite_mobilenet_v2_coco_2018_05_09/frozen_inference_graph.pb '--layout=image_tensor(NHWC)' '--input_shape=[1, 300, 300, 3]' --compress_to_fp16=True

[ INFO ] MO command line tool is considered as the legacy conversion API as of OpenVINO 2023.2 release.
In 2025.0 MO command line tool and openvino.tools.mo.convert_model() will be removed. Please use OpenVINO Model Converter (OVC) or openvino.convert_model(). OVC represents a lightweight alternative of MO and provides simplified model conversion API. 
Find more information about transition from MO to OVC at https://docs.openvino.ai/2023.2/openvino_docs_OV_Converter_UG_prepare_model_convert_model_MO_OVC_transition.html
FAILED:
ssdlite_mobilenet_v2
```

**Comment by jappish84** [comment]
As mentioned, I [forked](https://github.com/jappish84/ProxmoxVE) the repo and excluded openvino - frigate then installed without errors.

`
root@frigate:~# cd /opt/frigate/models && /usr/local/bin/
omz_converter --name ssdlite_mobilenet_v2 --precision FP1
6 --mo /usr/local/bin/mo
-bash: /usr/local/bin/omz_converter: No such file or dire
ctory
root@frigate:/opt/frigate/models#

`

@Dino0811 you could use my fork if your cpu doesn't support AVX.

@remz1337 I could try to modify the script to prompt the user to choose whether or not to install openvino instead of just skipping it and create a PR, let me know if that's how you'd like to go around the issue.

Another approach is to better check CPUs compability maybe?

**Comment by remz1337** [comment]
I've removed the SSE 4.2 supports. Should fix this issue.
