### ISSUE TITLE
"Your **default** shell is currently not set to Bash"

### ISSUE THREAD

**Issue by itsthejb** [community-scripts/ProxmoxVE#476]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi everyone,

First of all, let me take the opportunity to pay my respect to tteck, and thanks to everyone here for taking on this great project 🙇 

Quite a minor one from me: as you are probably aware, the scripts enforce being executed under Bash, otherwise they will exit with:

```
✗ Your default shell is currently not set to Bash. To use these scripts, please switch to the Bash shell.
```

However, what seems to me to be a little user-unfriendly is that it seems to be necessary to use `chsh` to switch the default shell (as per the message) to `bash` before proceeding. Surely it should be possible to maintain the Bash requirement, but only require the user to run under Bash beforehand? Requiring the default shell is quite inconvenient for those using other defaults. Currently:

- Run script; exits with error
- `chsh -s /bin/bash root`
- Run script again - works
- `chsh -s <previous default> root`

What seems more reasonable is just to check the current shell. So now it would be:

- Run script; exits with error
- `bash`
- Run script again - works. No config restore required

This seems possible and less intrusive.

Hope you can help!

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

- `chsh -s <some other shell> root`
- Run script; exits with error

**Comment by Mellowlynx** [comment]
We need to have a standard that we adhere to, and test with.
Bash is the default, as it's mostly the Linux default. If you choose to switch, it's up to you to work around this.
Most use bash, and this ensures, us, that the scripts behave the way we expect them to.

**Comment by itsthejb** [comment]
Sure, I understand that. What I'm suggesting is, it's possible to just check that the currently active shell is Bash. I'll do a quick PR and you can see what you think

**Comment by havardthom** [comment]
Why Bash is required as default shell is discussed in this thread https://github.com/tteck/Proxmox/discussions/2536#discussion-6251444. 
Specifically this comment https://github.com/tteck/Proxmox/discussions/2536#discussioncomment-8562395 mentions that simply invoking scripts with bash is not good enough if the script relies on Bash-specific features or behaviors. This can/has caused issues that are difficult to troubleshoot.

**Comment by itsthejb** [comment]
Alright, then. So be it
