### ISSUE TITLE
Case Sensitivity Issue with CT Naming in Advanced Settings

### ISSUE THREAD

**Issue by ali2key** [community-scripts/ProxmoxVE#489]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When creating a container (CT) in Proxmox through script > **Advanced Settings**, the provided CT name is automatically converted to lowercase.  

For example:  
- **Input Name**: `CT-107-NGINX`  
- **Actual Result**: `ct-107-nginx`  

### Expected Behavior  
The CT name should retain the exact casing as provided, e.g., `CT-107-NGINX`.  

### Steps to Reproduce  
1. Run script (e.g. bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/nginx.sh)")
2. Select **Advanced Settings**.  
3. Enter a name in mixed case, e.g., `CT-107-NGINX`.
4. Complete the setup process.  

### Current Behavior  
The resulting CT name is lowercased (`ct-107-nginx`).  

### Environment  
- **Proxmox Version**: 8.2.7

### Additional Notes  
- The case sensitivity of CT names can be critical for specific use cases, such as standardized naming conventions.  
- If this is an intentional feature, adding an option to preserve the original casing would be beneficial.  

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Expected Behavior  
The CT name should retain the exact casing as provided, e.g., `CT-107-NGINX`.  

### Steps to Reproduce  
1. Run script (e.g. bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/nginx.sh)")
2. Select **Advanced Settings**.  
3. Enter a name in mixed case, e.g., `CT-107-NGINX`.
4. Complete the setup process.  

### Current Behavior  
The resulting CT name is lowercased (`ct-107-nginx`).

**Comment by MickLesk** [comment]
Since when has it been possible to treat LXCs in a case-sensitive manner?

LXC container names in Proxmox are always **converted to lowercase**. Even if you create a container with uppercase letters (e.g., `Ubuntu`), it will be stored and managed as `ubuntu`.

#### Reasons:
1. **Consistency**: Proxmox enforces lowercase to avoid conflicts with case-sensitive Linux filesystems.
2. **File paths**: Container names are part of the paths (e.g., `/etc/pve/lxc/`) and are standardized to lowercase for compatibility.

**Comment by ali2key** [comment]
I was specifically referring to the CT name displayed in the Proxmox UI, not the hostname. It's worth noting that it is possible to manually create a CT name with uppercase letters directly in the UI.

Regarding point 2, I disagree with the reasoning. Proxmox refers to VMs/CTs using their IDs, not their names, so I don't believe case sensitivity would cause conflicts in this context.

**Comment by ali2key** [comment]
> Since when has it been possible to treat LXCs in a case-sensitive manner?
> 
> LXC container names in Proxmox are always **converted to lowercase**. Even if you create a container with uppercase letters (e.g., `Ubuntu`), it will be stored and managed as `ubuntu`.
> 
> #### Reasons:
> 1. **Consistency**: Proxmox enforces lowercase to avoid conflicts with case-sensitive Linux filesystems.
> 2. **File paths**: Container names are part of the paths (e.g., `/etc/pve/lxc/`) and are standardized to lowercase for compatibility.

I was specifically referring to the CT name displayed in the Proxmox UI, not the hostname. It's worth noting that it is possible to manually create a CT name with uppercase letters directly in the UI.

Regarding point 2, I disagree with the reasoning. Proxmox refers to VMs/CTs using their IDs, not their names, so I don't believe case sensitivity would cause conflicts in this context.
