### ISSUE TITLE
paperless-ngx 2.12.1 upgrade fails

### ISSUE THREAD

**Issue by rowie** [community-scripts/ProxmoxVE#490]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After 2 minutes when i start the update:

[ERROR] in line 97: exit code 0: while executing command /usr/bin/python3 manage.py migrate &> /dev/null

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 ✓ Ghostscript updated to 10.04.0
 ✓ Stopped all Paperless-ngx Services
 - Updating to v2.13.5   
[ERROR] in line 97: exit code 0: while executing command /usr/bin/python3 manage.py migrate &> /dev/null

### Please provide detailed steps to reproduce the issue.

start the update like always ..

**Comment by MickLesk** [comment]
Execute rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED in the LXC console and try again

**Comment by rowie** [comment]
same error:

 ✓ Ghostscript updated to 10.04.0
 ✓ Stopped all Paperless-ngx Services
 - Updating to v2.13.5   
[ERROR] in line 97: exit code 0: while executing command /usr/bin/python3 manage.py migrate &> /dev/null

root@paperless-ngx-ct:~# 

NOT Fixed for me, sorry!

**Comment by rowie** [comment]
I install paperless-ngx with your script. So why is it not a script issue?

**Comment by MickLesk** [comment]
https://github.com/tteck/Proxmox/discussions/2945
https://github.com/tteck/Proxmox/issues/2925
https://forum.proxmox.com/threads/paperless-ngx-update-script-fehler.150797/

Its not an script issue, its an issue from switch bookworm 12.5 to bookworm 12.6 and PaperlessNGX do some things different.

**Comment by rowie** [comment]
upgrading the LXC to debian 12 and installing the missing packages with pip install .. fixes my problem!
thank you and sorry for the inconvenience!
