### ISSUE TITLE
Scrypted

### ISSUE THREAD

**Issue by koush** [community-scripts/ProxmoxVE#494]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Hi, I’m the maintainer of Scrypted. I would appreciate it if Scrypted was removed from the helper scripts. It does not handle gpu/hardware pass-through correctly, and it has become a persistent support issue on my repository and discord. So much so, that I have added detection code to see if it’s from the helper script, and warn the user to install using the official script. There are official installation instructions and scripts for running Scrypted in proxmox already. 

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by MickLesk** [comment]
Wouldn't it make more sense to simply fix the script or provide information on what is not working or what needs to be fixed?

We can also remove it, I don't care in the end.

**Comment by remz1337** [comment]
Let me look into it. Not sure who built the script, since your own repo provides an installation script, I should be able to easily integrate that

**Comment by koush** [comment]
> Wouldn't it make more sense to simply fix the script or provide information on what is not working or what needs to be fixed?
> 
> We can also remove it, I don't care in the end.

I don't know what's broken, and I don't want to maintain two scripts/repos. This project is welcome to figure that out. It would probably be easier for maintainers and both repos, and users running into issues before realizing they used the wrong script, to simply remove the script.
