### ISSUE TITLE
Vikunja update wont save data

### ISSUE THREAD

**Issue by helderrscorreia** [community-scripts/ProxmoxVE#502]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After using the Vikunja update script the data is deleted.
It seems the folder `/opt/vikunja` is completed removed and the data is not saved somewhere else during the update.

### What settings are you currently utilizing?

- [ ] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Just run the update script and check for the already existing data.

**Comment by vhsdream** [comment]
I can confirm as someone who runs Vikunja but without the script. The [default configuration](https://vikunja.io/docs/config-options#1-database-path) is to store the database and the uploaded files in the /opt/vikunja folder. Perhaps the config should be modified upon install to have the db and files in /etc/vikunja where the config is located.
