### ISSUE TITLE
Calibre-web update error

### ISSUE THREAD

**Issue by Aloe-recite** [community-scripts/ProxmoxVE#509]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi all,
Running the "update" command on Calibre-web LXC gives this error with option 7-8-9 selected:

```
 /error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

[ERROR] in line 146: exit code 0: while executing command pip install --upgrade calibreweb[$cps_options]
```

If no option is selected:
` |environment: line 143: options: unbound variable`

After that, the container is broken and I had to restore from a backup.

IF updating from the web GUI, it gets stuck "stopping server" and I have to stop the LXC and again restore the previous backup.
<img width="478" alt="Screenshot 2024-11-25 alle 17 57 56" src="https://github.com/user-attachments/assets/b484a81f-8a3d-45e2-9280-5ed99aebde0c">

I'm running the previous to last version of Calibre on standard settings and with a mount point added on the NFS share that holds my library.
Please advise :)
Thanks! 

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Run "update" command on a calibre-web LXC with version previous to last installed.
Alternatively, perform the update from within the web GUI.

**Comment by havardthom** [comment]
https://github.com/tteck/Proxmox/discussions/3300#discussioncomment-9923938

**Comment by MickLesk** [comment]
Leave the issue open, I'll create a guide in discussion tomorrow.
