### ISSUE TITLE
Jackett CT script Error 

### ISSUE THREAD

**Issue by nonelocker** [community-scripts/ProxmoxVE#548]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Jackett CT script is error during creating CT.
: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jackett.sh)"
Error message is following : 
"[ERROR] in line 90: exit code 0: while executing command locale_line=$(grep -v '^#' /etc/locale.gen | grep -E '^[a-zA-Z]' | awk '{print $1}' | head -n 1)"

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

       __           __        __  __ 
      / /___ ______/ /_____  / /_/ /_
 __  / / __ `/ ___/ //_/ _ \/ __/ __/
/ /_/ / /_/ / /__/ ,< /  __/ /_/ /_  
\____/\__,_/\___/_/|_|\___/\__/\__/  
                                     
Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 106
Using Hostname: jackett
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Jackett LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 106 was successfully created.
 ✓ Started LXC Container
 / Setting up Container OS   
[ERROR] in line 90: exit code 0: while executing command locale_line=$(grep -v '^#' /etc/locale.gen | grep -E '^[a-zA-Z]' | awk '{print $1}' | head -n 1)
root@pve:~# 

### Please provide detailed steps to reproduce the issue.

 bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jackett.sh)"
and select default setting.

**Comment by MickLesk** [comment]
Can you use the right Repo? 
Its not tteck anymore.

**Comment by nonelocker** [comment]
I had same error with bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/jackett.sh)".

**Comment by nonelocker** [comment]
Same Error occurs with Prowlarr LXC script too.

**Comment by tjcomserv** [comment]
What happens when you run the following in proxmox shell? (should return the system's locale eg en-US.UTF-8)

grep -v '^#' /etc/locale.gen | grep -E '^[a-zA-Z]' | awk '{print $1}' | head -n 1

**Comment by nonelocker** [comment]
my result is following : 
root@pve:~# grep -v '^#' /etc/locale.gen | grep -E '^[a-zA-Z]' | awk '{print $1}' | head -n 1
en_US.UTF-8
root@pve:~# echo $LANG
en_US.utf8

**Comment by nonelocker** [comment]
I succeed after changing locale LANG (export LANG=en_US.UTF-8).
Thank You
