### ISSUE TITLE
Kernel Clean script doesn't remove 4 old (ii) kernels on PVE 8

### ISSUE THREAD

**Issue by onetimecontributor** [community-scripts/ProxmoxVE#551]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

On my Proxmox 8.3.0 (clean install, no on-top-of), executing the script results is 0 removed kernels, though there are 4 of them (ii) beside the two latest 

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. check kernels via "dpkg --list|grep proxmox-kernel.*-pve.*" - 6 in total, one iU, one not installed due to lack of disk space (6.8, tat's why I'm trying to clean it up), 4 more marked as ii
2. execute the script (as of 27.11) via bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/kernel-clean.sh)"
3. reboot
4. check kernels via dpkg --list|grep proxmox-kernel.*-pve.*

Expected: the list after 4 will differ from that in step 1
Actual: the list is the same
I had to uninstall them manually via dpkg -P <kernel> that worked just fine

**Comment by tjcomserv** [comment]
Just a thought, I presume when you ran the script, it gave a list of kernels and you manually selected the ones you wanted to delete like in the image below?

![image](https://github.com/user-attachments/assets/7cae4a4a-9554-4568-8b7a-da8db22c99b7)

**Comment by havardthom** [comment]
Did you get any errors? And did you get the `Removing 'selected' old Kernels` info message?
```
msg_info "Removing ${CL}${RD}$(echo $remove_kernels | awk '{print NF}') ${CL}${YW}old Kernels${CL}"
/usr/bin/apt purge -y $remove_kernels >/dev/null 2>&1
msg_ok "Successfully Removed Kernels"
```

**Comment by MickLesk** [comment]
can you test the dev change here?
```bash
 bash -c "$(wget -qLO - https://raw.githubusercontent.com/MickLesk/Proxmox_DEV/refs/heads/main/misc/kernel-clean.sh)"
``` 

it need some time, because proxmox changed some things in background

**Comment by darc432** [comment]
> can you test the dev change here?
> 
> ```shell
>  bash -c "$(wget -qLO - https://raw.githubusercontent.com/MickLesk/Proxmox_DEV/refs/heads/main/misc/kernel-clean.sh)"
> ```
> 
> it need some time, because proxmox changed some things in background

I tested and it is working (dev).

**Comment by MickLesk** [comment]
Perfect. Then i prepare an Bugfix PR asap
