### ISSUE TITLE
Zabbix - Legacy LXC script fails with 'update' CLI command

### ISSUE THREAD

**Issue by JohnyBeGood** [community-scripts/ProxmoxVE#557]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Basically, this is the original tteck Zabbix LXC script that worked well. I've tried using "update" inside CLI with root user and get below error.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![video](https://github.com/user-attachments/assets/4b887094-903e-4374-91ef-563fbefc5814)

### Please provide detailed steps to reproduce the issue.

root@zabbix:~# update 
_____         __    __    _
/__  /  ____ _/ /_  / /_  (_)  __
  / /  / __ `/ __ \/ __ \/ / |/_/
 / /__/ /_/ / /_/ / /_/ / />  <
/____/\__,_/_.___/_.___/_/_/|_|

 /Failed to stop zabbix-agent2.service: Unit zabbix-agent2.service not loaded.

[ERROR] in line 61: exit code 0: while executing command systemctl stop zabbix-server zabbix-agent2

root@zabbix:~#

**Comment by MickLesk** [comment]
Breaking Change Yesterday,
Switched to Zabbix Agent2.

https://github.com/community-scripts/ProxmoxVE/pull/527

**Comment by JohnyBeGood** [comment]
Thanks for the reply!

What do I need to do to make 'update' work again?

**Comment by MickLesk** [comment]
You need to Install zabbix-agent2 and remove the old agent. Backup your instance before

systemctl stop zabbix-server zabbix-agent

apt-get install --only-upgrade zabbix-server-pgsql zabbix-frontend-php zabbix-agent2 zabbix-agent2-plugin-* 
  

 systemctl start zabbix-server zabbix-agent2

**Comment by MickLesk** [comment]
You need to Install zabbix-agent2 and remove the old agent. Backup your instance before

systemctl stop zabbix-server zabbix-agent

apt-get install --only-upgrade zabbix-server-pgsql zabbix-frontend-php zabbix-agent2 zabbix-agent2-plugin-* 
  

 systemctl start zabbix-server zabbix-agent2


Edit: disable zabbix-agent with systemctl and enable agent2 after this
