### ISSUE TITLE
Paperless Update stuck at Updating Ghostscript

### ISSUE THREAD

**Issue by AzraelsDisk** [community-scripts/ProxmoxVE#57]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Running "update" in LXC stuck at Updating Ghostscript

Version update from2.12.0 to v2.13.4

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Proxmox version Virtual Environment 8.2.7

LXC is updated

![image](https://github.com/user-attachments/assets/61871035-dc79-45fb-876d-edfdc8b5f17c)

**Comment by MickLesk** [comment]
How Long stuck? Its Ghostscript. The make Install needs time..

**Comment by MickLesk** [comment]
> > How Long stuck? Its Ghostscript. The make Install needs time..
> 
> 15 Minutes, but I give it an other shot 
> 
> Ghostscript is updated and installed-->ghostscript is already the newest version (10.0.0~dfsg-11+deb12u5)
 

10 is not enough, need 10.4, therefore it need time

**Comment by AzraelsDisk** [comment]
> > > How Long stuck? Its Ghostscript. The make Install needs time..
> > 
> > 
> > 15 Minutes, but I give it an other shot
> > Ghostscript is updated and installed-->ghostscript is already the newest version (10.0.0~dfsg-11+deb12u5)
> 
> 10 is not enough, need 10.4, therefore it need time
> 
> I think my LXC need 20-25 min

I'm sorry.... it's done
I will be more patient next time
