### ISSUE TITLE
Not supported error on `8.3.0`

### ISSUE THREAD

**Issue by BoBoBaSs84** [community-scripts/ProxmoxVE#572]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I'm trying to execute the post install script:
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"`

I'm running pve 8.3.0.
I know the closing this issue #446 should be solving the problem.

![image](https://github.com/user-attachments/assets/27817143-12d3-45de-a3cf-a10f96d9f745)

Am I missing something?

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MickLesk** [comment]
Wrong Repo.

**Comment by BoBoBaSs84** [comment]
My bad thx.
