### ISSUE TITLE
Sonarr update not working, No Sonarr Installation Found

### ISSUE THREAD

**Issue by giannis371** [community-scripts/ProxmoxVE#589]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After typing the script on the LXC container
No Sonarr Installation Found!
Other scripts work.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MickLesk** [comment]
Done.
