### ISSUE TITLE
Something very weird

### ISSUE THREAD

**Issue by giannis371** [community-scripts/ProxmoxVE#597]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I tried to update prowlarr and radarr but i was getting error "There is currently no update path available."
So i checked inside the opt/Radarr and the dir is full of .dll files!
For example 
`BouncyCastle.Crypto.dll                               Microsoft.AspNetCore.Hosting.Server.Abstractions.dll       Microsoft.Extensions.Configuration.Binder.dll                   NLog.Targets.Syslog.dll                    System.ComponentModel.dll                       System.Net.Security.dll                                System.Security.dll
Dapper.dll                                            Microsoft.AspNetCore.Hosting.dll                           Microsoft.Extensions.Configuration.CommandLine.dll              NLog.dll                                   System.Configuration.ConfigurationManager.dll   System.Net.ServicePoint.dll                            System.ServiceModel.Web.dll
Diacritical.dll                                       Microsoft.AspNetCore.Html.Abstractions.dll                 Microsoft.Extensions.Configuration.EnvironmentVariables.dll     Newtonsoft.Json.dll                        System.Configuration.dll                        System.Net.Sockets.dll                                 System.ServiceProcess.ServiceController.dll
DryIoc.Microsoft.DependencyInjection.dll`

But the service is working normally, i can use radarr and prowlarr.
Is this any kind of hidden crypto miner?
My use my services over VPN.  

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MickLesk** [comment]
If you look at the install file of this:
https://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64

There are some .dlls inside. 
I think they either didn't clean up the packages or they built one AIO package for all distributions

**Comment by giannis371** [comment]
Ok then maybe there is something wrong with the script?
Because im getting ` ✗ There is currently no update path available.` 
and the `/var/lib/radarr` exists.

`function update_script() {
header_info
check_container_storage
check_container_resources
if [[ ! -d /var/lib/radarr/ ]]; then msg_error "No ${APP} Installation Found!"; exit; fi
msg_error "There is currently no update path available."
exit
}`
