### ISSUE TITLE
TheLounge - dos-style line-endings causing problems

### ISSUE THREAD

**Issue by jamezpolley** [community-scripts/ProxmoxVE#598]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I'm able to get it to work via dos2unix: `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/the-lounge.sh | dos2unix)"`

so I'm guessing this is an issue with the way the file has been saved?

### What settings are you currently utilizing?

- [ ] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
root@bully:~# bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/the-lounge.sh)"
: No such file or directory
bash: line 7: $'\r': command not found
bash: -c: line 8: syntax error near unexpected token `$'{\r''
bash: -c: line 8: `function header_info {
```

Running dos2unix on `the-lounge.sh` fixed the main problem, but I've run into another problem later:

```
N: Ignoring file 'nodesource.list
   ' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
```
### Please provide detailed steps to reproduce the issue.

1. Run the command provided at https://community-scripts.github.io/ProxmoxVE/scripts?id=the-lounge

**Comment by Sp3kt3r** [comment]
Just to confirm I have the same issue when trying to run the script.

`root@bully:~# bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/the-lounge.sh)"
: No such file or directory
bash: line 7: $'\r': command not found
bash: -c: line 8: syntax error near unexpected token `$'{\r''
bash: -c: line 8: `function header_info {`

**Comment by MickLesk** [comment]
I know. But currently i dont know why. If you Download the file it works smooth. Its very weird.

**Comment by Sp3kt3r** [comment]
just tried the script again after #599 completed and it work but now I get this error later:

![image](https://github.com/user-attachments/assets/69881ec9-05f2-47e2-9af1-3e9632b8f3bd)

**Comment by MickLesk** [comment]
Done gpg

**Comment by Sp3kt3r** [comment]
It works 👍 thx
