### ISSUE TITLE
HomeBridge script not working after upgrading to 8.3

### ISSUE THREAD

**Issue by pazhanir** [community-scripts/ProxmoxVE#604]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

HomeBridge script is not working in version 8.3

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="1192" alt="Screenshot 2024-11-30 at 1 31 02 PM" src="https://github.com/user-attachments/assets/b0461d72-180d-45f2-80e9-b68d8d96e801">

**Comment by MickLesk** [comment]
Where do you execute it? 
The Script cant pull our build.func, can you check If GitHub is reachable?

**Comment by pazhanir** [comment]
Fixed by Changing the ownership of the _resolv.conf_ file to the root user
