### ISSUE TITLE
Proxmox VE CPU Scaling Governor URL Link

### ISSUE THREAD

**Issue by vicky-bs** [community-scripts/ProxmoxVE#610]
### Please verify that you have read and understood the guidelines.

yes

### What type of issue is this?

Documentation

### A clear and concise description of the issue.

Link to URL (https://www.kernel.org/doc/html/latest/admin-guide/pm/cpufreq.html#generic-scaling-governors ) from old documentation to the text 'Generic Scaling Governors' to be added to the Proxmox VE CPU Scaling Governor script documentation 

### Which browser are you using?

Chrome

**Comment by tjcomserv** [comment]
Hi @vicky-bs , thank you for raising this. In keeping with the rest of the site, the URL you mention is now linked under the "Documentation" button.

![image](https://github.com/user-attachments/assets/f8967795-871e-4e2d-8e1a-77aebf875e3d)
