### ISSUE TITLE
Alpine Vaultwarden does not update webvault

### ISSUE THREAD

**Issue by LilTrublMakr** [community-scripts/ProxmoxVE#613]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When using the script to update Vaultwarden, it does not update the webvault. The script does update the webvault ("(81/81) Upgrading vaultwarden-web-vault (1.31.0-r0 -> 1.32.5-r0)"), it does not actually update it. When updated, the webvault would still be running the old version of the webvault.

In todays example, I was running "Vaultwarden Web Version 2024.5.0",and after the update, it stayed the same even after a restart.

To fix this, I had to manually update the webvault using the following:
```
WEBVAULT=$(curl -s https://api.github.com/repos/dani-garcia/bw_web_builds/releases/latest |
  grep "tag_name" |
  awk '{print substr($2, 2, length($2)-3) }')
curl -fsSLO https://github.com/dani-garcia/bw_web_builds/releases/download/$WEBVAULT/bw_web_$WEBVAULT.tar.gz
tar -xvzf bw_web_$WEBVAULT.tar.gz
rm -r /var/lib/vaultwarden/web-vault
mv ./web-vault/ /var/lib/vaultwarden/
rc-service vaultwarden restart
```

### What settings are you currently utilizing?

- [X] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Alpine

**Comment by towerhand** [comment]
This is what it shows in my diagnostics page in the admin panel, which seems like everything is up to date.

Versions:
- Server Installed Update
1.32.5-r0
Server Latest
1.32.5-da3701c0

- Web Installed
2024.6.2c
Web Latest
2024.6.2c

**Comment by LilTrublMakr** [comment]
That is what I am currently getting as well, but it is after I had to manually update the web vault. Before that my Vaultwarden login screen was showing "Version 2023.5.0" which made me think 'this seems really old... I wonder if there's an update...'

For the Alpine variant, I think the script is updating the binary web vault, but is not using the binary version.

**Comment by havardthom** [comment]
Are you using a custom config `/var/lib/vaultwarden/config.json` or the default config `/etc/conf.d/vaultwarden`? What is your `WEB_VAULT_FOLDER` setting?

The default config `/etc/conf.d/vaultwarden` should correctly point to `/usr/share/webapps/vaultwarden-web` where the package `vaultwarden-web-vault` is installed
```
export WEB_VAULT_FOLDER=/usr/share/webapps/vaultwarden-web
```

**Comment by LilTrublMakr** [comment]
Ah. Looks like this was changed all the way back in June 2023... https://github.com/community-scripts/ProxmoxVE/commit/e1037834d7e5cd02cf599223e2be5ddc95f75ce2
