### ISSUE TITLE
Problems with post install script

### ISSUE THREAD

**Issue by jiro1072** [community-scripts/ProxmoxVE#615]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I've installed the version of Proxmox 8.3.0 and tried to run the post install script :
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"`

unfortunately, it failed and I got the message.
```
 ✗ This version of Proxmox Virtual Environment is not supported
Requires Proxmox Virtual Environment Version 8.0 or later.
```

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="906" alt="Capture d'écran 2024-11-30 165959" src="https://github.com/user-attachments/assets/81318aa2-2c48-4a5b-a0d5-b7d008e7d165">

### Please provide detailed steps to reproduce the issue.

Install the version 8.3.0 via Boot USB and launch the post install script 
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"`

**Comment by MickLesk** [comment]
Wrong Repo!
