### ISSUE TITLE
Zabbix Postgres Default Login

### ISSUE THREAD

**Issue by GameEnder** [community-scripts/ProxmoxVE#617]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Fresh install of Zabbix from the script and the setup asks for login to the built in Postgres Database. Has some settings prefilled but they do not work to login. I did some looking on this Repo and the old Repo and am not find it documented anywhere. Just log login for Zabbix itself.

![image](https://github.com/user-attachments/assets/7b16ac1e-8a13-4a3e-aab0-c5b4a2532c04)

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MickLesk** [comment]
Do you check the Website before? There are written in an seperate Info Box.

**Comment by GameEnder** [comment]
You mean this?

![image](https://github.com/user-attachments/assets/0998e5c9-0ad4-4a54-b6b8-73326d83327e)

Tried that too.

![image](https://github.com/user-attachments/assets/f1bfa89b-de78-4e64-82b3-720fec30e10e)

**Comment by bahaman1971** [comment]
I'm sure I'm too inexperienced to fully understand the Linux command world (as a newbie) but on the proxmox helper script page, in the description of the "Database credentials" there is only the command "cat zabbix.creds" and that leads to the error message in the prompt (in the fresh install after the script) "cat: zabbix.creds: No such file or directory"
