### ISSUE TITLE
PBS - Bad Request (400) - command "zpool" "list" "-H" "-p" "-P" failed - status code: 1 

### ISSUE THREAD

**Issue by S1M8N** [community-scripts/ProxmoxVE#626]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,

When I install PBS with the LXC Script, it's impossible for me to create ZFS disks. When I go to the section, I have this error:
Bad Request (400)
command "zpool" "list" "-H" "-p" "-P" failed - status code: 1 - /dev/zfs and /proc/self/mounts are required. Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.

When I try to run "udevadm trigger" I have message say permission deny

Do you have an idea why ?

Thanks in advance

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/0ba839a2-e424-4b18-9518-dc42411fb306)

![image](https://github.com/user-attachments/assets/ba0d326b-397a-4754-af51-e02bc7a1434c)
![image](https://github.com/user-attachments/assets/ddde11f6-02ef-4b17-96c1-6a05c2162f0c)

### Please provide detailed steps to reproduce the issue.

Run script, default, [Enter when I can], connect to web ui with https://local_ip:8007
-> Section Storage / Disks
-> ZFS
-> Getting previous Error

**Comment by michelroegl-brunner** [comment]
Hello!

This is not an issue related to the install script. 
Did you add any mountpoints to the PBS LXC? If you installed it default it only has 10GB in one partition, you can not create a ZFS Pool there.
Consider consulting the PBS doks: https://pbs.proxmox.com/docs/introduction.html
