### ISSUE TITLE
Linkwarden Update Fails

### ISSUE THREAD

**Issue by hgelpke** [community-scripts/ProxmoxVE#633]
### Please verify that you have read and understood the guidelines.

I have

### A clear and concise description of the issue.

Updating from 2.6.4 to current

Ran "update" to update to the latest version. Monolith installed per the instructions

Receive the following error

 ✓ Stopped Linkwarden
 | Updating Linkwarden to v2.8.4   
[ERROR] in line 78: exit code 0: while executing command yarn build &> /dev/null

root@linkwarden:~# 

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 20.04

### Please provide detailed steps to reproduce the issue.

Open LXC console and type update.

**Comment by MickLesk** [comment]
I think Ubuntu 20.04 is now too old, because a newer Yarn version is needed. At least I cannot reproduce it in my 22.04.
