### ISSUE TITLE
PVE Post Install on Proxmox 8.3.0 failed, This version of Proxmox Virtual Environment is not supported

### ISSUE THREAD

**Issue by saschape** [community-scripts/ProxmoxVE#638]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

PVE Post Install on Proxmox 8.3.0 failed, This version of Proxmox Virtual Environment is not supported

   ____ _    ________   ____             __     ____           __        ____
   / __ \ |  / / ____/  / __ \____  _____/ /_   /  _/___  _____/ /_____ _/ / /
  / /_/ / | / / __/    / /_/ / __ \/ ___/ __/   / // __ \/ ___/ __/ __ `/ / /
 / ____/| |/ / /___   / ____/ /_/ (__  ) /_   _/ // / / (__  ) /_/ /_/ / / /
/_/     |___/_____/  /_/    \____/____/\__/  /___/_/ /_/____/\__/\__,_/_/_/

This script will Perform Post Install Routines.

Start the Proxmox VE Post Install Script (y/n)?y
 ✗ This version of Proxmox Virtual Environment is not supported
Requires Proxmox Virtual Environment Version 8.0 or later.
Exiting...

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MickLesk** [comment]
Wrong Repo.

**Comment by grahamgraham** [comment]
> Wrong Repo.

I get what you're saying, but a canned response that tells people to utilize the current website (https://community-scripts.github.io) would help make the transition from tteck's stuff over here smoother.

**Comment by MickLesk** [comment]
It would also help to look through the issues/discussions, the topic has probably already been discussed 5-10 times :smile:
