### ISSUE TITLE
PVE Post Install Script, just ends during update process

### ISSUE THREAD

**Issue by DerProGamer2000** [community-scripts/ProxmoxVE#654]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After running the Post Install Script on 8.3.0 
i press yes to all the options except disabling HA
after pressing yes to update it says patience for 2 sec 
and than it just throws me back into the comand line with no  further output.

it also doesnt ask me if i want to disable the update nag, which came back after the update to 8.3.0

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![chrome_mNKsaDnE1F](https://github.com/user-attachments/assets/dee6e886-c396-49d0-a6a7-bf972d8874dd)

### Please provide detailed steps to reproduce the issue.

look above

**Comment by MickLesk** [comment]
![image](https://github.com/user-attachments/assets/fef74de9-e38d-4e93-88d3-a3751d8dd5aa)


I can't reproduce that.

**Comment by DerProGamer2000** [comment]
> ![image](https://private-user-images.githubusercontent.com/47820557/391920102-fef74de9-e38d-4e93-88d3-a3751d8dd5aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzExMDgsIm5iZiI6MTczMzIzMDgwOCwicGF0aCI6Ii80NzgyMDU1Ny8zOTE5MjAxMDItZmVmNzRkZTktZTM4ZC00ZTkzLTg4ZDMtYTM3NTFkOGRkNWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NDllNTM1ZDNlNTA2ZTBkMTZhMzQ2NGNkZjEwMjI5MzQxZGI1ODMwNDNlNTBjNDVkNjBkMTQ0MTI1MTdhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xKLPioo0IB0iRP1GJcVuOt4NKoJJM80O37GaQD-sRWI)
> 
> I can't reproduce that.

i did read that for others it works normally but it doesnt for me, what steps could i take to see why it behaves like that? 
i already tried running the commands the script runs manually, but it gives no output when i type them in

**Comment by havardthom** [comment]
What is the output when you run these?
```
apt-get update
apt-get -y dist-upgrade
```

**Comment by DerProGamer2000** [comment]
> What is the output when you run these?
> 
> ```
> apt-get update
> apt-get -y dist-upgrade
> ```

i ran these. 
the first one worked fine but the second one just gave me a error that i should run "dpkg --configure -a" after doing that it seems to work fine now.

Thanks for the help! 
i thought i did ran these 2 command on their own while looking thru the source code before opening a issue report but i guess i did something incorrectly because it didnt give me that error lol...

**Comment by havardthom** [comment]
You probably ran `apt-get -y dist-upgrade &>/dev/null` from the script which will not give any output because of the `&>/dev/null` part.
