### ISSUE TITLE
Case Sensitivity Issue with CT Naming in Advanced Settings

### ISSUE THREAD

**Issue by ali2key** [community-scripts/ProxmoxVE#655]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When creating a container (CT) in Proxmox through script > Advanced Settings, the provided CT name is automatically converted to lowercase.

For example:

Input Name: CT-107-NGINX
Actual Result: ct-107-nginx

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

https://github.com/community-scripts/ProxmoxVE/issues/489
In my previous issue, "I was specifically referring to the CT name displayed in the Proxmox UI, not the hostname. It's worth noting that it is possible to manually create a CT name with uppercase letters directly in the UI.

Regarding point 2, I disagree with the reasoning. Proxmox refers to VMs/CTs using their IDs, not their names, so I don't believe case sensitivity would cause conflicts in this context."

### Please provide detailed steps to reproduce the issue.

1. Run script (e.g. bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/nginx.sh)")
2. Select Advanced Settings.
3. Enter a name in mixed case, e.g., CT-107-NGINX.
4. Complete the setup process.

**Comment by MickLesk** [comment]
How many times are you going to open this?

It is rejected. Then rebuild it yourself in the core. I don't take any risks to build possible vulnerabilities into a case sensitive system. You are welcome to get the opinion of others, but I for one will not install anything like that.

@judeibe @newzealandpaul @havardthom @remz1337

**Comment by havardthom** [comment]
Using lowercase letters for hostnames is a recommended best practice, as it helps maintain consistency and minimizes the likelihood of confusion. The scripts in use adhere to this practice. 
If you want to deviate from this best practice you can use `pct set <VMID> --hostname <newname>`
