### ISSUE TITLE
Proxmox Backup Server Post Install fails when PBS in installed on the host

### ISSUE THREAD

**Issue by cstby** [community-scripts/ProxmoxVE#667]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Proxmox Backup Server Post Install checks whether the `pveversion` command is available on the system as a way of preventing users from running the script on PVE (instead of PBS).

```
if command -v pveversion >/dev/null 2>&1; then
    echo -e "\n🛑  PVE Detected, Wrong Script!\n"
    exit 1
fi
```

IF PBS is installed on the host (an option included in the official documentation, even if it's not recommended), the script will fail.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

- Install PVE from scratch
- Add PBS to `sources.list` by adding the line `deb http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription`
- Install PBS on the host system using `apt update & apt upgrade` and then `apt install proxmox-backup-server`
- Log on to the backup server UI, and attempt to run the post-install script from the shell.

**Comment by havardthom** [comment]
Why would you run PBS directly on the host? Just install the LXC instead? https://community-scripts.github.io/ProxmoxVE/scripts?id=pbs

We don't want the scripts to mess with the host, and if we open this up there will be more people erroneously running this on their host than people that actually want to run PBS directly on host (who should use LXC instead).

**Comment by NaturalDevCR** [comment]
> Why would you run PBS directly on the host? Just install the LXC instead? https://community-scripts.github.io/ProxmoxVE/scripts?id=pbs
> 
> We don't want the scripts to mess with the host, and if we open this up there will be more people erroneously running this on their host than people that actually want to run PBS directly on host (who should use LXC instead).

Sorry for asking here but, what is the default login credentials for the PBS LXC installed with the scipt?, just can't figure it out

**Comment by docgalaxyblock** [comment]
@havardthom Please reopen this.
In my case I have two PVE HA worker nodes and a third PVE as the "quorum" node that is my main PBS.

The script should be changed to check if `proxmox-backup-manager` is available alongside of `pveversion`.
If only the latter is detected

Also I think renaming this issue to `Proxmox Backup Server Post Install fails when PBS in installed on the PVE host` could be better.

---

PS: Uhm I also do not see a check in the script if PBS is even installed - should I open a second issue for this?
