### ISSUE TITLE
Transfer of original repo into this organization

### ISSUE THREAD

**Issue by Neustradamus** [community-scripts/ProxmoxVE#67]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

@tteck: Why the original repository has not been moved into @community-scripts organization?
- https://github.com/tteck/Proxmox

Can you do it?

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

**Comment by newzealandpaul** [comment]
I am not sure the original reasoning, but please keep in mind tteck may not be able to answer questions. I don't think it matters going forward.

**Comment by MickLesk** [comment]
tteck wants the original code to remain unprocessed. The original repo has therefore been archived.

**Comment by Neustradamus** [comment]
@MickLesk: It has not been solved, can you reopen?

I have already explained steps to @BramSuurdje :)

The goal is to do not lost the history, fork, star, etc. and there will have redirections.
- 14.3k stars
- 194 Watchers
- 2.3k Forks
