### ISSUE TITLE
Linkwarden fails to update

### ISSUE THREAD

**Issue by AdmiralAwesome** [community-scripts/ProxmoxVE#672]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I'm trying to update Linkwarden to 2.8.4. From inside LXC I'm running

`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/linkwarden.sh)"`

which gives me:

```
cat: /opt/Linkwarden_version.txt: No such file or directory
 ✓ Stopped Linkwarden
 /mv: cannot stat '/opt/linkwarden/.env': No such file or directory

[ERROR] in line 68: exit code 0: while executing command mv /opt/linkwarden/.env /opt/.env

root@linkwarden:~#
```

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Install Linkwarden. Try to run update via script.

**Comment by MickLesk** [comment]
wtf? :D check your issue :smile:

**Comment by AdmiralAwesome** [comment]
Oh, sorry. Wrong copy-paste in my previous message. Now it's edited correctly and problem is still the same.

**Comment by MickLesk** [comment]
if you have created the file? :-O

**Comment by michelroegl-brunner** [comment]
Have you installed linkwarden with the Helper-Script or by hand? 

I just tested it with the Script and it works fine.

**Comment by hundehausen** [comment]
I have the same issue with the LXC created by the Helper-Script. Creating /opt/linkwarden/.env does not help.

**Comment by tistjendop** [comment]
I have the same issue and installed the container on April 18th 2024 using the helper script on Ubuntu 22.04 LTS. I updated the os (apt upgrade and apt upgrade) as well as Linkwarden (update script) without problems until now.

**Comment by MickLesk** [comment]
Then you dont have add monolith
