### ISSUE TITLE
Z-Wave JS Update Script Loses Config

### ISSUE THREAD

**Issue by bradarussell** [community-scripts/ProxmoxVE#683]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

I ran the z-wave JS UI update script to update to the latest version after a notification and the result is:

zwave-js-ui: 9.27.8
zwave-js: 14.3.7
home id: undefined
home hex: undefined

It lost the keys for S2 authentication and all devices are missing.  I restored a backup and tried again with the same result.  No big deal for me, but wanted to share in case it affects others.  Thanks to all who help for all their hard work and tteck (RIP) for creating this.

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Run the following in the Z-Wave JS UI LXC:

`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/zwave-js-ui.sh)"`

and then select upgrade functions.

**Comment by xijio** [comment]
This happened to me too, I just rebuilt my config from scratch. Took me couple hours going around the house and readding al the zwave devices.

**Comment by bradarussell** [comment]
> The script has made a breaking change. Check the discussions (always Announcements) to stay up to date.
> 
> #635

You guys are amazing.  Your instructions worked great.  Thanks so much for all you do!
