### ISSUE TITLE
Vikunja Script Update Dropped Config

### ISSUE THREAD

**Issue by xijio** [community-scripts/ProxmoxVE#684]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I updated vikunja using the update command and it delete my config.  I had to restore from backup.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Type update.

restart lxc
try to login, can't user doesn't exist
rollback

**Comment by michelroegl-brunner** [comment]
It seems the update function is deleting everything under /opt/

```
cd /opt
rm -rf /opt/*
```

I take a look at that later today @MickLesk .

**Comment by MickLesk** [comment]
there are no files there. thats an AIO Package

**Comment by havardthom** [comment]
Looks like db is stored in `/etc/vikunja/vikunja.db` and files stored in `/etc/vikunja/files`, not sure why users would be deleted in this update. Vikunja states they do necessary migrations on binary restart https://vikunja.io/docs/installing/#updating

**Comment by havardthom** [comment]
Ah probably an old install before this change https://github.com/havardthom/ProxmoxVE/commit/9795d41d398adf8b8086f2bd19da6bb7d9013eda

**Comment by michelroegl-brunner** [comment]
Yes, i´m testing this right now and i can not reproduce the issue so far.

**Comment by havardthom** [comment]
Probably best not to remove whole opt folder, for people with old config before that change

**Comment by michelroegl-brunner** [comment]
> Probably best not to remove whole opt folder, for people with old config before that change

There is a file create during install under /opt/vikunja but it doese not look like it is related to the update data loss problem.

If you want to, i can change the script to not delete the folder an do a PR.

**Comment by havardthom** [comment]
> > Probably best not to remove whole opt folder, for people with old config before that change
> 
> There is a file create during install under /opt/vikunja but it doese not look like it is related to the update data loss problem.
> 
> If you want to, i can change the script to not delete the folder an do a PR.

Sure, just delete the old binary instead of the whole folder :+1:
