### ISSUE TITLE
unifi.sh unable to update

### ISSUE THREAD

**Issue by niouniou49** [community-scripts/ProxmoxVE#685]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

the script to update unifi ends with 
[ERROR] in line 63: exit code 0: while executing command apt-get update --allow-releaseinfo-change

"Reading package lists... Done
W: GPG error: https://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 InRelease: The following signatures were invalid: EXPKEYSIG 656408E390CFB1F5 MongoDB 4.4 Release Signing Key <packaging@mongodb.com>
E: The repository 'https://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

just run update in the lxc of unifi

**Comment by michelroegl-brunner** [comment]
I can not reproduce your error, the update is running smoothly on Debian 12, so no script issue.
![Unify](https://github.com/user-attachments/assets/7f8077f9-a373-493e-a75d-20f2a8ec9ffe)

But it seems like you nedd to update the GPG keys. You can try and run the following code, and the run the update script again.

**Make a Backup of your LXC beforehand!**

```
 wget -qO- https://www.mongodb.org/static/pgp/server-4.4.asc | gpg --dearmor > /usr/share/keyrings/mongodb-server-4.2.gpg
 echo "deb [signed-by=/usr/share/keyrings/mongodb-server-4.4.gpg] https://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" >/etc/apt/sources.list.d/mongodb-org-4.4.list
```

**Comment by havardthom** [comment]
This is a bug related to https://github.com/community-scripts/ProxmoxVE/pull/319, I will have alook

**Comment by havardthom** [comment]
Actually not able to reproduce this, so I think @michelroegl-brunner is right that this is not a script issue. Did you update mongodb to 4.4 manually? 
I will update the install script to use 4.4 for non-AVX users anyway, since that is the latest version without AVX support
