### ISSUE TITLE
Unable to update Nginx Proxy Manager: python3 error while trying to install certbot-dns-cloudflare

### ISSUE THREAD

**Issue by LucasJanin** [community-scripts/ProxmoxVE#7]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I'm running the update for the first time.  
My current version of NPM is v2.11.1.  
The update fails.  

In the previous repository, the problem is marked as fixed :  https://github.com/tteck/Proxmox/discussions/4016  
That is not the case for me with the previous and new repositories.

Thanks in advance for your help

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
 ✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.12.1
 | Setting up Enviroment   
[ERROR] in line 137: exit code 0: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null

```

### Please provide detailed steps to reproduce the issue.

Run
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/nginxproxymanager.sh)"

**Comment by MickLesk** [comment]
An old comment from tteck:
"If you have manually updated to Debian 12.6, execute rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED in the LXC console.
The Proxmox VE LXC Updater and Proxmox VE Cron LXC Updater have been modified (6/29) for Debian 12.6."

**Comment by tteck** [comment]
Yep `rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED`

**Comment by LucasJanin** [comment]
> An old comment from tteck: "If you have manually updated to Debian 12.6, execute rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED in the LXC console. The Proxmox VE LXC Updater and Proxmox VE Cron LXC Updater have been modified (6/29) for Debian 12.6."

Problem fixed!!!
Thanks a lot @MickLesk and @tteck

**Comment by EnduringGuerila** [comment]
Ah, finally. Thanks!

**Comment by LucasJanin** [comment]
FYI, I still need to run:

rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED

to upgrade to v2.12.1
