### ISSUE TITLE
Komga Update Error: "✗ No Komga Installation Found!"

### ISSUE THREAD

**Issue by DaZuru** [community-scripts/ProxmoxVE#707]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installed custom with debian 12, system works. When running "update" or the script in the LXC it gives the "✗ No Komga Installation Found!" error. I tested another LXC with the default options and it behaved the same.

### What settings are you currently utilizing?

- [X] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Clean install. Run script in LXC or type update and error will be reproduced.

**Comment by MickLesk** [comment]
@DysfunctionalProgramming

**Comment by DysfunctionalProgramming** [comment]
I'll try to take a look this weekend
