### ISSUE TITLE
LXC Paperles-ng stuck on creation 

### ISSUE THREAD

**Issue by Athostechdevicesetup** [community-scripts/ProxmoxVE#724]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Stuck on Installing OCR dependencies

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

![image](https://github.com/user-attachments/assets/0f0be51e-b75b-40f5-af3c-ecf8ed5385ae)

**Comment by MickLesk** [comment]
How Long? Need 20min

**Comment by Athostechdevicesetup** [comment]
Yeap delay like 51 but finish , sorry
