### ISSUE TITLE
Recognize wrong RAM size (update)

### ISSUE THREAD

**Issue by rkolja76** [community-scripts/ProxmoxVE#732]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Sabnzbd update script (starting install/update script inside the container) does not recognize the amount of the lxc container correctly.

"⚠️  Required: 2 CPU, 2048MB RAM | Current: 8 CPU, MB RAM
Please ensure that the SABnzbd LXC is configured with at least 2 vCPU and 2048 MB RAM for the build process."

![grafik](https://github.com/user-attachments/assets/c8e85ca3-aa06-4025-9949-d2175a058e71)

But I have assigned 4 Gigs of RAM to the container.
I have also tried it with the zoraxy install/update script. Same error here. RAM is not recognized by the script.

Any idea?
Thanks guys! 

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![grafik](https://github.com/user-attachments/assets/79d85deb-d261-41c4-b1e7-9a1b0ab9100f)

**Comment by MickLesk** [comment]
Something in your lxc is broken. RAM Output is empty

**Comment by havardthom** [comment]
> Something in your lxc is broken. RAM Output is empty

The code assumes English language which is not the case here: `$(free -m | awk '/^Mem:/{print $2}')`

**Comment by MickLesk** [comment]
Puh, okay whats language has this LXC? 

We can change the function to: 
free -m | awk 'NR==2{print $2}'

Can you test this: 
echo "Systemmemory: $(free -m | awk 'NR==2{print $2}') MB"

**Comment by michelroegl-brunner** [comment]
The lxc is running in german. Wich is odd i guess?

**Comment by rkolja76** [comment]
That's correct - the lxc container is running in german.

**Comment by MickLesk** [comment]
Okay i fix it in the next Version of Develop PR

**Comment by rkolja76** [comment]
Thanks a lot!
