### ISSUE TITLE
nginx-proxy-manager exits script after cloning nvm -> /root/.bashrc: line 6: PS1: unbound variable

### ISSUE THREAD

**Issue by Taucher451** [community-scripts/ProxmoxVE#733]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

trying to install Nginx Proxy Manager 
with 
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/nginxproxymanager.sh)"
in the Proxmox VE console.

The script dumps after cloning nvm 

Using advanced settings for container: 

- fixed ipv4 address
- fixed gateway address
- unprivileged container
- anything else using default values

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Console output 

` \=> Downloading nvm from git to '/root/.nvm'
=> Cloning into '/root/.nvm'...
 -remote: Enumerating objects: 380, done.
remote: Counting objects: 100% (380/380), done.
remote: Compressing objects: 100% (323/323), done.
remote: Total 380 (delta 43), reused 179 (delta 29), pack-reused 0 (from 0)
Receiving objects: 100% (380/380), 382.75 KiB | 6.27 MiB/s, done.
Resolving deltas: 100% (43/43), done.
 \* (HEAD detached at FETCH_HEAD)
  master
 |=> Compressing and cleaning up git repository

=> Appending nvm source string to /root/.bashrc
=> Appending bash_completion source string to /root/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
**/root/.bashrc: line 6: PS1: unbound variable**`

### Please provide detailed steps to reproduce the issue.

call bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/nginxproxymanager.sh)"

in proxmox VE Shell

**Comment by MickLesk** [comment]
Test with Default settings

**Comment by havardthom** [comment]
![image](https://github.com/user-attachments/assets/298bdfa3-70e2-49ca-ab64-b4f5fdf95623)
