### ISSUE TITLE
Tandoor Recipes LXC Install Script fails

### ISSUE THREAD

**Issue by jaiewl** [community-scripts/ProxmoxVE#746]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have tried the script to install Tandoor Recipe. The script will exit at the following line:

[ERROR] in line 53: exit code 0: while executing command $STD npm install -g yarn

Prior to this I see:

Unpacking nodejs (20.18.1-1nodesource1) ...
 -Setting up nodejs (20.18.1-1nodesource1) ...
Processing triggers for man-db (2.11.2-2) ...
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/yarn - Not found
npm error 404
npm error 404  'yarn@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-08T18_27_12_359Z-debug-0.log

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

I run the script on Proxmox 8.3.1 PVE shell. 

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/tandoor.sh)"

**Comment by MickLesk** [comment]
DNS Error? Yarn package cant be downloadex

**Comment by jaiewl** [comment]
Possibly. I tried the script again this morning and it worked so no changes on my end. Looks like https://registry.npmjs.org/yarn couldn't be reached temporarily. Thanks for the suggestion.
