### ISSUE TITLE
Zigbee2MQTT installation fails

### ISSUE THREAD

**Issue by tommeh1337** [community-scripts/ProxmoxVE#747]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello all,

When installing Zigbee2MQTT via the Proxmox VE Helper Script I receive an error related to "npm":

I am running the advanced settings to enable verbose mode. But I made sure all settings are identical to the "default" settings. 

Looks like the script needs an update? Or could it be something with my system/setup?

Thanks in advance for your help. And thank you for your this project, really great initiative to carry on with tteck's work.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
 ✓ Set up Zigbee2MQTT Repository
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/jest-diff/-/jest-diff-29.7.0.tgz - Not found
npm error 404
npm error 404  'jest-diff@https://registry.npmjs.org/jest-diff/-/jest-diff-29.7.0.tgz' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-08T18_42_51_305Z-debug-0.log

[ERROR] in line 45: exit code 0: while executing command $STD npm ci
root@pve:~# 
```

**Comment by MickLesk** [comment]
Do you read the discussion annoucment? Npm is deprecated for dev branch. You need to migrate himself.
