### ISSUE TITLE
Umbrel.sh

### ISSUE THREAD

**Issue by michelroegl-brunner** [community-scripts/ProxmoxVE#748]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Umbrel.sh fails during install.

It seems Umbrell Switch to a OS-based install, so mybe this script needs to be removed.

[New way to install Umbrel](https://github.com/getumbrel/umbrel/wiki/Install-umbrelOS-on-a-Linux-VM)

![umbrel](https://github.com/user-attachments/assets/376cf75b-3777-44d5-bd76-49214d2e44f7)

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by MickLesk** [comment]
Script is already removed on webpage and only as reminder in scripts
