### ISSUE TITLE
On the Helper Scripts Website the Zabbix Default Login Credential is writen admin instead of Admin

### ISSUE THREAD

**Issue by MickLesk** [community-scripts/ProxmoxVE#75]
### Discussed in https://github.com/community-scripts/ProxmoxVE/discussions/71

<div type='discussions-op-text'>

<sup>Originally posted by **mogultekin** November  5, 2024</sup>
On the Helper Scripts Website the Zabbix Default Login Credential is writen admin instead of Admin. When tried to login for the first time looking at the written name. Then I searched to reset it. There I saw and remembered the default user is Admin. It will be good to correct it. 

BR,
mogultekin </div>

**Comment by BramSuurdje** [comment]
issue has been fixed. thanks!

![image](https://github.com/user-attachments/assets/85695a9a-b2bb-48ef-a022-080a5e74707c)
