### ISSUE TITLE
Proxmox VE Post Install Version not Supported

### ISSUE THREAD

**Issue by Fabo3D** [community-scripts/ProxmoxVE#751]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

On version 8.3.0 of Proxxmox I get this output: 
Start the Proxmox VE Post Install Script (y/n)?Y
 ✗ This version of Proxmox Virtual Environment is not supported
Requires Proxmox Virtual Environment Version 8.0 or later.
Exiting..

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![PXE](https://github.com/user-attachments/assets/8b6655cf-b2e4-4969-9988-77c25740b0e5)

**Comment by flashadams** [comment]
post-pve-install.sh is the script. I just changed the version check to 0-3 from 0-2 and it resolved and ran fine.

**Comment by MickLesk** [comment]
Ive asked for the Script not the Name..you use the wrong

**Comment by flashadams** [comment]
@MickLesk, I use the wrong what? You posted "Which Script?" I gave you the script name (is there a better way to reference it beyond name?)

**Comment by MickLesk** [comment]
> @MickLesk, I use the wrong what? You posted "Which Script?" I gave you the script name (is there a better way to reference it beyond name?)

URL of this Script or the bash call

**Comment by Fabo3D** [comment]
Thanks for the quick fix !!😁
