### ISSUE TITLE
NGINX Proxy Manager LXC - geoip2 module missing

### ISSUE THREAD

**Issue by lepo80** [community-scripts/ProxmoxVE#772]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I don't find the geoip2 module presence. I tried to install after the current script installation, but when upgrade the container the geoip2 modle broken.

is it feasable to add it into the current NGINX Proxy Manager LXC script intallation, please?
thanks

### What settings are you currently utilizing?

- [X] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

the geoip2 module is missing into the current script installation

### Please provide detailed steps to reproduce the issue.

N/A

**Comment by lepo80** [comment]
The current installation doesn't have the geoip2 module installed. Did you find it?
My simply request is to add it into the current installation script, of it is feasible... I tried to add it in secondary step, but when I upgrade the lxc using the script, the geoip module it doesn't work anymore.
Frankly speaking, I don't get your message meaning. If my request is out of the issue request expectations, it can be deleted.
For myself, the geoip2 module can very useful into the reverse proxy service.

**Comment by MickLesk** [comment]
What is geoip2? Its Not a dependency

**Comment by lepo80** [comment]
The GeoIP2 module for NGINX is an advanced feature used to determine the geographical location of users accessing your server. It integrates with MaxMind's GeoIP2 databases to map IP addresses to specific data, such as country, city, latitude, longitude, ISP, and more. This information can be utilized to tailor content, apply location-based restrictions, or enhance logging and analytics. The module requires the GeoIP2 library and databases to be installed separately and supports configuration through directives in the NGINX configuration file. It's a modern alternative to the older GeoIP module, offering better accuracy and more detailed data.

For example, you have a lab environment and you want to accept the connection to your site/service provided by NGINX for only a specific country /region (security needs).  This module permits to declare it into the Nginx host advanced configuration.

**Comment by lepo80** [comment]
It be that I'm wrong to open a request like issue.. sorry for this!

**Comment by MickLesk** [comment]
Then is this a topic for discussion, Not an issue.
