### ISSUE TITLE
Esphome update error

### ISSUE THREAD

**Issue by Tux92** [community-scripts/ProxmoxVE#778]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Running update script on an ESPHOME LXC give this error:

`[ERROR] in line 68: exit code 0: while executing command pip3 install -U esphome &> /dev/null`

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by havardthom** [comment]
Have you manually updated LXC to Debian 12.6? Try this fix https://github.com/community-scripts/ProxmoxVE/discussions/555

**Comment by Tux92** [comment]
Thank you very much this works!
