### ISSUE TITLE
https://community-scripts.github.io/ gives 404

### ISSUE THREAD

**Issue by xijio** [community-scripts/ProxmoxVE#779]
### Please verify that you have read and understood the guidelines.

yes

### What type of issue is this?

Bug

### A clear and concise description of the issue.

Navigating to https://community-scripts.github.io/ gives a 404 error.  The correct URL for the helper scripts is https://community-scripts.github.io/ProxmoxVE/.  It would be great if the root url either had some information or redirected to the ProxmoxVE directory. Or at the very least had a simple html page that told people to use the correct URL

### Which browser are you using?

Firefox

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Not needed

### Please provide detailed steps to reproduce the issue.

1) Navigate to https://community-scripts.github.io/
2) See 404 error
3) be sad :(

**Comment by BramSuurdje** [comment]
not possible, it's a limitation of github

**Comment by MickLesk** [comment]
For TE: its better when u use https://helper-scripts.com/ :-)
