### ISSUE TITLE
Proxmox VE Post Install is not running on 8.3.0

### ISSUE THREAD

**Issue by kokobadu** [community-scripts/ProxmoxVE#784]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While trying to install "Proxmox VE Post Install" on fresh Proxmox 8.3.0 instalation I'm getting:
`Start the Proxmox VE Post Install Script (y/n)?y

 ✗ This version of Proxmox Virtual Environment is not supported

Requires Proxmox Virtual Environment Version 8.0 or later.

Exiting...

root@pve:~# `

Any hints?

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by kokobadu** [comment]
As in the title "Proxmox VE Post Install".
Now I did try it on other machine: the same result:
`Requires Proxmox Virtual Environment Version 8.0 or later.

Exiting...`

**Comment by error13376** [comment]
Hey, just created an account to give you all a heads up on this quick fix while I figure out git and github.

In the post install script, in line 234, there is a check for the pve version. 
It checks from 8.0 to 8.2. But the PVE version changed to 8.3, hence why its failing.

I changed the check locally to 8.[0-3] and the script ran perfectly again.

**Comment by MickLesk** [comment]
Dudes, I'm asking specifically which script, not the name. 
You're 100% using the wrong one and it's been fixed for weeks!

**Comment by error13376** [comment]
> Dudes, I'm asking specifically which script, not the name. You're 100% using the wrong one and it's been fixed for weeks!

You are 100% correct, my bad. I didnt see the news about tteck passing and the change of repositories, and was still using his repository instead of the new one.
This "bug" is non-existent in the current script.

**Comment by MickLesk** [comment]
Change your Bookmarks to the new repo :-P

**Comment by kokobadu** [comment]
Consider it done. Thanks for help.
