### ISSUE TITLE
Plex LXC update script bug

### ISSUE THREAD

**Issue by fabien4444** [community-scripts/ProxmoxVE#794]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello
in a CT LXC proxmox, i used to run the script to update Plex Media Server. Since today, it was working flawlessly but the last script displays error:

\ Updating Plex LXC   
[ERROR] in line 65: exit code 0: while executing command apt-get update &> /dev/null

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 23.04

### Please provide detailed steps to reproduce the issue.

i run the script:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/plex.sh)"

then update and OK

**Comment by MickLesk** [comment]
At first update your OS. Plex is for Ubuntu 22.04. we only support Issues with correct OS

**Comment by fabien4444** [comment]
> At first update your OS. Plex is for Ubuntu 22.04. we only support Issues with correct OS

My mistake, my version is Ubuntu 23.04. I modify my ticket

**Comment by MickLesk** [comment]
i see you use the wrong script. check repo.

**Comment by Carloz1112** [comment]
I also got the same error.
I even used what i think should be the correct script by using
`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/plex.sh)"`
But i get the same error.
It seems like it fail the "apt-get update" command. If prompted in the terminal this error comes up:

> Hit:1 https://downloads.plex.tv/repo/deb public InRelease
> Ign:2 http://archive.ubuntu.com/ubuntu lunar InRelease
> Ign:3 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
> Ign:4 http://archive.ubuntu.com/ubuntu lunar-security InRelease
> Err:5 http://archive.ubuntu.com/ubuntu lunar Release
>   404  Not Found [IP: 91.189.91.82 80]
> Err:6 http://archive.ubuntu.com/ubuntu lunar-updates Release
>   404  Not Found [IP: 91.189.91.82 80]
> Err:7 http://archive.ubuntu.com/ubuntu lunar-security Release
>   404  Not Found [IP: 91.189.91.82 80]
> Reading package lists... Done
> E: The repository 'http://archive.ubuntu.com/ubuntu lunar Release' no longer has a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'http://archive.ubuntu.com/ubuntu lunar-updates Release' no longer has a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: The repository 'http://archive.ubuntu.com/ubuntu lunar-security Release' no longer has a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by MickLesk** [comment]
> I also got the same error.
> I even used what i think should be the correct script by using
> `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/plex.sh)"`
> But i get the same error.
> It seems like it fail the "apt-get update" command. If prompted in the terminal this error comes up:
> 
> > Hit:1 https://downloads.plex.tv/repo/deb public InRelease
> > Ign:2 http://archive.ubuntu.com/ubuntu lunar InRelease
> > Ign:3 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
> > Ign:4 http://archive.ubuntu.com/ubuntu lunar-security InRelease
> > Err:5 http://archive.ubuntu.com/ubuntu lunar Release
> >   404  Not Found [IP: 91.189.91.82 80]
> > Err:6 http://archive.ubuntu.com/ubuntu lunar-updates Release
> >   404  Not Found [IP: 91.189.91.82 80]
> > Err:7 http://archive.ubuntu.com/ubuntu lunar-security Release
> >   404  Not Found [IP: 91.189.91.82 80]
> > Reading package lists... Done
> > E: The repository 'http://archive.ubuntu.com/ubuntu lunar Release' no longer has a Release file.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > E: The repository 'http://archive.ubuntu.com/ubuntu lunar-updates Release' no longer has a Release file.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > E: The repository 'http://archive.ubuntu.com/ubuntu lunar-security Release' no longer has a Release file.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.




Which Settings? Default works fine in 2 nodes

**Comment by platini76** [comment]
I used the script bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/plex.sh)"

get this error:
[ERROR] in line 41: exit code 0: while executing command apt-get update &> /dev/null

**Comment by jakemauer** [comment]
I got the same error as @platini76 and I think I know the reason.

The update script calls `header_info` which is included from https://github.com/community-scripts/ProxmoxVE/blob/main/misc/build.func

Line 162 of build.func checks to see if the container has the file  `/etc/debian_version`, if it does it then checks to see if your `/etc/apt/sources.list` contains the source for debian bookworm, and if it doesn't, it adds it. Since the Plex LXC is based around Ubuntu Jammy I *think* this is what breaks things.

If I edit the `/etc/apt/sources.list` file on my Plex LXC after running `update` and remove the reference to the Bookworm source I can then run `apt update` and `apt upgrade` normally.

**Comment by platini76** [comment]
in /etc/apt/sources.list

I have:
# Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources

and in this file:
Types: deb
URIs: http://archive.ubuntu.com/ubuntu
Suites: noble noble-updates
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://security.ubuntu.com/ubuntu
Suites: noble-security
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

please can you say me what to do?

**Comment by platini76** [comment]
> I got the same error as @platini76 and I think I know the reason.
> 
> The update script calls `header_info` which is included from https://github.com/community-scripts/ProxmoxVE/blob/main/misc/build.func
> 
> In the `header_info` function on Line 162 of build.func it checks to see if the container has the file `/etc/debian_version`, if it does it then checks to see if your `/etc/apt/sources.list` contains the source for debian bookworm, and if it doesn't, it adds it. Since the Plex LXC is based around Ubuntu Jammy I _think_ this is what breaks things.
> 
> If I edit the `/etc/apt/sources.list` file on my Plex LXC after running `update` and remove the reference to the Bookworm source I can then run `apt update` and `apt upgrade` normally.

in /etc/apt/sources.list

I have:

Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources
and in this file:
Types: deb
URIs: http://archive.ubuntu.com/ubuntu
Suites: noble noble-updates
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://security.ubuntu.com/ubuntu
Suites: noble-security
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

please can you say me what to do?

**Comment by Outsmart2383** [comment]
Just checking in to say that I also have the same error.
` ⠋ Updating Plex LXC 
[ERROR] in line 41: exit code 0: while executing command apt-get update &> /dev/null`

`PRETTY_NAME="Ubuntu 22.04.5 LTS"`
