### ISSUE TITLE
Linkwarden error

### ISSUE THREAD

**Issue by doozybytes** [community-scripts/ProxmoxVE#796]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Linkwarden installation fails with error code. 

### What settings are you currently utilizing?

- [ ] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

  Downloaded async-compression v0.4.18
  Downloaded 164 crates (22.6 MB) in 1.75s (largest was `openssl-src` at 9.9 MB)
 \error: failed to compile `monolith v2.8.3`, intermediate artifacts can be found at `/tmp/cargo-install5IttYs`

Caused by:
  package `tokio-util v0.7.13` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.63.0
  Try re-running cargo install with `--locked`

[ERROR] in line 41: exit code 0: while executing command $STD cargo install monolith

### Please provide detailed steps to reproduce the issue.

Trying to install linkwarden LXC using `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/linkwarden.sh)"`

**Comment by MickLesk** [comment]
Have you installed Monolith?

https://github.com/community-scripts/ProxmoxVE/discussions/305

**Comment by doozybytes** [comment]
> Have you installed Monolith?
> 
> https://github.com/community-scripts/ProxmoxVE/discussions/305

Monolith install is handled by the script.

Failure is actually due to rust version requirement:

```
package tokio-util v0.7.13 cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.63.0
```

**Comment by MickLesk** [comment]
Okay thats a Clean new Install?

**Comment by doozybytes** [comment]
> Okay thats a Clean new Install?

Yes, I just run the script for a new LXC install and get this.

**Comment by MickLesk** [comment]
Tested on 2 Devices, Work fine for me:

![image](https://github.com/user-attachments/assets/c4d539c3-dd36-479c-a786-7c1c0d9d9902)

**Comment by doozybytes** [comment]
> Tested on 2 Devices, Work fine for me:
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/c4d539c3-dd36-479c-a786-7c1c0d9d9902)
> 
> 

Please refer to the issue details, it clearly states Debian

**Comment by MickLesk** [comment]
![image](https://github.com/user-attachments/assets/a25d683a-4aa1-41f6-8a45-b75e6fa4b301)

**Comment by doozybytes** [comment]
What do you mean? The fail happens with Debian 12....this is an easy dependency fix

**Comment by MickLesk** [comment]
Sorry, confused statement, i mean its an debian thing, default is ubuntu for this. Because Debian has another repo and this is older

**Comment by doozybytes** [comment]
I understand. 

But why not fix the issue if it is known and reported? Why close the ticket and let a known issue be? If other distributions are not supported, clearly indicate it or remove the option.

Leaving this issue persist only creates a worse user experience for anyone not aware where to look for solutions.

**Comment by MickLesk** [comment]
Because you accept the guidelines of the Script.
Advanced Settings with another OS are a Breaking Change and we cant fix for every os with every version. Look at the Screenshot of Issue Creating. 

Your Script Braking at this part:
```bash
msg_info "Installing Monolith"
$STD cargo install monolith
export PATH=~/.cargo/bin:$PATH
msg_ok "Installed Monolith"
```

Cargo provides the values matching the OS. If Debian12 provides old or other dependencies, we cannot implement a fix only for this OS
