### ISSUE TITLE
Error Trying To Upgrade SABnzbd

### ISSUE THREAD

**Issue by wdpronovost** [community-scripts/ProxmoxVE#808]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Command:

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/sabnzbd.sh)"

Error:
 \ Updating SABnzbd to 4.4.0   
[ERROR] in line 68: exit code 0: while executing command python3 -m pip install -r requirements.txt &> /dev/null

I tried to get verbose logging but could not figure out how. Apologies.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Run script, select yes for upgrade.

python3 version 3.11.2

**Comment by MickLesk** [comment]
Try this - i think you have updated your os manually:

https://github.com/community-scripts/ProxmoxVE/discussions/555

**Comment by wdpronovost** [comment]
That did work. So am I to assume that I'm not to use `apt update && apt upgrade` in this LXC?

Either way, thank you!

**Comment by MickLesk** [comment]
Unfortunately, this was a Debian bug that we could not work around.
