### ISSUE TITLE
Error while installing Alpine-Nextcloud

### ISSUE THREAD

**Issue by kmavrov** [community-scripts/ProxmoxVE#813]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When trying to install Alpine-Nextcloud (Default/Advanced Settings) i end up with this error message:

 - Installing MySQL Database...mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
 ✓ Installed MySQL Database
 - Installing Nextcloud...sed: /etc/php82/php-fpm.d/nextcloud.conf: No such file or directory

[ERROR] in line 138: exit code 1: while executing command sed -i -E '/^php_admin_(flag|value)\[opcache/s/^/;/' /etc/php82/php-fpm.d/nextcloud.conf

### What settings are you currently utilizing?

- [X] Default Settings
- [X] Advanced Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 - Installing MySQL Database...mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
 ✓ Installed MySQL Database
 - Installing Nextcloud...sed: /etc/php82/php-fpm.d/nextcloud.conf: No such file or directory

[ERROR] in line 138: exit code 1: while executing command sed -i -E '/^php_admin_(flag|value)\[opcache/s/^/;/' /etc/php82/php-fpm.d/nextcloud.conf

### Please provide detailed steps to reproduce the issue.

Copy/paste the install script and choose defauilt settings

**Comment by kangaroo72** [comment]
I can confirm the issue and would be happy for a solution.
Thanks.

**Comment by michelroegl-brunner** [comment]
The error seems to be related to the php version. 8.2 gets installed but but nextcloud tries 8.3. I hwill have a look.

**Comment by kmavrov** [comment]
Thank you !
