### ISSUE TITLE
Installing SABnzbd via script fails when installing in advanced mode on Ubuntu

### ISSUE THREAD

**Issue by etzadla** [community-scripts/ProxmoxVE#816]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

SABnzbd

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/sabnzbd.sh)"

### 📝 Provide a clear and concise description of the issue.

Installing on Ubuntu with advanced settings (static IP, privileged and verbose mode) causes this error: 

Installing via default settings works as intended.

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Ubuntu 22.04

### 🔄 Steps to reproduce the issue.

1. Open shell on pve and paste code from PVE helper scripts:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/sabnzbd.sh)"

2. Install in advanced mode. 

3. Check privileged
4. add static IP
5. add gateway
6. all following steps as suggested and verbose mode activated

### ❌ Paste the full error output (if available).

Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Err:1 http://deb.debian.org/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
 /
[ERROR] in line 25: exit code 0: while executing command $STD apt-get update

**Comment by michelroegl-brunner** [comment]
You are using the old repository. Please try again with this command; `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/sabnzbd.sh)"`

**Comment by michelroegl-brunner** [comment]
Any reason you need Ubunut 22.04? It installs fine under Debian 12.

**Comment by etzadla** [comment]
> Any reason you need Ubunut 22.04? It installs fine under Debian 12. But with ubunut i get the same error.

Ubuntu wasn´t really necessary, just personal preference, but I needed privileged. The default installation creates the container as unprivileged.

Found this workaround so far: I installed default, made a backup and restored it. When restoring it´s possible to make some changes, so I set it to static IP and made the container privileged. For now it works fine, but still don´t know why the installation in advanced mode fails.

**Comment by michelroegl-brunner** [comment]
It is not a issue with the advanced mode. You can create a Privileged LXC with debian 12 no problem. It probably will also work with ubuntu 24.04 (Not checked). It fails because of the "old" Ubunut version. There are some GPG keys missing it seems.
