### ISSUE TITLE
Debian VM disk space

### ISSUE THREAD

**Issue by uSlackr** [community-scripts/ProxmoxVE#822]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Debian 12 VM

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/vm/debian-vm.sh)"

### 📝 Provide a clear and concise description of the issue.

I'm creating a debian VM using the script and it creates the disk with on 2G drive.  I'm finding while trying to  patch it, it doesn't have sufficient space to recreate the initrd.img-6.1.0-21-amd64.  
I downloaded the script and tried editing line 410 to set the drive size to 6G, but that doesn't affect the initial disk size.  But issue is seen running direct from repo

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Run the vm script. Login to the shell.  Run `apt uppdate` and `apt upgrade`.  apt update fails with this issue and drive is now 97%

### ❌ Paste the full error output (if available).

Captured as an image - see below

### 🖼️ Additional context (optional).
![image](https://github.com/user-attachments/assets/adbaf4ea-0df3-46a4-a25f-b89efbc14da7)

**Comment by michelroegl-brunner** [comment]
You can either run the script in advanced mode and set a higher disk capacity there (you my leace the rest untouched if you want all other things to stay like the deafult settings), or you can after the installation resize the LXC disk in the Pproxmox UI. Look at something like [this](https://pakstech.com/blog/proxmox-increase-lxc-disk/) tutorial.

**Comment by uSlackr** [comment]
Advanced mode doesn't offer the option to increase the disk size. 
I tried resizing the disk using the proxmox gui.  It works fine but the VM does not see the new disk size.  Also there is not enough space in the VM to add `resize2fs` or `growpart` used to resize the disk in the vm.

**Comment by MickLesk** [comment]
What you do with the vm? Its an fresh clean vm?

fresh install:
![image](https://github.com/user-attachments/assets/12babf4b-5d25-4aae-be67-0fc8c684605e)

apt-get update & apt-get upgrade
![image](https://github.com/user-attachments/assets/add61f30-c2c3-4798-a771-ea0b496a67d1)

space after initramfs:
![image](https://github.com/user-attachments/assets/3841a78e-8ae9-4855-aec7-b2be3ecafa71)

but i can do it in a new pr.
