### ISSUE TITLE
Zoraxy will not update to latest version

### ISSUE THREAD

**Issue by ryaneford** [community-scripts/ProxmoxVE#826]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Zoraxy

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

I see that Zoraxy is on version 3.1.4 and when i type "update" in the LXC container, it says that it already is on that version but does not reflect at all on the client webpage even after rebooting.

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

- in the LXC shell, type update and agree to update

### ❌ Paste the full error output (if available).

` ✓ No update required. Zoraxy is already at v3.1.4`

### 🖼️ Additional context (optional).

<img width="387" alt="Screenshot 2024-12-14 at 6 44 18 PM" src="https://github.com/user-attachments/assets/cb573a09-5e2d-4144-877b-a11307192431" />

**Comment by dsiebel** [comment]
When did you first create your Zoraxy LXC?
There have been a few changes to the install and update scripts that might require some manual fixes, I'm afraid.

**Comment by dsiebel** [comment]
@ryaneford did you manage to fix your zoraxy install using the above link?

**Comment by MickLesk** [comment]
i close the issue for now. no interaction
