### ISSUE TITLE
Proxmox VE Post Install is not working on PVE 8.3+

### ISSUE THREAD

**Issue by leo852** [community-scripts/ProxmoxVE#832]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Proxmox VE Post Install

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"

### 📝 Provide a clear and concise description of the issue.

![Screenshot 2024-12-16 044212](https://github.com/user-attachments/assets/be29d359-dcd2-4ce9-933d-565bc476a379)

When running the script on proxmox ve 8.3.1, it shows:

Start the Proxmox VE Post Install Script (y/n)?y
 ✗ This version of Proxmox Virtual Environment is not supported
Requires Proxmox Virtual Environment Version 8.0 or later.
Exiting...

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Just type in the script, pressing y and enter

### ❌ Paste the full error output (if available).

Start the Proxmox VE Post Install Script (y/n)?y
 ✗ This version of Proxmox Virtual Environment is not supported
Requires Proxmox Virtual Environment Version 8.0 or later.
Exiting...

**Comment by MickLesk** [comment]
I don't understand it. This is the old repo. It's written there several times.
In the issue system it is pointed out several times which repo we have. It is pointed out to look through closed discussions and issues and then there are people who consistently ignore everything.

**Comment by pjgoodall** [comment]
The reason you are confused is - it's confusing (TM)

The third line on the page: https://tteck.github.io/Proxmox/#proxmox-ve-post-install
is: ` New home for the project: https://github.com/community-scripts/ProxmoxVE`

This page is the first point of call from a google search. The third line is ambiguous. It could be asserting that 'this page is the new page'.   It certainly threw me :-)

Perhaps change that line to 'There is a new home..., please access the scripts there. ' or words to that effect.

Cheers - and many thanks...
