### ISSUE TITLE
Docker / Frigate install error

### ISSUE THREAD

**Issue by bearli97** [community-scripts/ProxmoxVE#838]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Docker,

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/alpine-docker.sh)"

### 📝 Provide a clear and concise description of the issue.

I am trying to install Alpine Docker (for later having Frigate running inside) using the script on a Proxmox VE 8.3.
The install aborts with the following error:

`[ERROR] in line 34: exit code 1: while executing command PORTAINER_LATEST_VERSION=$(get_latest_release "portainer/portainer")`

Using Advanced Settings, but tried Default Settings anyway. Same Issue when turning on Verbose.

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12.8 on host

### 🔄 Steps to reproduce the issue.

open shell on main node PVE
enter install command

### ❌ Paste the full error output (if available).

Creating a Alpine-Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 107 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: ...
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker
[ERROR] in line 34: exit code 1: while executing command PORTAINER_LATEST_VERSION=$(get_latest_release "portainer/portainer")

**Comment by MickLesk** [comment]
Heh? You're talking about Docker, Debian 12 and sending in an Alpine script? What exactly are you trying to do? Revise your issue or I'll have to close it.

**Comment by remz1337** [comment]
So I tested the script (`bash -c "$(wget -qO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/alpine-docker.sh)"`) and installed portainer and everything worked fine.

```
...
 * service docker added to runlevel default
  ✔️  Installed Docker
Would you like to add Portainer? <y/N> y
   Installing Portainer 2.21.4Unable to find image 'portainer/portainer-ce:latest' locally
latest: Pulling from portainer/portainer-ce
2a8c27161aa3: Pull complete 
679061c2c821: Pull complete 
d40df14c1d7a: Pull complete 
8215717c7c10: Pull complete 
542669febe7c: Pull complete 
6c27c7f45b54: Pull complete 
070d3bf2528e: Pull complete 
846480e9f8b0: Pull complete 
c7053d7d4c2a: Pull complete 
a2ed6de7fb5f: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:f2a7f5abd4735f9cd91563c6134e014b15168c4018beea87f1eec9d9618b2ad4
Status: Downloaded newer image for portainer/portainer-ce:latest
a33a2b3808276035f717f42d70eb988094a910a0899b49aa3edb937e5448b48c
  ✔️  Installed Portainer 2.21.4
Would you like to add Docker Compose? <y/N> y
  ✔️  Installed Docker Compose v2.32.1
  ✔️  Customized Container
  ✔️  Completed Successfully!
```

**Comment by michelroegl-brunner** [comment]
Same for me, the install works fine. It seems to be a github api error or something when getting the latest release.

**Comment by mwilky** [comment]
Default options work but I get the same error when running through with the advanced settings, the container seems to install but error's before getting to the portainer option.

**Comment by bearli97** [comment]
@remz1337 
I did, comes up with the exact same error. What I've also tried: 

Reboot router. I have a simple setup, pve host wired to the router, no pihole or whatsoever. DHCP active on router, but static IP for the pve.

Reboot host.

My /etc/resolv.conf on pve host is:
search local
nameserver 192.168.1.1

**Comment by RafaG** [comment]
Same error here:
`                                   
  ⚙️  Using Default Settings on node g3
  🖥️  Operating System: debian
  🌟  Version: 12
  📦  Container Type: Unprivileged
  💾  Disk Size: 4GB
  🧠  CPU Cores: 2
  🛠️  RAM Size: 2048MB
  🆔  Container ID: 106
  🚀  Creating a Docker LXC using the above default settings
  
  ✔️  Using local for Template Storage.
  ✔️  Using local for Container Storage.
  ✔️  Updated LXC Template List
  ✔️  LXC Container 106 was successfully created.
  ✔️  Started LXC Container
  ✔️  Set up Container OS
  ✔️  Network Connected: 192.168.0.182 
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.121.4
  ✔️  Updated Container OS
  ✔️  Installed Dependencies

[ERROR] in line 26: exit code 0: while executing command DOCKER_LATEST_VERSION=$(get_latest_release "moby/moby")
root@g3:~# 
`

**Comment by MickLesk** [comment]
Looks Like DNS Error. GitHub call dont finished

**Comment by xyeoda** [comment]
this was affecting me as well but i had to use the following and then it worked....The error occurs because GitHub blocks unauthenticated API requests after a few attempts.

sudo apt install -y jq && \
GITHUB_TOKEN="ghp_your_token_here" bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/docker.sh)"

**Comment by MickLesk** [comment]
You know its the old repo?

**Comment by bearli97** [comment]
@xyeoda 
Thank you! I changed to url according to my needs and, well, it runs like clockwork.
