### ISSUE TITLE
Error executing Pihole installation script when choosing to install Unbound

### ISSUE THREAD

**Issue by TroLLzOr97** [community-scripts/ProxmoxVE#85]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the Pi-hole installation script, an error occurs while attempting to download the root.hints file into the /var/lib/unbound/ directory. The script propably fails because the directory does not exist.
The script fails with the following error message: 
`[ERROR] in line 97: exit code 0: while executing command wget -qO /var/lib/unbound/root.hints https://www.internic.net/domain/named.root`

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 107
Using Hostname: pihole
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Pihole LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 107 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.178.49 fd00:a92a:a309:eb15:be24:11ff:fe62:10d1 2003:e8:4f12:4e00:be24:11ff:fe62:10d1 
 ✓ IPv4 Internet Connected
 ✓ IPv6 Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Pi-hole
Would you like to add Unbound? <y/N> y
 | Installing Unbound   
[ERROR] in line 97: exit code 0: while executing command wget -qO /var/lib/unbound/root.hints https://www.internic.net/domain/named.root
```

### Please provide detailed steps to reproduce the issue.

1. Execute the Pihole installation script on a Proxmox server.
2. During the installation of Unbound, the error occurs.

**Comment by ahmed-habbachi** [comment]
I had the same issue but when I checked unbound I found out that it is configured to be using 5335 if in your configuration it is not just change that and just restart your machine and everything should be fine.

**Comment by newzealandpaul** [comment]
I just tried it. It ran without issue. Can you try it again and see if you get this error again.

Can you also try running this on your main proxmox shell to see if it works.

```
wget https://www.internic.net/domain/named.root
```

**Comment by havardthom** [comment]
Script also works fine here.

🌐 It seems that you're facing a network problem, probably linked to DNS.
