### ISSUE TITLE
Proxmox VE LXC IP-Tag Stuck Pending Shell Icon

### ISSUE THREAD

**Issue by rustikles** [community-scripts/ProxmoxVE#850]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Proxmox VE LXC IP-Tag

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/add-lxc-iptag.sh)"

### 📝 Provide a clear and concise description of the issue.

Install on current version proxmox VE host from web shell. Observed the "in-progress" six dot icon stuck around after the script finished executing. Pressing enter does not clear. A quick click away and back to reset the shell fixes it, so not a game breaking item.

![image](https://github.com/user-attachments/assets/e63eb9d5-0de0-4825-a392-97451f1326db)

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

1. Run script from PVE host web shell
2. Observe broken shell display

### ❌ Paste the full error output (if available).

![image](https://github.com/user-attachments/assets/41b14101-3f4a-4df4-85ec-a04fe3c572a3)

**Comment by MickLesk** [comment]
its done, the animation stuck only. But the Service is done. 

Fix with spinner comes in next pr (already done)
