### ISSUE TITLE
z2m ssh root access is not working after last script update 

### ISSUE THREAD

**Issue by eugenjy** [community-scripts/ProxmoxVE#854]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Zigbee2MQTT

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/zigbee2mqtt.sh)"

### 📝 Provide a clear and concise description of the issue.

After the last update, on fresh installation, root ssh access not working. Access denied for root through ssh after installation. 

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Choose Root ssh Access - yes on advanced settings 

### ❌ Paste the full error output (if available).

no access for root through ssh

**Comment by MickLesk** [comment]
thats a issue with zigbee2mqtt script, not with root ssh, or can you reproduce this on all cts? 

I cant reproduce this.

**Comment by eugenjy** [comment]
@MickLesk Yes, there is an issue with the z2m script. This is a fresh install. I tried three times. There were no issues in the previous version of the script. I needed to edit the SSH config after installation.

**Comment by MickLesk** [comment]
Yes, we know. But we cant fix it at the moment. The Devs are mixing Up branches. In january it should be all zigbee2mqtt v2

At the moment its an Mix of yarn, pnpm, Dev und Main.
