### ISSUE TITLE
Incorrect port displayed after PLEX installation

### ISSUE THREAD

**Issue by Yokosa** [community-scripts/ProxmoxVE#866]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Incorrect port displayed after PLEX installation

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/plex.sh)"

### 📝 Provide a clear and concise description of the issue.

After proper installation of PLEX server via shell, the wrong server address is displayed.
We get information that it is available on port 23400/web, however, the default port is 32400, and we will find the PLEX server on such port.

### ⚙️ What settings are you using?

- [ ] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Ubuntu 22.04

### 🔄 Steps to reproduce the issue.

 run the command below in the Proxmox VE Shell
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/plex.sh)"

### ❌ Paste the full error output (if available).

![plex](https://github.com/user-attachments/assets/065495f9-9a5b-464a-a913-05cce8986d4c)

**Comment by MickLesk** [comment]
Done
