### ISSUE TITLE
Error (line24) running Jellyfin script 

### ISSUE THREAD

**Issue by sciencegeek2087** [community-scripts/ProxmoxVE#87]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

running the Jellyfin set up script, results in a container set up but a debian error when |Unpacking libllvm14:amd64 (1:14.0.6-12) ...

cant use defaulkt cos i have to have IP static pass through my internet connection

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

'''
Preparing to unpack .../31-libllvm14_1%3a14.0.6-12_amd64.deb ...
 |Unpacking libllvm14:amd64 (1:14.0.6-12) ...
 /dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/31-libllvm14_1%3a14.0.6-12_amd64.deb (--unpack):
 unable to sync new file '/var/lib/dpkg/info/libllvm14:amd64.list-new': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/32-libllvmspirvlib14_14.0.0-5_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/33-libigc1_1.0.12504.6-1+deb12u1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
 -dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/34-libclang-cpp14_1%3a14.0.6-12_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/35-libopencl-clang14_14.0.0-4_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/36-libigdfcl1_1.0.12504.6-1+deb12u1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/37-ocl-icd-libopencl1_2.3.1-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/38-intel-opencl-icd_22.43.24595.41-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/39-libdrm-radeon1_2.4.114-1+b1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/40-libllvm15_1%3a15.0.6-4+b1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/41-libva-drm2_2.17.0-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/42-libwayland-client0_1.21.0-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/43-libva-wayland2_2.17.0-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/44-libx11-xcb1_2%3a1.8.4-2+deb12u2_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/45-libxcb-dri3-0_1.15-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
 \dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/46-libxfixes3_1%3a6.0.0-2_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/47-libva-x11-2_2.17.0-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/48-libxcb-dri2-0_1.15-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/49-libxcb-present0_1.15-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/50-libxcb-sync1_1.15-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/51-libxcb-xfixes0_1.15-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/52-libxshmfence1_1.3-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/53-mesa-va-drivers_22.3.6-1+deb12u1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/54-va-driver-all_2.17.0-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error processing archive /tmp/apt-dpkg-install-op7zN5/55-vainfo_2.12.0+ds1-1_amd64.deb (--unpack):
 unable to sync file '/var/lib/dpkg/tmp.ci//control': Input/output error
dpkg: error: unable to sync new file '/var/lib/dpkg/status-new': Input/output error
 /E: Sub-process /usr/bin/dpkg returned an error code (2)

[ERROR] in line 24: exit code 0: while executing command $STD apt-get -y install {va-driver-all,ocl-icd-libopencl1,intel-opencl-icd,vainfo,intel-gpu-tools}
root@basil:~# 
'''

### Please provide detailed steps to reproduce the issue.

liteartly just using the bash script provided

**Comment by newzealandpaul** [comment]
Are you out of disk space?

What happens if you try install with the defaults? I know you want a static IP, but it would help to know if this occurs with the defaults.

**Comment by sciencegeek2087** [comment]
> Are you out of disk space?
> 
> What happens if you try install with the defaults? I know you want a static IP, but it would help to know if this occurs with the defaults.

With defaults it's can't connect to the Internet cos my gateway has to be my main PC , hence the static IP

**Comment by newzealandpaul** [comment]
The error seems to indicate either a issue with your hard drive/ssd or internet connection. 

Are you on UFB? Is your computer plugged directly into the ONT?

**Comment by MickLesk** [comment]
1. Check your Drive:
sudo fsck -f /dev/<device>
dmesg | grep -i 'error\|fail'

2. Enough Space ? Or its full?

3. Reinstall packages:
sudo apt-get clean
sudo apt-get update
sudo apt-get install --reinstall {va-driver-all,ocl-icd-libopencl1,intel-opencl-icd,vainfo,intel-gpu-tools}

4. Check your RAM for errors

**Comment by sciencegeek2087** [comment]
gparted , increased partition sda3
updated using:
lvextend -l +100%FREE /dev/pve/root
resize2fs /dev/pve/root

Script works :D

 ✓ Installed Jellyfin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
 |0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
 ✓ Cleaned
 ✓ Completed Successfully!

Jellyfin should be reachable by going to the following URL.
             http://192.168.100.4:8096

**Comment by sciencegeek2087** [comment]
thanks for fast and helpful advice, all
