### ISSUE TITLE
WireGuard LXC installation does not work

### ISSUE THREAD

**Issue by milandzuris** [community-scripts/ProxmoxVE#881]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

WireGuard LXC

### 📂 What was the exact command used to execute the script?

*

### 📝 Provide a clear and concise description of the issue.

installation does not work

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

*

### ❌ Paste the full error output (if available).

```
  ✔️  Installed WireGuard
 ⠹------------------------------------------------------------
[WGDashboard] Starting to install WGDashboard
[WGDashboard] Creating /etc/wireguard/WGDashboard_Backup folder
[WGDashboard] Creating ./log folder
[WGDashboard] OS: debian
[WGDashboard] ✔ Python is installed
[WGDashboard] ✗ Could not find a compatible version of Python. Current Python is Python 3.9.2.
[WGDashboard] WGDashboard required Python 3.10, 3.11 or 3.12. Halting install now.
Terminated

[ERROR] in line 34: exit code 0: while executing command $STD ./wgd.sh install
root@dzurisserver:~# python3 --version
Python 3.11.2
```

![image](https://github.com/user-attachments/assets/9fda918f-df81-44e9-9086-9a0cd37d2fcd)

```
[WGDashboard] Starting to install WGDashboard
[WGDashboard] Creating /etc/wireguard/WGDashboard_Backup folder
 ⠋[WGDashboard] Creating ./log folder
[WGDashboard] OS: ubuntu
[WGDashboard] ✔ Python is installed
[WGDashboard] ✗ Could not find a compatible version of Python. Current Python is Python 3.8.10.
[WGDashboard] WGDashboard required Python 3.10, 3.11 or 3.12. Halting install now.
Terminated

[ERROR] in line 33: exit code 0: while executing command $STD ./wgd.sh install
```

**Comment by MickLesk** [comment]
@daanselen @donaldzou
Is this an issue of your Software? We only start wgd.sh and this install python3.

We can Install python3 before, but i think its an issue in your dependencies?

**Comment by DaanSelen** [comment]
I am going to try to reproduce.

**Comment by DaanSelen** [comment]
I used:
```shell
 _       ___                                      __
| |     / (_)_______  ____ ___  ______ __________/ /
| | /| / / / ___/ _ \/ __ `/ / / / __ `/ ___/ __  / 
| |/ |/ / / /  /  __/ /_/ / /_/ / /_/ / /  / /_/ /  
|__/|__/_/_/   \___/\__, /\__,_/\__,_/_/   \__,_/   
                   /____/                           
  🧩  Using Advanced Settings
  🖥️  Operating System: debian
  🌟  Version: 12
  📦  Container Type: Unprivileged
  🔐  Root Password: ********
  🆔  Container ID: 101
  🏠  Hostname: wireguard
  💾  Disk Size: 4
  🧠  CPU Cores: 2
  🛠️  RAM Size: 1024
  🌉  Bridge: vmbr0
  📡  IP Address: dhcp
  🌐  Gateway IP Address: Default
  📡  APT-Cacher IP Address: Default
  🚫  Disable IPv6: yes
  ⚙️  Interface MTU Size: Default
  🔍  DNS Search Domain: Host
  📡  DNS Server IP Address: 192.168.178.30
  🏷️  Vlan: Default
  🔑  Root SSH Access: yes
  🔍  Verbose Mode: yes
  🚀  Creating a Wireguard LXC using the above advanced settings
  ✔️  Using Proxmox for Template Storage.
  ✔️  Using Proxmox for Container Storage.
  ✔️  Updated LXC Template List
  ✔️  LXC Container 101 was successfully created.
  ✔️  Started LXC Container
net.ipv6.conf.all.disable_ipv6 = 1
  ✔️  Set up Container OS
  ✔️  Network Connected: 192.168.178.156 
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.121.4
```

I tried running with both standard and advanced install with the details above... but it works...

```shell
 ⠙run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables start
 ⠹run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables start
  ✔️  Installed WireGuard
 ⠇------------------------------------------------------------
[WGDashboard] Starting to install WGDashboard
[WGDashboard] Creating /etc/wireguard/WGDashboard_Backup folder
[WGDashboard] Creating ./log folder
[WGDashboard] OS: debian
[WGDashboard] ✔ Python is installed
 ⠋[WGDashboard] ✔ Python Virtual Environment is installed
 ⠦[WGDashboard] ✔ Python Package Manager (PIP) is installed
[WGDashboard] WireGuard is already installed.
 ⠧[WGDashboard] Creating ./db folder
[WGDashboard] Creating Python Virtual Environment under ./venv
 ⠦[WGDashboard] Upgrading Python Package Manage (PIP)
 ⠼[WGDashboard] Installing latest Python dependencies
 ⠏[WGDashboard] WGDashboard installed successfully!
[WGDashboard] Enter ./wgd.sh start to start the dashboard
------------------------------------------------------------
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv4.ip_forward = 1
  ✔️  Installed WGDashboard
  ✔️  Created Example Config for WGDashboard
  ✔️  Created Service
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
 ⠸0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
  ✔️  Cleaned
  ✔️  Completed Successfully!

  🚀  Wireguard setup has been successfully initialized!
  💡   WGDashboard Access it using the following URL:
    🌐  http://192.168.178.156:10086
root@Osiris:~#
```

Can you share your initial values @milandzuris ?

**Comment by tjcomserv** [comment]
@milandzuris Pleas an you confirm that the LXC has been created? If so, can you access it from the Proxmoxroot shell using:

`pct enter <containerId>`

Then get the python3 version from here:

`python3 --version`

Then can you try updating and upgrading the container:

`apt update && apt upgrade -y`

Once done, whilst in the container, can you try running the script again:

`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/wireguard.sh)"`

I think that maybe, the apt update (as run by wgd.sh) is pulling from an outdated repository. (Could be a DNS Issue IDK)

**Comment by maniac79** [comment]
Hi,
found this by googling, because I'm unable to update my LXC, I'm getting the same error message when I try to update via the script:

Hit:1 http://security.debian.org bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[WGDashboard] OS: debian
[WGDashboard] ✔ Python is installed
[WGDashboard] ✗ Could not find a compatible version of Python. Current Python is Python 3.9.2.
[WGDashboard] WGDashboard required Python 3.10, 3.11 or 3.12. Halting install now.
Terminated

[ERROR] in line 39: exit code 0: while executing command ./wgd.sh update
