### ISSUE TITLE
Omada install script not getting latest version due to filename change

### ISSUE THREAD

**Issue by physdl** [community-scripts/ProxmoxVE#889]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Omada Controller LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/omada.sh)"

### 📝 Provide a clear and concise description of the issue.

The Omada install script runs "grep -o 'https://.*x64.deb'" to find the latest downloadable package from the TP Link listing of Omada downloads. However, it looks like for the latest version (5.15.6.7) has switched to a different filename: https://static.tp-link.com/upload/software/2024/202412/20241205/omada_v5.15.6.7_linux_x64_20241128140044.deb

This results in the script downloading the prior version. Manually downloading the file and installing it via dpkg works fine.

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Attempt to update Omada but latest version is not downloaded

### ❌ Paste the full error output (if available).

n/a

**Comment by MickLesk** [comment]
work fine for me:

![image](https://github.com/user-attachments/assets/b9e9034f-d67b-4923-a04a-0492cbe69916)

**Comment by physdl** [comment]
Hi @MickLesk, installation works but does not install the latest version. Can you check what version it installed for you? When I used the script it installed 5.14, not 5.15.

**Comment by MickLesk** [comment]
The script was always downloading the older version because the URL structure had changed, and the script was still looking for older patterns. By updating the URL extraction to handle the new format, it now correctly fetches the latest version.
