### ISSUE TITLE
Ombi does not update to latest version

### ISSUE THREAD

**Issue by ChristophCaina** [community-scripts/ProxmoxVE#907]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

ombi

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/ombi.sh)"

### 📝 Provide a clear and concise description of the issue.

Ombi is showing that a new version is available.
Version 4.46.7 as shown in the screenshot.

![image](https://github.com/user-attachments/assets/adb22f13-ab52-4233-9661-26685b17e73c)

While running the Script in the LXC as usual, the update process is showing, that Ombi is at the latest version of 4.44.1
![image](https://github.com/user-attachments/assets/dd84a563-a8b9-4191-862c-3346510af49f)

### ⚙️ What settings are you using?

- [ ] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

update existing ombi installation based on 4.44.1

### ❌ Paste the full error output (if available).

n/a

**Comment by michelroegl-brunner** [comment]
Not a bug. The latest GH Release ist 4.44.1. Alll other Versions are marke as Pre Release at the moment. [OMBI GH](https://github.com/Ombi-app/Ombi/releases)

**Comment by ChristophCaina** [comment]
ah :) Ok, sorry ... 👍
