### ISSUE TITLE
Sabnbzd - Update to 4.4.0 failing

### ISSUE THREAD

**Issue by crazyduck** [community-scripts/ProxmoxVE#922]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

SABnzbd

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/sabnzbd.sh)"

### 📝 Provide a clear and concise description of the issue.

Running the script inside the LXC.

Script fails with this output:
```
 ⠼ Updating SABnzbd to 4.4.0 
[ERROR] in line 43: exit code 0: while executing command python3 -m pip install -r requirements.txt &> /dev/null

```

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Running the script inside an existing SABnbzd LXC

### ❌ Paste the full error output (if available).

 ⠼ Updating SABnzbd to 4.4.0 
[ERROR] in line 43: exit code 0: while executing command python3 -m pip install -r requirements.txt &> /dev/null

**Comment by crazyduck** [comment]
Installed the update by hand:

`cd /opt/sabnbzd
python3 -m pip install -r requirements.txt &> /dev/null
systemctl start sabnzbd.service`

**Comment by MickLesk** [comment]
https://github.com/community-scripts/ProxmoxVE/discussions/555
