### ISSUE TITLE
Alpine-Nextcloud: can't upload files bigger than 1/2MB (easy fix)

### ISSUE THREAD

**Issue by NetMan134** [community-scripts/ProxmoxVE#927]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Alpine-Nextcloud LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/alpine-nextcloud.sh)"

### 📝 Provide a clear and concise description of the issue.

`/etc/php83/php.ini`
`upload_max_filesize` is `2M` by default (also set `post_max_size`)

`/etc/nginx/http.d/nextcloud.conf`
does not have a `client_max_body_size` variable set

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Alpine

### 🔄 Steps to reproduce the issue.

1. Install Nextcloud
2. Log in
3. Try to upload a file (>1/2MB)
4. HTTP Error 413 or "Unknown error while uploading"

### ❌ Paste the full error output (if available).

not relevant

**Comment by MickLesk** [comment]
@michelroegl-brunner that can you do ^^

**Comment by michelroegl-brunner** [comment]
Can do, will prop. take me a day or two.
