### ISSUE TITLE
CheckMK installation error

### ISSUE THREAD

**Issue by PCE-Consulting** [community-scripts/ProxmoxVE#935]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

CheckMK

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/checkmk.sh)"

### 📝 Provide a clear and concise description of the issue.

Install fails with the following error:

  ✔️  Using local for Template Storage.
  ✔️  Using local for Container Storage.
  ✔️  Updated LXC Template List
  ✔️  LXC Container 103 was successfully created.
  ✔️  Started LXC Container
  ✔️  Set up Container OS
  ✔️  Network Connected: xxx.xxx.xxx.xxx
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.121.4
  ✔️  Updated Container OS
  ✔️  Installed Dependencies
 ⠙ Install Checkmk 
**[ERROR] in line 44: exit code 0: while executing command "$@" > /dev/null 2>&1**

I used advanced settings and set the network bridge, ip and gateway - nothing else.

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Open host shell, paste the install command, run the script

### ❌ Paste the full error output (if available).

[ERROR] in line 44: exit code 0: while executing command "$@" > /dev/null 2>&1

**Comment by michelroegl-brunner** [comment]
Please run the script in verbose mode to see the error message.

**Comment by PCE-Consulting** [comment]
Okay, here is the output:

dpkg: error processing package check-mk-raw-2.3.0p23 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 check-mk-raw-2.3.0p23

[ERROR] in line 27: exit code 0: while executing command $STD dpkg -i /opt/checkmk.deb

**Comment by MickLesk** [comment]
try again in 5-10 min

**Comment by PCE-Consulting** [comment]
No stress, thank you for your fast responses and the fix :)

**Comment by MickLesk** [comment]
Running now?

**Comment by Pommmmmes** [comment]
Well the installation works but the autologin won't work

**Comment by MickLesk** [comment]
Fixed, please reinstall
