### ISSUE TITLE
Zabbix update script points to old version 

### ISSUE THREAD

**Issue by Hindin81** [community-scripts/ProxmoxVE#937]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Zabbix LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/zabbix.sh)"

### 📝 Provide a clear and concise description of the issue.

The Update script point to the old version 7.0: 
`wget -q https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian12_all.deb`
The actual version is: 
`wget https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian12_all.deb`

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Running the update script installs not the new version 7.2. 

### ❌ Paste the full error output (if available).

It always remains on version 7.0. because the new version 7.2 is not referenced.

**Comment by MickLesk** [comment]
Not an issue. Its an Feature-Request. Investigate later
