### ISSUE TITLE
CheckMK does not show how/where to find the login credentials

### ISSUE THREAD

**Issue by magixnetworks** [community-scripts/ProxmoxVE#938]
### Please verify that you have read and understood the guidelines.

yes

### What type of issue is this?

Documentation

### A clear and concise description of the issue.

CheckMK does not show how/where to find the login credentials
I had to check the source code to find a reference to credentials

### Which browser are you using?

Safari

### Please provide detailed steps to reproduce the issue.

Read description

**Comment by MickLesk** [comment]
Fixed, please reinstall. Command added to website
