### ISSUE TITLE
Omada Software Controller error

### ISSUE THREAD

**Issue by TheCeet** [community-scripts/ProxmoxVE#939]
### ✅ Have you read and understood the above guidelines?

Yes

### 📜 What is the name of the script you are using?

Omada Controller LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/omada.sh)"

### 📝 Provide a clear and concise description of the issue.

`[ERROR] in line 41: exit code 0: while executing command latest_url=$(curl -fsSL "https://www.tp-link.com/en/support/download/omada-software-controller/" | grep -oP 'href="([^"]+linux_x64[^"]+\.deb)' | sed 's/href="//' | sort | tail -n 1)`

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Just excecude the install script.

### ❌ Paste the full error output (if available).

✔️  Installed MongoDB

[ERROR] in line 41: exit code 0: while executing command latest_url=$(curl -fsSL "https://www.tp-link.com/en/support/download/omada-software-controller/" | grep -oP 'href="([^"]+linux_x64[^"]+\.deb)' | sed 's/href="//' | sort | tail -n 1)

**Comment by liveware-problems** [comment]
I was just going to raise an issue as the Update script has a similar problem:

> [ERROR] in line 34: exit code 0: while executing command latest_url=$(curl -fsSL "https://www.tp-link.com/en/support/download/omada-software-controller/" | grep -oP 'href="([^"]+linux_x64[^"]+\.deb)' | sed 's/href="//' | sort | tail -n 1)

It looks like the URL in the script now redirects to https://support.omadanetworks.com/en/product/omada-software-controller/ and from there you need to select the `Downloads` page which adds a URL param to make it https://support.omadanetworks.com/en/product/omada-software-controller/?resourceType=download

**Comment by MickLesk** [comment]
They change their shitty site and their link structure like I change my underpants. So annoying

**Comment by liveware-problems** [comment]
Update looks good though, thanks @MickLesk !

> Unpacking omadac (5.15.6.7) over (5.14.32.3) ...
Setting up omadac (5.15.6.7) ...
Install Omada Controller succeeded!
