### ISSUE TITLE
Issue with DNS in nextcloud script

### ISSUE THREAD

**Issue by gitarman94** [community-scripts/ProxmoxVE#94]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

I may have found an issue with the installer script? I've got protected DNS, and force all traffic on my network to go through my DNS server, all other traffic gets blocked (for security reasons). The installer script kept failing saying it couldn't find the raw.githubusercontent.com website, but apt was able to install packages just fine prior to the attempted product install. After looking at the code, I found the below...

cat <<'EOF' >/etc/systemd/resolved.conf
[Resolve]
DNS=8.8.8.8
FallbackDNS=8.8.4.4
EOF

It appears that you're manually pointing the lxc to google as a valid DNS server to resolve addresses. This is a departure from a number of your other scripts, and In my case, this broke the installer as I'm blocking google DNS (for security/tracking purposes). I was able to modify the file post failure to point at my DNS server, and then copy/paste the remainder of the script, but this code should probably default to the base system's dns server (or utilize the address that was prompted for during the setup wizard).

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Have a network mandated DNS server where all DNS queries not directed at that server get blocked at the firewall.

**Comment by MickLesk** [comment]
https://github.com/community-scripts/ProxmoxVE/discussions/5#discussioncomment-11131054
