### ISSUE TITLE
Checkmk LXC - Default password unknown, and landing page not in root

### ISSUE THREAD

**Issue by Possemaster** [community-scripts/ProxmoxVE#942]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Checkmk LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/checkmk.sh)"

### 📝 Provide a clear and concise description of the issue.

Default username and password are not chown.
Website default username and password do not work so something must go wrong in the script as it also does not echo the credentials.

This part of the script does not function;

```
PASSWORD=$(omd create monitoring | grep "password:" | awk '{print $NF}')
$STD omd start
{
    echo "Application-Credentials"
    echo "Username: cmkadmin"
    echo "Password: $PASSWORD"
} >> ~/checkmk.creds
```

2nd issue is that the tool is installed with the landing page in the folder /monitoring and the root is empty. Please recreate this so the root is the landing page. This is unusable for reverse proxy without rewrites and stuff while there is no use to have the landing page under /monitoring for a standalone instance.

### ⚙️ What settings are you using?

- [X] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Install script

### ❌ Paste the full error output (if available).

No visible error.
Only username and password are unknown

**Comment by michelroegl-brunner** [comment]
Part 1 we have to check.

Part two: This is how checkmk works. we can not easily change the webroot, as checkmk is intendet ro support more then one Monitoringsite.

**Comment by Possemaster** [comment]
I think this is the culprit the $ is misplaced

```
PASSWORD=$(omd create monitoring | grep "password:" | awk '{print $NF}')
$STD omd start
{
    echo "Application-Credentials"
    echo "Username: cmkadmin"
    echo "Password: $PASSWORD"
} >> ~/checkmk.creds
```

Should be

```
$PASSWORD=(omd create monitoring | grep "password:" | awk '{print $NF}')
$STD omd start
{
    echo "Application-Credentials"
    echo "Username: cmkadmin"
    echo "Password: $PASSWORD"
} >> ~/checkmk.creds
```

**Comment by michelroegl-brunner** [comment]
In bash you have no leading $ when declaring a variable, this is not the issue.

**Comment by Possemaster** [comment]
> In bash you have no leading $ when declaring a variable, this is not the issue.

OK, then I will leave it to the Pros 😄

**Comment by MickLesk** [comment]
idk what you do, for me the script is working absolutely correctly.

![image](https://github.com/user-attachments/assets/1828b2dd-a6be-4fc7-a969-c41512b617cb)


![image](https://github.com/user-attachments/assets/81e0d124-2b3e-45ac-a3e5-5501fdb71902)

![image](https://github.com/user-attachments/assets/ae8eaea7-beab-4908-9143-605d0efc6c79)

**Comment by Possemaster** [comment]
I do not see anywhere I need to get my credentials from a file.
Maybe I am blind but I do not see any instruction at the script and during running of the script that I need to get my credentials from the checkmk.creds file. I am not a scripting Guru or Unix hero. That is why I rely on these scripts. 😄 
![image](https://github.com/user-attachments/assets/13488740-c295-43be-a5fa-feec336128c3)

**Comment by Possemaster** [comment]
So consider it a User issue then and not a "bug". 
But imo you should at least communicate it somewhere for the NON Scriptkiddies

**Comment by michelroegl-brunner** [comment]
Thats on me, i missed it when i created the json file. @MickLesk fixed it and is now visible on the  website
![image](https://github.com/user-attachments/assets/a406f41c-dff6-4dc4-b42f-d247da97ffd6)

**Comment by MickLesk** [comment]
> I do not see anywhere I need to get my credentials from a file.
> Maybe I am blind but I do not see any instruction at the script and during running of the script that I need to get my credentials from the checkmk.creds file. I am not a scripting Guru or Unix hero. That is why I rely on these scripts. 😄 
> ![image](https://github.com/user-attachments/assets/13488740-c295-43be-a5fa-feec336128c3)
> 


Clear your Cache

**Comment by Possemaster** [comment]
Thanks so much for the support. 
Works great.
