### ISSUE TITLE
Vaultwarden Alpine Update - getting error

### ISSUE THREAD

**Issue by gomble** [community-scripts/ProxmoxVE#956]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Vaultwarden LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/alpine-vaultwarden.sh)"

### 📝 Provide a clear and concise description of the issue.

Gettin following error if i run update:

```
/dev/fd/63: line 173: tput: command not found                                                                                                                                                                                     

[ERROR] in line 173: exit code 0: while executing command term_width=$(tput cols)

alpine-vaultwarden:~# 
```

I searched how to activate verbose mode but didnt find anything.

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Alpine

### 🔄 Steps to reproduce the issue.

run:
bash -c "$(wget -qO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/alpine-vaultwarden.sh)"
select update

### ❌ Paste the full error output (if available).

```
/dev/fd/63: line 173: tput: command not found                                                                                                                                                                                     

[ERROR] in line 173: exit code 0: while executing command term_width=$(tput cols)

alpine-vaultwarden:~# 
```

**Comment by MickLesk** [comment]
Can you test it again in 10 to 15min?

**Comment by gomble** [comment]
> Can you test it again in 10 to 15min?

yeah, write me here and then i will test it

**Comment by MickLesk** [comment]
Its done & fixed, but GitHub need Sometimes 10-15min to push the change for curl / wget ^^

**Comment by gomble** [comment]
> Its done & fixed, but GitHub need Sometimes 10-15min to push the change for curl / wget ^^

![image](https://github.com/user-attachments/assets/1457d1a4-788b-4216-a308-10dce78fd35b)

thank you 👍
