### ISSUE TITLE
Navidrome update fails

### ISSUE THREAD

**Issue by symphonyalpha** [community-scripts/ProxmoxVE#958]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Navidrome

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

When updating an existing Navidrome container, the script does not perform a `chmod +x` on the new binary which prevents the Navidrome service from starting up. 

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Run `update` in an already created container. 

### ❌ Paste the full error output (if available).

Nil

### 🖼️ Additional context (optional).

https://github.com/community-scripts/ProxmoxVE/blob/67a0c06b806aff58688d1bf9dd6c9ff5564a771e/ct/navidrome.sh#L41-L42

I've tested running the above commands from the script manually but the new binary still does not have the executable flag set which prevents the Navidrome service from starting. 

Relevant screenshot: 

![image](https://github.com/user-attachments/assets/4b939770-78bc-4405-9404-048f77bf39a3)

**Comment by ehcloninger** [comment]
I tried to create a new LXC from navidrome today and this may be the same problem. The container was created, but there was no navidrome.service created from the contents of /opt/navidrome. I had previously created containers from the scripts for calibre-web and audiobookshelf from the scripts in the last 2 days, so this may be unique to the navidrome script.

**Comment by MickLesk** [comment]
Can you test the dev branch?

```bash
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/develop/ct/navidrome.sh)"
```

**Comment by symphonyalpha** [comment]
Just tried it and Navidrome was able to start up fine after the update! 

![image](https://github.com/user-attachments/assets/81a175d1-cb6c-46b9-ba84-080bfc108e9a)

**Comment by MickLesk** [comment]
Okay fine, im not on PC today, i prepare the PR tomorrow

**Comment by ehcloninger** [comment]
@MickLesk I can also confirm that it worked on a new install where yesterday the script in `main` did not. Thanks!

**Comment by arnob216** [comment]
Yap, main script is not working, update or fresh.
