### ISSUE TITLE
APACHE GUACAMOLE : RDP CONNECTION ERROR

### ISSUE THREAD

**Issue by sannier3** [community-scripts/ProxmoxVE#968]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

apache-guacamole

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/apache-guacamole.sh)"

### 📝 Provide a clear and concise description of the issue.

I am encountering an issue with RDP connections. Whenever I try to initiate an RDP session, I get an error that seems to indicate an internal issue, but I am unsure how to resolve it.

### ⚙️ What settings are you using?

- [X] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

[ScriptInstallLogsCustom.log](https://github.com/user-attachments/files/18220372/ScriptInstallLogsCustom.log)
[ScriptInstallLogsDefault.log](https://github.com/user-attachments/files/18220382/ScriptInstallLogsDefault.log)
[Apache Guacamole Host Configuration.pdf](https://github.com/user-attachments/files/18220363/Apache.Guacamole.Host.Configuration.pdf)

### ❌ Paste the full error output (if available).

![Capture d'écran 2024-12-21 113935](https://github.com/user-attachments/assets/bb237f3e-1612-4e58-9ad1-ea308eef0f20)

**Comment by ipod86** [comment]
Same here
![Screenshot_20241222_100711_Chrome](https://github.com/user-attachments/assets/a4bbb824-35c9-4866-bd8b-9d75e9467c16)

**Comment by lichtenstern** [comment]
Same here

**Comment by michelroegl-brunner** [comment]
Ive looked into it but can not realy find the issue. Im no Guacamole user myself. Probably best if you ask in related forums what the issue might be. It installs fine and i do not see a issue with the scripts so far. Sadly i can not provide deeper help for every app in the repository. If you end up finding the error and it is related to how we install Apache Guacamole, let me know and i Update the Script acordingly!

**Comment by lichtenstern** [comment]
I think its how quaca is inside the container. I Also tried on another Host. Same Issue.
Install and site is running fine, but no connection is possible to rdp, ssh or telnet hosts
Dont know how to troubleshoote but willing to help.

**Comment by MickLesk** [comment]
can everyone try to use an debian or ubuntu vm and enter the install functions of -install.sh? (without STD)

Work this? 
Otherwise we remove guacamole completely.

**Comment by lichtenstern** [comment]
So I just installed debian vm on my proxmox.
Can you tell me what I should install/run?

**Comment by MickLesk** [comment]
Look at the Install folder apache-guacamole-install.sh

And Look the commands

**Comment by lichtenstern** [comment]
So after 3 hours I quit. I am not a developer. Also not to deep in linux.
I do not get it installed. Sorry

**Comment by sannier3** [comment]
Hi everyone,
Thank you for your responses and for looking into the issue. I will investigate further on my side to identify what might be causing this problem. If I manage to find a solution or pinpoint the root cause, I will provide feedback here so it can potentially help resolve the issue in the script or its configuration.

**Comment by itkfilelor** [comment]
If in the build script you can leave an option for selecting a version, it may be beneficial. I tried several different methods to get it working and I couldn't get it going. Finally I tried installing version 1.5.3 (current is 1.5.5) and everything works.

**Comment by Homer-Sim** [comment]
same here, 
what is/was the solution and what to do?

thanks for yur great work!
