### ISSUE TITLE
Apache Guacamole - An internal error has occurred within the Guacamole server, and the connection has been terminated

### ISSUE THREAD

**Issue by vicky-bs** [community-scripts/ProxmoxVE#985]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Apach - Guacamole

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/apache-guacamole.sh)"

### 📝 Provide a clear and concise description of the issue.

Getting error whenever creating a new connection. Even if the connection is SSH, RDP, VNC etc. Same error everytime. 

Steps tried
1. Reinstalled many times but still see the same issue
2. Changed network port but still see the same error
![Screenshot 2024-12-23 180241](https://github.com/user-attachments/assets/4af59c06-19aa-4f73-b7e8-6f3a21951ded)

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Normal installation with no advance settings on Debian 12 (Proxmox 8.3.2 - latest kernel)

### ❌ Paste the full error output (if available).

An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs.

**Comment by lichtenstern** [comment]
Same here. RDP, SSH Telnet... Same Error
